"local orca = require 'orca'\n"
"local Behaviour = {}\n"

"function Behaviour:__rebuild(body)\n"
"  self.body = body or self.body\n"
"  if type(self.body) == 'function' then\n"
"    OBJECT.__setcontext(self.__userdata)\n"
"    self:clear()\n"
"    self:body()\n"
"    if self.__erasebody then self.body = nil end\n"
"  elseif type(self.body) == 'string' then\n"
"    self:addChild(self.body)\n"
"  end\n"
"  return self\n"
"end\n"

"function Behaviour:rebuild(body)\n"
"  orca.async(self.__rebuild, self, body)\n"
"end\n"

"function Behaviour:loadImageAsync(url)\n"
"  orca.async(function (url)\n"
"    local network = require 'orca.network'\n"
"    self.Image = network.fetch(url):image()\n"
"  end, url)\n"
"end\n"

"function Behaviour:handleEvent(name, ...)\n"
"  if (not self[name] or not self[name](self, ...)) and self.parent then\n"
"    self.parent:handleEvent(name, ...)\n"
"  end\n"
"end\n"

"function Behaviour:loadView(filename, no_clear)\n"
"  if self.viewWillLoad then self:viewWillLoad(filename) end\n"
"  local ok, doc = pcall(require, filename)\n"
"  if ok then\n"
"    if not no_clear then self:clear() end\n"
"    self.view = doc()\n"
"    self:addChild(self.view, true)\n"
"    if self.viewDidLoad then self:viewDidLoad() end\n"
"    return self.view\n"
"  else\n"
"    io.stderr:write(string.format(\"%s: Can't load prefab\\n\", filename))\n"
"  end\n"
"end\n"

"function Behaviour:set(key, value)\n"
"  self[key] = value\n"
"end\n"

"function Behaviour:get(key)\n"
"  return self[key]\n"
"end\n"

"function Behaviour:async(...)\n"
"  orca.async(...) -- .error = function(error)\n"
"  --  self.error = error\n"
"  --  self:rebuild()\n"
"  -- end\n"
"end\n"

"function Behaviour:is(class)\n"
"  local cls = self\n"
"  while cls do\n"
"    if cls.__class == class or cls.__class.__name == class then\n"
"      return true\n"
"    end\n"
"    cls = getmetatable(cls)\n"
"  end\n"
"  return false\n"
"end\n"

/* extended functionality */

"function Behaviour:populateInputs()\n"
"  local tbl = {}\n"
"  for e in self.children do\n"
"    if e.className == 'Input' then\n"
"      tbl[e.Name] = e.Text\n"
"    end\n"
"  end\n"
"  return tbl\n"
"end\n"

"function Behaviour:findParentOfType(class)\n"
"  for n in self.lineage do\n"
"    if n:is(class) then return n end\n"
"  end\n"
"end\n"

"function Behaviour:setScrollTop(value)\n"
"  local offset = self.ContentOffset\n"
"  offset.y = math.min(0, self.ActualHeight - value)\n"
"  self.ContentOffset = offset\n"
"end\n"

"function Behaviour:extend(_base_0)\n"
"  local _parent_0 = self\n"
"  _base_0 = _base_0 or {}\n"
"  _base_0.__index = _base_0\n"
"  setmetatable(_base_0, _parent_0.__base)\n"
"  local _class_0 = setmetatable({\n"
"    __init = function(self_1, ...)\n"
"      return _parent_0.__init(self_1, ...)\n"
"    end,\n"
"    __base = _base_0,\n"
"    __name = 'SizedPlayer',\n"
"    __parent = _parent_0\n"
"  }, {\n"
"    __index = function(_, name)\n"
"      return rawget(_base_0, name) or _parent_0[name]\n"
"    end,\n"
"    __call = function(cls, ...)\n"
"      local _self_0 = setmetatable({}, _base_0)\n"
"      cls.__init(_self_0, ...)\n"
"      return _self_0\n"
"    end,\n"
"  })\n"
"  _base_0.__class = _class_0\n"
"  if _parent_0.__inherited then\n"
"    _parent_0.__inherited(_parent_0, _class_0)\n"
"  end\n"
"  return _class_0\n"
"end\n"

"local _base_0 = Behaviour\n"
"_base_0.__index = _base_0\n"
"local _class_0 = setmetatable({\n"
"  __init = function(self, ...)\n"
"    local _base_1 = getmetatable(self)\n"
"    \n"
"    _base_1.__index = function(_self_0, key)\n"
"      local ud = rawget(_self_0, '__userdata')\n"
"      local mt = getmetatable(_base_1) or {}\n"
"      local fn = OBJECT.__index\n"
"      local getp = OBJECT.__getproperty\n"
"      return rawget(_base_1, key) or mt[key] or (ud and (fn(_self_0, key) or getp(_self_0, key)))\n"
"            or (mt.__class and mt.__class[key])\n " // this is needed to access inherited classes (ui.Node2D)
"    end\n"
"    \n"
"    _base_1.__newindex = function(_self_0, key, value)\n"
"      local ud = rawget(_self_0, '__userdata')\n"
"      local set = OBJECT.__setproperty\n"
"      return ud and set(_self_0, key, value) or rawset(_self_0, key, value)\n"
"    end\n"

"    OBJECT.new(self, ...)\n"
"    self.print = print\n"

"    self:rebuild()\n"
"  end,\n"
"  __base = _base_0,\n"
"  __name = 'Behaviour'\n"
"}, {\n"
"  __index = function(cls, name)\n"
"    local ud = rawget(cls, '__userdata')\n"
"    return ud and ud[name] or rawget(_base_0, name)\n"
"  end,\n"
"  __call = function(cls, ...)\n"
"    local _self_0 = setmetatable({}, _base_0)\n"
"    cls.__init(_self_0, ...)\n"
"    return _self_0\n"
"  end\n"
"})\n"
"_base_0.__class = _class_0\n"
"return _class_0\n"

