// Generated by XSLT code generator
#include <include/api.h>
#include <core.h>

static int lua_Object_Clear(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object_Clear(self);
    return 0;
}

static int lua_Object_Release(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object_Release(self);
    return 0;
}

static int lua_Object_Awake(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object_Awake(self);
    return 0;
}

static int lua_Object_Animate(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object_Animate(self);
    return 0;
}

static int lua_Object_LoadPrefabs(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object_LoadPrefabs(self);
    return 0;
}

static int lua_Object_ProcesEvents(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object_ProcesEvents(self);
    return 0;
}

static int lua_Object_RemoveFromParent(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object_RemoveFromParent(self);
    return 0;
}

static int lua_Object_SetProperty(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    bool result = Object_SetProperty(self);
    lua_pushbool(L, result);
    return 1;
}

static int lua_Object_GetProperty(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    nresults result = Object_GetProperty(self);
    lua_pushnresults(L, result);
    return 1;
}

static int lua_Object_DispatchEvent(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object result = Object_DispatchEvent(self);
    lua_pushObject(L, result);
    return 1;
}

static int lua_Object_Bind(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object_Bind(self);
    return 0;
}

static int lua_Object_DoTween(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object_DoTween(self);
    return 0;
}

static int lua_Object_AddStyleSheet(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object_AddStyleSheet(self);
    return 0;
}

static int lua_Object_SetTimer(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    nresults result = Object_SetTimer(self);
    lua_pushnresults(L, result);
    return 1;
}

static int lua_Object_SetContext(lua_State *L) {
    Object_t* self = lua_toObject(L, 1);
    Object_SetContext(self);
    return 0;
}


ORCA_API int luaopen_orca_core(lua_State *L) {
    luaL_newlib(L, ((luaL_Reg[]) {
        { "GetFocus", lua_GetFocus },
        { "GetHover", lua_GetHover },
        { NULL, NULL }
    }));
    void on_core_module_registered(lua_State *L);
    on_core_module_registered(L);
    // Object
    luaopen_orca_Object(L);
    lua_setfield(L, -2, "Object");
    return 1;
}
