// Generated by codegen utility
#include <include/api.h>
#include <source/core/core.h>

void luaX_pushlocalization(lua_State *L, lpclocalization_t localization) {
	lua_pushlightuserdata(L, (lplocalization_t)localization);
}
lplocalization_t luaX_checklocalization(lua_State *L, int idx) {
	return lua_touserdata(L, idx);
}
void luaX_pushgame(lua_State *L, lpcgame_t game) {
	lua_pushlightuserdata(L, (lpgame_t)game);
}
lpgame_t luaX_checkgame(lua_State *L, int idx) {
	return lua_touserdata(L, idx);
}
lpObject_t luaX_checkObject(lua_State *L, int idx);
int f_new_Object(lua_State *L);
static int f_Object_clear(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_Clear(L, self);
	return 0;
}
static int f_Object___gc(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_Release(L, self);
	return 0;
}
static int f_Object___eq(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	lpcObject_t other = luaX_checkObject(L, 2);
	bool_t output = OBJ_Equals(self, other);
	lua_pushboolean(L, output);
	return 1;
}
static int f_Object_awake(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_Awake(L, self);
	return 0;
}
static int f_Object_animate(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_Animate(L, self);
	return 0;
}
static int f_Object_loadPrefabs(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_LoadPrefabs(L, self);
	return 0;
}
static int f_Object_emitPropertyChangedEvents(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_EmitPropertyChangedEvents(L, self);
	return 0;
}
static int f_Object_updateProperties(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_UpdateProperties(self);
	return 0;
}
static int f_Object_updateLayout(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	int32_t width = luaL_checknumber(L, 2);
	int32_t height = luaL_checknumber(L, 3);
	OBJ_UpdateLayout(self, width, height);
	return 0;
}
static int f_Object_addChild(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	lpObject_t child = luaX_checkObject(L, 2);
	bool_t is_template = lua_toboolean(L, 3);
	OBJ_AddChild(self, child, is_template);
	return 0;
}
static int f_Object_removeFromParent(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	bool_t dropModal = lua_toboolean(L, 2);
	OBJ_RemoveFromParent(L, self, dropModal);
	return 0;
}
static int f_Object___setproperty(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* Property = luaL_checkstring(L, 2);
	bool_t output = OBJ_SetProperty(L, self, Property);
	lua_pushboolean(L, output);
	return 1;
}
static int f_Object___getproperty(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* Property = luaL_checkstring(L, 2);
	return OBJ_GetProperty(L, self, Property);
}
static int f_Object_findChild(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* name = luaL_checkstring(L, 2);
	bool_t recursive = lua_toboolean(L, 3);
	lpObject_t output = OBJ_FindChild(self, name, recursive);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_dispatchEvent(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* event = luaL_checkstring(L, 2);
	lpObject_t output = OBJ_DispatchEvent(L, self, event);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_postMessage(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* message = luaL_checkstring(L, 2);
	OBJ_PostMessage(L, self, message);
	return 0;
}
static int f_Object_play(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* animation = luaL_checkstring(L, 2);
	OBJ_Play(self, animation);
	return 0;
}
static int f_Object_bind(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* Property = luaL_checkstring(L, 2);
	const char* expression = luaL_checkstring(L, 3);
	OBJ_Bind(L, self, Property, expression);
	return 0;
}
static int f_Object_setFocus(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_SetFocus(self);
	return 0;
}
static int f_Object_doTween(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_DoTween(L, self);
	return 0;
}
static int f_Object_addStyleSheet(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* source = luaL_checkstring(L, 2);
	OBJ_AddStyleSheet(L, self, source);
	return 0;
}
static int f_Object_setTimer(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	return OBJ_SetTimer(L, self);
}
static int f_Object___setcontext(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_SetContext(L, self);
	return 0;
}
static int f_Object_getName(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	const char* output = OBJ_GetName(self);
	lua_pushstring(L, output);
	return 1;
}
static int f_Object_setName(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* name = luaL_checkstring(L, 2);
	OBJ_SetName(self, name);
	return 0;
}
static int f_Object_getClassName(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	const char* output = OBJ_GetClassName(self);
	lua_pushstring(L, output);
	return 1;
}
static int f_Object_checkName(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	const char* name = luaL_checkstring(L, 2);
	bool_t output = OBJ_CheckName(self, name);
	lua_pushboolean(L, output);
	return 1;
}
static int f_Object_findByPath(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* name = luaL_checkstring(L, 2);
	lpObject_t output = OBJ_FindByPath(self, name);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_getStyle(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	uint32_t output = OBJ_GetStyle(self);
	lua_pushnumber(L, output);
	return 1;
}
static int f_Object_setStyle(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	uint32_t style = luaL_checknumber(L, 2);
	OBJ_SetStyle(self, style);
	return 0;
}
static int f_Object_findCallbackForID(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	uint32_t event = luaL_checknumber(L, 2);
	const char* output = OBJ_FindCallbackForID(self, event);
	lua_pushstring(L, output);
	return 1;
}
static int f_Object_applyStyles(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	bool_t recursive = lua_toboolean(L, 2);
	OBJ_ApplyStyles(self, recursive);
	return 0;
}
static int f_Object_setDirty(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_SetDirty(self);
	return 0;
}
static int f_Object_getParent(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	lpObject_t output = OBJ_GetParent(self);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_getFirstChild(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	lpObject_t output = OBJ_GetFirstChild(self);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_getNext(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	lpObject_t output = OBJ_GetNext(self);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_getRoot(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	lpObject_t output = OBJ_GetRoot(self);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_findChildByID(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	uint32_t id = luaL_checknumber(L, 2);
	lpObject_t output = OBJ_FindChildByID(self, id);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_findChildByAlias(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	uint32_t id = luaL_checknumber(L, 2);
	lpObject_t output = OBJ_FindChildByAlias(self, id);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_getSourceFile(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	const char* output = OBJ_GetSourceFile(self);
	lua_pushstring(L, output);
	return 1;
}
static int f_Object_getTextContent(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	const char* output = OBJ_GetTextContent(self);
	lua_pushstring(L, output);
	return 1;
}
static int f_Object_getTimestamp(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	long output = OBJ_GetTimestamp(self);
	lua_pushinteger(L, output);
	return 1;
}
static int f_Object_getAlias(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	uint32_t output = OBJ_GetAlias(self);
	lua_pushnumber(L, output);
	return 1;
}
static int f_Object_getFlags(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	uint32_t output = OBJ_GetFlags(self);
	lua_pushnumber(L, output);
	return 1;
}
static int f_Object_setFlags(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	uint32_t flags = luaL_checknumber(L, 2);
	OBJ_SetFlags(self, flags);
	return 0;
}
static int f_Object_getIdentifier(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	uint32_t output = OBJ_GetIdentifier(self);
	lua_pushnumber(L, output);
	return 1;
}
static int f_Object_getModal(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	lpObject_t output = OBJ_GetModal(self);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_setModal(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	lpObject_t modal = luaX_checkObject(L, 2);
	OBJ_SetModal(self, modal);
	return 0;
}
static int f_Object_isFocused(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	bool_t output = OBJ_IsFocused(self);
	lua_pushboolean(L, output);
	return 1;
}
static int f_Object_setHover(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_SetHover(self);
	return 0;
}
static int f_Object_setTextContent(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* text = luaL_checkstring(L, 2);
	OBJ_SetTextContent(self, text);
	return 0;
}
static int f_Object_setSourceFile(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* path = luaL_checkstring(L, 2);
	OBJ_SetSourceFile(self, path);
	return 0;
}
static int f_Object_setClassName(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* classID = luaL_checkstring(L, 2);
	OBJ_SetClassName(self, classID);
	return 0;
}
static int f_Object_findParentOfClass(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	uint32_t classID = luaL_checknumber(L, 2);
	lpObject_t output = OBJ_FindParentOfClass(self, classID);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_findChildOfClass(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	uint32_t classID = luaL_checknumber(L, 2);
	lpObject_t output = OBJ_FindChildOfClass(self, classID);
	luaX_pushObject(L, output);
	return 1;
}
static int f_Object_isPrefabView(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	bool_t output = OBJ_IsPrefabView(self);
	lua_pushboolean(L, output);
	return 1;
}
static int f_Object_addAlias(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* name = luaL_checkstring(L, 2);
	const char* path = luaL_checkstring(L, 3);
	OBJ_AddAlias(self, name, path);
	return 0;
}
static int f_Object_assignAliases(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* pathToObject = luaL_checkstring(L, 2);
	OBJ_AssignAliases(self, pathToObject);
	return 0;
}
static int f_Object_parseClassAttribute(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* classString = luaL_checkstring(L, 2);
	OBJ_ParseClassAttribute(self, classString);
	return 0;
}
static int f_Object_setAnimation(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* name = luaL_checkstring(L, 2);
	OBJ_SetAnimation(self, name);
	return 0;
}
static int f_Object_getAnimation(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	lpcKeyframeAnim_t output = OBJ_GetAnimation(self);
	luaX_pushKeyframeAnim(L, output);
	return 1;
}
static int f_Object_addAnimation(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	lpKeyframeAnim_t animation = luaX_checkKeyframeAnim(L, 2);
	OBJ_AddAnimation(self, animation);
	return 0;
}
static int f_Object_getInteger(lua_State *L) {
	lpcObject_t self = luaX_checkObject(L, 1);
	uint32_t ident = luaL_checknumber(L, 2);
	int32_t fallback = luaL_checknumber(L, 3);
	int32_t output = OBJ_GetInteger(self, ident, fallback);
	lua_pushnumber(L, output);
	return 1;
}
static int f_Object_findImplicitProperty(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* name = luaL_checkstring(L, 2);
	lpPropertyType_t output = OBJ_FindImplicitProperty(self, name);
	luaX_pushPropertyType(L, output);
	return 1;
}
static int f_Object_findPropertyByPath(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	const char* path = luaL_checkstring(L, 2);
	lpProperty_t output = OBJ_FindPropertyByPath(self, path);
	luaX_pushProperty(L, output);
	return 1;
}
static int f_Object_rebuild(lua_State *L) {
	lpObject_t self = luaX_checkObject(L, 1);
	OBJ_Rebuild(L, self);
	return 0;
}
int f_Object___index(lua_State *L) {
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	case 0x5c6e1222: // clear
		lua_pushcfunction(L, f_Object_clear);
		return 1;
	case 0xd71034dc: // awake
		lua_pushcfunction(L, f_Object_awake);
		return 1;
	case 0xe79c66b0: // animate
		lua_pushcfunction(L, f_Object_animate);
		return 1;
	case 0xd43670bc: // loadPrefabs
		lua_pushcfunction(L, f_Object_loadPrefabs);
		return 1;
	case 0xaac1a1fc: // emitPropertyChangedEvents
		lua_pushcfunction(L, f_Object_emitPropertyChangedEvents);
		return 1;
	case 0x8aef52d9: // updateProperties
		lua_pushcfunction(L, f_Object_updateProperties);
		return 1;
	case 0x37fc391a: // updateLayout
		lua_pushcfunction(L, f_Object_updateLayout);
		return 1;
	case 0x14e0dba2: // addChild
		lua_pushcfunction(L, f_Object_addChild);
		return 1;
	case 0x90d2bfd5: // removeFromParent
		lua_pushcfunction(L, f_Object_removeFromParent);
		return 1;
	case 0x95c0f780: // findChild
		lua_pushcfunction(L, f_Object_findChild);
		return 1;
	case 0x46310439: // dispatchEvent
		lua_pushcfunction(L, f_Object_dispatchEvent);
		return 1;
	case 0x2a7c8ec6: // postMessage
		lua_pushcfunction(L, f_Object_postMessage);
		return 1;
	case 0xc2cbd863: // play
		lua_pushcfunction(L, f_Object_play);
		return 1;
	case 0xc7535f2e: // bind
		lua_pushcfunction(L, f_Object_bind);
		return 1;
	case 0x417e6e85: // setFocus
		lua_pushcfunction(L, f_Object_setFocus);
		return 1;
	case 0x67e26693: // doTween
		lua_pushcfunction(L, f_Object_doTween);
		return 1;
	case 0x913ef93c: // addStyleSheet
		lua_pushcfunction(L, f_Object_addStyleSheet);
		return 1;
	case 0x874125d8: // setTimer
		lua_pushcfunction(L, f_Object_setTimer);
		return 1;
	case 0x1f1b2f34: // getName
		lua_pushcfunction(L, f_Object_getName);
		return 1;
	case 0xbac20468: // setName
		lua_pushcfunction(L, f_Object_setName);
		return 1;
	case 0xcb556952: // getClassName
		lua_pushcfunction(L, f_Object_getClassName);
		return 1;
	case 0xbfdb0d64: // checkName
		lua_pushcfunction(L, f_Object_checkName);
		return 1;
	case 0xccee3724: // findByPath
		lua_pushcfunction(L, f_Object_findByPath);
		return 1;
	case 0x871aec88: // getStyle
		lua_pushcfunction(L, f_Object_getStyle);
		return 1;
	case 0x08819dd4: // setStyle
		lua_pushcfunction(L, f_Object_setStyle);
		return 1;
	case 0xd2bdfc55: // findCallbackForID
		lua_pushcfunction(L, f_Object_findCallbackForID);
		return 1;
	case 0xc431c97d: // applyStyles
		lua_pushcfunction(L, f_Object_applyStyles);
		return 1;
	case 0xd93fb1e1: // setDirty
		lua_pushcfunction(L, f_Object_setDirty);
		return 1;
	case 0xc98e64d7: // getParent
		lua_pushcfunction(L, f_Object_getParent);
		return 1;
	case 0x2f984b2b: // getFirstChild
		lua_pushcfunction(L, f_Object_getFirstChild);
		return 1;
	case 0xb6d23e36: // getNext
		lua_pushcfunction(L, f_Object_getNext);
		return 1;
	case 0x9184f6db: // getRoot
		lua_pushcfunction(L, f_Object_getRoot);
		return 1;
	case 0x17702518: // findChildByID
		lua_pushcfunction(L, f_Object_findChildByID);
		return 1;
	case 0xc2b337cf: // findChildByAlias
		lua_pushcfunction(L, f_Object_findChildByAlias);
		return 1;
	case 0x97139044: // getSourceFile
		lua_pushcfunction(L, f_Object_getSourceFile);
		return 1;
	case 0xc768d4f5: // getTextContent
		lua_pushcfunction(L, f_Object_getTextContent);
		return 1;
	case 0xbdbd90e5: // getTimestamp
		lua_pushcfunction(L, f_Object_getTimestamp);
		return 1;
	case 0x8bb4da01: // getAlias
		lua_pushcfunction(L, f_Object_getAlias);
		return 1;
	case 0x9d1d3b0e: // getFlags
		lua_pushcfunction(L, f_Object_getFlags);
		return 1;
	case 0x40443eda: // setFlags
		lua_pushcfunction(L, f_Object_setFlags);
		return 1;
	case 0xda6c15fc: // getIdentifier
		lua_pushcfunction(L, f_Object_getIdentifier);
		return 1;
	case 0x02e6a110: // getModal
		lua_pushcfunction(L, f_Object_getModal);
		return 1;
	case 0xeb276564: // setModal
		lua_pushcfunction(L, f_Object_setModal);
		return 1;
	case 0xc86983e2: // isFocused
		lua_pushcfunction(L, f_Object_isFocused);
		return 1;
	case 0x37b88e13: // setHover
		lua_pushcfunction(L, f_Object_setHover);
		return 1;
	case 0xfb656971: // setTextContent
		lua_pushcfunction(L, f_Object_setTextContent);
		return 1;
	case 0x337ee4d0: // setSourceFile
		lua_pushcfunction(L, f_Object_setSourceFile);
		return 1;
	case 0x72d988f6: // setClassName
		lua_pushcfunction(L, f_Object_setClassName);
		return 1;
	case 0xfa1508f5: // findParentOfClass
		lua_pushcfunction(L, f_Object_findParentOfClass);
		return 1;
	case 0x23386cab: // findChildOfClass
		lua_pushcfunction(L, f_Object_findChildOfClass);
		return 1;
	case 0x57a31c36: // isPrefabView
		lua_pushcfunction(L, f_Object_isPrefabView);
		return 1;
	case 0xf53c8710: // addAlias
		lua_pushcfunction(L, f_Object_addAlias);
		return 1;
	case 0xcf2ffd7c: // assignAliases
		lua_pushcfunction(L, f_Object_assignAliases);
		return 1;
	case 0xef604934: // parseClassAttribute
		lua_pushcfunction(L, f_Object_parseClassAttribute);
		return 1;
	case 0x2d3d15fb: // setAnimation
		lua_pushcfunction(L, f_Object_setAnimation);
		return 1;
	case 0x8b9c8f7f: // getAnimation
		lua_pushcfunction(L, f_Object_getAnimation);
		return 1;
	case 0xbb6beb62: // addAnimation
		lua_pushcfunction(L, f_Object_addAnimation);
		return 1;
	case 0xafe50917: // getInteger
		lua_pushcfunction(L, f_Object_getInteger);
		return 1;
	case 0xf2167b80: // findImplicitProperty
		lua_pushcfunction(L, f_Object_findImplicitProperty);
		return 1;
	case 0xfc8bdeb9: // findPropertyByPath
		lua_pushcfunction(L, f_Object_findPropertyByPath);
		return 1;
	case 0x7e809e90: // rebuild
		lua_pushcfunction(L, f_Object_rebuild);
		return 1;
	}
	return 0;
}
int luaopen_orca_Object(lua_State *L) {
	luaL_newmetatable(L, "Object");
	luaL_setfuncs(L, ((luaL_Reg[]) {
		{ "new", f_new_Object },
		{ "__index", f_Object___index },
		{ "__gc", f_Object___gc },
		{ "__eq", f_Object___eq },
		{ "__setproperty", f_Object___setproperty },
		{ "__getproperty", f_Object___getproperty },
		{ "__setcontext", f_Object___setcontext },
		{ NULL, NULL },
	}), 0);
	return 1;
}
static int f_core_getFocus(lua_State *L) {
	lpObject_t output = core_GetFocus();
	luaX_pushObject(L, output);
	return 1;
}
static int f_core_getHover(lua_State *L) {
	lpObject_t output = core_GetHover();
	luaX_pushObject(L, output);
	return 1;
}
static const char *_DataType[] = {"none","bool","int","enum","float","fixed","longstring","edges","objecttags","event","struct","object","group",NULL};
eDataType_t luaX_checkDataType(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _DataType);
}
void luaX_pushDataType(lua_State *L, eDataType_t value) {
	assert(value >= 0 && value < 13);
	lua_pushstring(L, _DataType[value]);
}
#include <libxml/parser.h>
ORCA_API lpcString_t __strtoDataType(lpcString_t string, enum DataType* output) {
	if (string == NULL) return FALSE;
	const char* _DataType[] = { "None", "Bool", "Int", "Enum", "Float", "Fixed", "LongString", "Edges", "ObjectTags", "Event", "Struct", "Object", "Group", NULL };
	if (isdigit(*string)) {
		*output = strtod(string, (char**)&string);
		return string;
	} else for (const char **s = _DataType; *s; s++) {
		if (!strcmp(string, *s)) {
			*output = (enum DataType)(s - _DataType);
			return string + strlen(*s);
		}
	}
	Con_Error("Could not parse '%s' value of property DataType", string);
	return string + strlen(string);
}
void luaX_pushPropertyEnumValue(lua_State *L, lpcPropertyEnumValue_t data) {
	lpPropertyEnumValue_t self = lua_newuserdata(L, sizeof(struct PropertyEnumValue));
	luaL_setmetatable(L, "PropertyEnumValue");
	memcpy(self, data, sizeof(struct PropertyEnumValue));
}
lpPropertyEnumValue_t luaX_checkPropertyEnumValue(lua_State *L, int idx) {
	return luaL_checkudata(L, idx, "PropertyEnumValue");
}
static int f_new_PropertyEnumValue(lua_State *L) {
	lpPropertyEnumValue_t self = lua_newuserdata(L, sizeof(struct PropertyEnumValue));
	luaL_setmetatable(L, "PropertyEnumValue");
	memset(self, 0, sizeof(struct PropertyEnumValue));
	if (lua_istable(L, 1)) {
		lua_getfield(L, 1, "Name");
		strncpy(self->Name, luaL_optstring(L, -1, ""), sizeof(self->Name));
		lua_pop(L, 1);
		lua_getfield(L, 1, "Value");
		self->Value = lua_tonumber(L, -1);
		lua_pop(L, 1);
	} else {
		strncpy(self->Name, luaL_checkstring(L, 1), sizeof(self->Name));
		self->Value = luaL_checknumber(L, 2);
	}
	return 1;
}
static int f_PropertyEnumValue___call(lua_State *L) {
	lua_remove(L, 1); // remove PropertyEnumValue from stack
	return f_new_PropertyEnumValue(L);
}
int f_PropertyEnumValue___index(lua_State *L) {
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	case 0x0fe07306: // Name
		lua_pushstring(L, luaX_checkPropertyEnumValue(L, 1)->Name);
		return 1;
	case 0xd147f96a: // Value
		lua_pushnumber(L, luaX_checkPropertyEnumValue(L, 1)->Value);
		return 1;
	}
	return luaL_error(L, "Unknown field in PropertyEnumValue: %s", luaL_checkstring(L, 2));
}
int f_PropertyEnumValue___newindex(lua_State *L) {
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	case 0x0fe07306: // Name
		strncpy(luaX_checkPropertyEnumValue(L, 1)->Name, luaL_checkstring(L, 3), sizeof(luaX_checkPropertyEnumValue(L, 1)->Name));
		return 0;
	case 0xd147f96a: // Value
		luaX_checkPropertyEnumValue(L, 1)->Value = luaL_checknumber(L, 3);
		return 0;
	}
	return luaL_error(L, "Unknown field in PropertyEnumValue: %s", luaL_checkstring(L, 2));
}
#include <libxml/parser.h>
ORCA_API lpcString_t __strtoPropertyEnumValue(lpcString_t str, lpPropertyEnumValue_t output) {
	lpcString_t __strtofixed(lpcString_t, fixedString_t*);
	lpcString_t __strtoint(lpcString_t, int32_t*);
	str = __strtofixed(str, &output->Name);
	str = __strtoint(str, &output->Value);
	return str;
}
static int xml_PropertyEnumValue(xmlNodePtr xml, lpPropertyEnumValue_t output) {
	lpcString_t __strtofixed(lpcString_t, fixedString_t*);
	lpcString_t __strtoint(lpcString_t, int32_t*);
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("Name")), xmlFree) {
		__strtofixed((lpcString_t)attr, &output->Name);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("Value")), xmlFree) {
		__strtoint((lpcString_t)attr, &output->Value);
	}
	return TRUE;
}

int luaopen_orca_PropertyEnumValue(lua_State *L) {
	luaL_newmetatable(L, "PropertyEnumValue");
	luaL_setfuncs(L, ((luaL_Reg[]) {
		{ "new", f_new_PropertyEnumValue },
		{ "__newindex", f_PropertyEnumValue___newindex },
		{ "__index", f_PropertyEnumValue___index },
		{ NULL, NULL },
	}), 0);
	lua_newtable(L);
	lua_pushcfunction(L, f_PropertyEnumValue___call);
	lua_setfield(L, -2, "__call");
	lua_setmetatable(L, -2);
	lua_pushlightuserdata(L, xml_PropertyEnumValue);
	lua_setfield(L, LUA_REGISTRYINDEX, "PropertyEnumValueParser");
	return 1;
}
void luaX_pushPropertyType(lua_State *L, lpcPropertyType_t data) {
	lpPropertyType_t self = lua_newuserdata(L, sizeof(struct PropertyType));
	luaL_setmetatable(L, "PropertyType");
	memcpy(self, data, sizeof(struct PropertyType));
}
lpPropertyType_t luaX_checkPropertyType(lua_State *L, int idx) {
	return luaL_checkudata(L, idx, "PropertyType");
}
static int f_new_PropertyType(lua_State *L) {
	lpPropertyType_t self = lua_newuserdata(L, sizeof(struct PropertyType));
	luaL_setmetatable(L, "PropertyType");
	memset(self, 0, sizeof(struct PropertyType));
	if (lua_istable(L, 1)) {
		lua_getfield(L, 1, "Name");
		strncpy(self->Name, luaL_optstring(L, -1, ""), sizeof(self->Name));
		lua_pop(L, 1);
		lua_getfield(L, 1, "Category");
		strncpy(self->Category, luaL_optstring(L, -1, ""), sizeof(self->Category));
		lua_pop(L, 1);
		lua_getfield(L, 1, "DataType");
		if (!lua_isnil(L, -1)) self->DataType = luaX_checkDataType(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "DefaultValue");
		strncpy(self->DefaultValue, luaL_optstring(L, -1, ""), sizeof(self->DefaultValue));
		lua_pop(L, 1);
		lua_getfield(L, 1, "TargetType");
		strncpy(self->TargetType, luaL_optstring(L, -1, ""), sizeof(self->TargetType));
		lua_pop(L, 1);
		lua_getfield(L, 1, "AffectLayout");
		self->AffectLayout = lua_toboolean(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "AffectRender");
		self->AffectRender = lua_toboolean(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "IsReadOnly");
		self->IsReadOnly = lua_toboolean(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "IsHidden");
		self->IsHidden = lua_toboolean(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "IsInherited");
		self->IsInherited = lua_toboolean(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "Key");
		strncpy(self->Key, luaL_optstring(L, -1, ""), sizeof(self->Key));
		lua_pop(L, 1);
		lua_getfield(L, 1, "Value");
		strncpy(self->Value, luaL_optstring(L, -1, ""), sizeof(self->Value));
		lua_pop(L, 1);
		lua_getfield(L, 1, "Step");
		self->Step = lua_tonumber(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "UpperBound");
		self->UpperBound = lua_tonumber(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "LowerBound");
		self->LowerBound = lua_tonumber(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "ShortIdentifier");
		self->ShortIdentifier = lua_tonumber(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "FullIdentifier");
		self->FullIdentifier = lua_tonumber(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "Offset");
		self->Offset = lua_tonumber(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "DataSize");
		self->DataSize = lua_tonumber(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "TypeString");
		strncpy(self->TypeString, luaL_optstring(L, -1, ""), sizeof(self->TypeString));
		lua_pop(L, 1);
		lua_getfield(L, 1, "NumComponents");
		self->NumComponents = lua_tonumber(L, -1);
		lua_pop(L, 1);
		lua_getfield(L, 1, "IsArray");
		self->IsArray = lua_toboolean(L, -1);
		lua_pop(L, 1);
	} else {
		strncpy(self->Name, luaL_checkstring(L, 1), sizeof(self->Name));
		strncpy(self->Category, luaL_checkstring(L, 2), sizeof(self->Category));
		self->DataType = luaX_checkDataType(L, 3);
		strncpy(self->DefaultValue, luaL_checkstring(L, 4), sizeof(self->DefaultValue));
		strncpy(self->TargetType, luaL_checkstring(L, 5), sizeof(self->TargetType));
		self->AffectLayout = lua_toboolean(L, 6);
		self->AffectRender = lua_toboolean(L, 7);
		self->IsReadOnly = lua_toboolean(L, 8);
		self->IsHidden = lua_toboolean(L, 9);
		self->IsInherited = lua_toboolean(L, 10);
		strncpy(self->Key, luaL_checkstring(L, 11), sizeof(self->Key));
		strncpy(self->Value, luaL_checkstring(L, 12), sizeof(self->Value));
		self->Step = luaL_checknumber(L, 13);
		self->UpperBound = luaL_checknumber(L, 14);
		self->LowerBound = luaL_checknumber(L, 15);
		self->ShortIdentifier = luaL_checknumber(L, 16);
		self->FullIdentifier = luaL_checknumber(L, 17);
		self->Offset = luaL_checknumber(L, 18);
		self->DataSize = luaL_checknumber(L, 19);
		strncpy(self->TypeString, luaL_checkstring(L, 20), sizeof(self->TypeString));
		self->NumComponents = luaL_checknumber(L, 21);
		self->IsArray = lua_toboolean(L, 22);
	}
	return 1;
}
static int f_PropertyType___call(lua_State *L) {
	lua_remove(L, 1); // remove PropertyType from stack
	return f_new_PropertyType(L);
}
int f_PropertyType___index(lua_State *L) {
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	case 0x0fe07306: // Name
		lua_pushstring(L, luaX_checkPropertyType(L, 1)->Name);
		return 1;
	case 0xafb3e591: // Category
		lua_pushstring(L, luaX_checkPropertyType(L, 1)->Category);
		return 1;
	case 0x840d6c6d: // DataType
		luaX_pushDataType(L, luaX_checkPropertyType(L, 1)->DataType);
		return 1;
	case 0xcd093f9f: // DefaultValue
		lua_pushstring(L, luaX_checkPropertyType(L, 1)->DefaultValue);
		return 1;
	case 0x77ada720: // TargetType
		lua_pushstring(L, luaX_checkPropertyType(L, 1)->TargetType);
		return 1;
	case 0xd2d3694e: // AffectLayout
		lua_pushboolean(L, luaX_checkPropertyType(L, 1)->AffectLayout);
		return 1;
	case 0xcae7b378: // AffectRender
		lua_pushboolean(L, luaX_checkPropertyType(L, 1)->AffectRender);
		return 1;
	case 0xd9ee91e7: // IsReadOnly
		lua_pushboolean(L, luaX_checkPropertyType(L, 1)->IsReadOnly);
		return 1;
	case 0x3bf0d5c9: // IsHidden
		lua_pushboolean(L, luaX_checkPropertyType(L, 1)->IsHidden);
		return 1;
	case 0x26e59151: // IsInherited
		lua_pushboolean(L, luaX_checkPropertyType(L, 1)->IsInherited);
		return 1;
	case 0xcd1ac90c: // Key
		lua_pushstring(L, luaX_checkPropertyType(L, 1)->Key);
		return 1;
	case 0xd147f96a: // Value
		lua_pushstring(L, luaX_checkPropertyType(L, 1)->Value);
		return 1;
	case 0x4771f92f: // Step
		lua_pushnumber(L, luaX_checkPropertyType(L, 1)->Step);
		return 1;
	case 0x48b88645: // UpperBound
		lua_pushnumber(L, luaX_checkPropertyType(L, 1)->UpperBound);
		return 1;
	case 0xccc57b3a: // LowerBound
		lua_pushnumber(L, luaX_checkPropertyType(L, 1)->LowerBound);
		return 1;
	case 0x0f76864e: // ShortIdentifier
		lua_pushnumber(L, luaX_checkPropertyType(L, 1)->ShortIdentifier);
		return 1;
	case 0x429417cf: // FullIdentifier
		lua_pushnumber(L, luaX_checkPropertyType(L, 1)->FullIdentifier);
		return 1;
	case 0x8995c7ea: // Offset
		lua_pushnumber(L, luaX_checkPropertyType(L, 1)->Offset);
		return 1;
	case 0x58ff2a7c: // DataSize
		lua_pushnumber(L, luaX_checkPropertyType(L, 1)->DataSize);
		return 1;
	case 0xdf6c0780: // TypeString
		lua_pushstring(L, luaX_checkPropertyType(L, 1)->TypeString);
		return 1;
	case 0xc3c2d1e7: // NumComponents
		lua_pushnumber(L, luaX_checkPropertyType(L, 1)->NumComponents);
		return 1;
	case 0x660880b6: // IsArray
		lua_pushboolean(L, luaX_checkPropertyType(L, 1)->IsArray);
		return 1;
	}
	return luaL_error(L, "Unknown field in PropertyType: %s", luaL_checkstring(L, 2));
}
int f_PropertyType___newindex(lua_State *L) {
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	case 0x0fe07306: // Name
		strncpy(luaX_checkPropertyType(L, 1)->Name, luaL_checkstring(L, 3), sizeof(luaX_checkPropertyType(L, 1)->Name));
		return 0;
	case 0xafb3e591: // Category
		strncpy(luaX_checkPropertyType(L, 1)->Category, luaL_checkstring(L, 3), sizeof(luaX_checkPropertyType(L, 1)->Category));
		return 0;
	case 0x840d6c6d: // DataType
		luaX_checkPropertyType(L, 1)->DataType = luaX_checkDataType(L, 3);
		return 0;
	case 0xcd093f9f: // DefaultValue
		strncpy(luaX_checkPropertyType(L, 1)->DefaultValue, luaL_checkstring(L, 3), sizeof(luaX_checkPropertyType(L, 1)->DefaultValue));
		return 0;
	case 0x77ada720: // TargetType
		strncpy(luaX_checkPropertyType(L, 1)->TargetType, luaL_checkstring(L, 3), sizeof(luaX_checkPropertyType(L, 1)->TargetType));
		return 0;
	case 0xd2d3694e: // AffectLayout
		luaX_checkPropertyType(L, 1)->AffectLayout = lua_toboolean(L, 3);
		return 0;
	case 0xcae7b378: // AffectRender
		luaX_checkPropertyType(L, 1)->AffectRender = lua_toboolean(L, 3);
		return 0;
	case 0xd9ee91e7: // IsReadOnly
		luaX_checkPropertyType(L, 1)->IsReadOnly = lua_toboolean(L, 3);
		return 0;
	case 0x3bf0d5c9: // IsHidden
		luaX_checkPropertyType(L, 1)->IsHidden = lua_toboolean(L, 3);
		return 0;
	case 0x26e59151: // IsInherited
		luaX_checkPropertyType(L, 1)->IsInherited = lua_toboolean(L, 3);
		return 0;
	case 0xcd1ac90c: // Key
		strncpy(luaX_checkPropertyType(L, 1)->Key, luaL_checkstring(L, 3), sizeof(luaX_checkPropertyType(L, 1)->Key));
		return 0;
	case 0xd147f96a: // Value
		strncpy(luaX_checkPropertyType(L, 1)->Value, luaL_checkstring(L, 3), sizeof(luaX_checkPropertyType(L, 1)->Value));
		return 0;
	case 0x4771f92f: // Step
		luaX_checkPropertyType(L, 1)->Step = luaL_checknumber(L, 3);
		return 0;
	case 0x48b88645: // UpperBound
		luaX_checkPropertyType(L, 1)->UpperBound = luaL_checknumber(L, 3);
		return 0;
	case 0xccc57b3a: // LowerBound
		luaX_checkPropertyType(L, 1)->LowerBound = luaL_checknumber(L, 3);
		return 0;
	case 0x0f76864e: // ShortIdentifier
		luaX_checkPropertyType(L, 1)->ShortIdentifier = luaL_checknumber(L, 3);
		return 0;
	case 0x429417cf: // FullIdentifier
		luaX_checkPropertyType(L, 1)->FullIdentifier = luaL_checknumber(L, 3);
		return 0;
	case 0x8995c7ea: // Offset
		luaX_checkPropertyType(L, 1)->Offset = luaL_checknumber(L, 3);
		return 0;
	case 0x58ff2a7c: // DataSize
		luaX_checkPropertyType(L, 1)->DataSize = luaL_checknumber(L, 3);
		return 0;
	case 0xdf6c0780: // TypeString
		strncpy(luaX_checkPropertyType(L, 1)->TypeString, luaL_checkstring(L, 3), sizeof(luaX_checkPropertyType(L, 1)->TypeString));
		return 0;
	case 0xc3c2d1e7: // NumComponents
		luaX_checkPropertyType(L, 1)->NumComponents = luaL_checknumber(L, 3);
		return 0;
	case 0x660880b6: // IsArray
		luaX_checkPropertyType(L, 1)->IsArray = lua_toboolean(L, 3);
		return 0;
	}
	return luaL_error(L, "Unknown field in PropertyType: %s", luaL_checkstring(L, 2));
}
#include <libxml/parser.h>
ORCA_API lpcString_t __strtoPropertyType(lpcString_t str, lpPropertyType_t output) {
	lpcString_t __strtoDataType(lpcString_t, enum DataType*);
	lpcString_t __strtobool(lpcString_t, bool_t*);
	lpcString_t __strtofixed(lpcString_t, fixedString_t*);
	lpcString_t __strtofloat(lpcString_t, float*);
	lpcString_t __strtouint(lpcString_t, uint32_t*);
	str = __strtofixed(str, &output->Name);
	str = __strtofixed(str, &output->Category);
	str = __strtoDataType(str, &output->DataType);
	str = __strtofixed(str, &output->DefaultValue);
	str = __strtofixed(str, &output->TargetType);
	str = __strtobool(str, &output->AffectLayout);
	str = __strtobool(str, &output->AffectRender);
	str = __strtobool(str, &output->IsReadOnly);
	str = __strtobool(str, &output->IsHidden);
	str = __strtobool(str, &output->IsInherited);
	str = __strtofixed(str, &output->Key);
	str = __strtofixed(str, &output->Value);
	str = __strtofloat(str, &output->Step);
	str = __strtofloat(str, &output->UpperBound);
	str = __strtofloat(str, &output->LowerBound);
	str = __strtouint(str, &output->ShortIdentifier);
	str = __strtouint(str, &output->FullIdentifier);
	str = __strtouint(str, &output->Offset);
	str = __strtouint(str, &output->DataSize);
	str = __strtofixed(str, &output->TypeString);
	str = __strtouint(str, &output->NumComponents);
	str = __strtobool(str, &output->IsArray);
	return str;
}
static int xml_PropertyType(xmlNodePtr xml, lpPropertyType_t output) {
	lpcString_t __strtoDataType(lpcString_t, enum DataType*);
	lpcString_t __strtobool(lpcString_t, bool_t*);
	lpcString_t __strtofixed(lpcString_t, fixedString_t*);
	lpcString_t __strtofloat(lpcString_t, float*);
	lpcString_t __strtouint(lpcString_t, uint32_t*);
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("Name")), xmlFree) {
		__strtofixed((lpcString_t)attr, &output->Name);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("Category")), xmlFree) {
		__strtofixed((lpcString_t)attr, &output->Category);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("DataType")), xmlFree) {
		__strtoDataType((lpcString_t)attr, &output->DataType);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("DefaultValue")), xmlFree) {
		__strtofixed((lpcString_t)attr, &output->DefaultValue);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("TargetType")), xmlFree) {
		__strtofixed((lpcString_t)attr, &output->TargetType);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("AffectLayout")), xmlFree) {
		__strtobool((lpcString_t)attr, &output->AffectLayout);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("AffectRender")), xmlFree) {
		__strtobool((lpcString_t)attr, &output->AffectRender);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("IsReadOnly")), xmlFree) {
		__strtobool((lpcString_t)attr, &output->IsReadOnly);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("IsHidden")), xmlFree) {
		__strtobool((lpcString_t)attr, &output->IsHidden);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("IsInherited")), xmlFree) {
		__strtobool((lpcString_t)attr, &output->IsInherited);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("Key")), xmlFree) {
		__strtofixed((lpcString_t)attr, &output->Key);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("Value")), xmlFree) {
		__strtofixed((lpcString_t)attr, &output->Value);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("Step")), xmlFree) {
		__strtofloat((lpcString_t)attr, &output->Step);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("UpperBound")), xmlFree) {
		__strtofloat((lpcString_t)attr, &output->UpperBound);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("LowerBound")), xmlFree) {
		__strtofloat((lpcString_t)attr, &output->LowerBound);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("ShortIdentifier")), xmlFree) {
		__strtouint((lpcString_t)attr, &output->ShortIdentifier);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("FullIdentifier")), xmlFree) {
		__strtouint((lpcString_t)attr, &output->FullIdentifier);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("Offset")), xmlFree) {
		__strtouint((lpcString_t)attr, &output->Offset);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("DataSize")), xmlFree) {
		__strtouint((lpcString_t)attr, &output->DataSize);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("TypeString")), xmlFree) {
		__strtofixed((lpcString_t)attr, &output->TypeString);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("NumComponents")), xmlFree) {
		__strtouint((lpcString_t)attr, &output->NumComponents);
	}
	xmlWith(xmlChar, attr, xmlGetProp(xml, XMLSTR("IsArray")), xmlFree) {
		__strtobool((lpcString_t)attr, &output->IsArray);
	}
	return TRUE;
}

int luaopen_orca_PropertyType(lua_State *L) {
	luaL_newmetatable(L, "PropertyType");
	luaL_setfuncs(L, ((luaL_Reg[]) {
		{ "new", f_new_PropertyType },
		{ "__newindex", f_PropertyType___newindex },
		{ "__index", f_PropertyType___index },
		{ NULL, NULL },
	}), 0);
	lua_newtable(L);
	lua_pushcfunction(L, f_PropertyType___call);
	lua_setfield(L, -2, "__call");
	lua_setmetatable(L, -2);
	lua_pushlightuserdata(L, xml_PropertyType);
	lua_setfield(L, LUA_REGISTRYINDEX, "PropertyTypeParser");
	return 1;
}
ORCA_API int luaopen_orca_core(lua_State *L) {
	luaL_newlib(L, ((luaL_Reg[]) {
		{ "getFocus", f_core_getFocus },
		{ "getHover", f_core_getHover },
		{ NULL, NULL }
	}));
	void on_core_module_registered(lua_State *L);
	on_core_module_registered(L);
	// PropertyEnumValue
	luaopen_orca_PropertyEnumValue(L);
	lua_setfield(L, -2, "PropertyEnumValue");
	// PropertyType
	luaopen_orca_PropertyType(L);
	lua_setfield(L, -2, "PropertyType");
	// Object
	luaopen_orca_Object(L);
	lua_setfield(L, -2, "Object");
	return 1;
}
