// Generated by XSLT code generator
#ifndef __CORE_H__
#define __CORE_H__

#include <include/orca.h>

typedef struct Object Object_t;
typedef struct PropertyType PropertyType_t;
typedef struct PropertyEnumValue PropertyEnumValue_t;

// Core engine host object.
struct Object {
};

void Object_Clear(Object_t* self);

void Object_Release(Object_t* self);

bool Object_Equals(const Object_t* self, const Object* other);

void Object_Awake(Object_t* self);

void Object_Animate(Object_t* self);

void Object_LoadPrefabs(Object_t* self);

void Object_ProcesEvents(Object_t* self);

void Object_UpdateProperties(Object_t* self);

void Object_UpdateLayout(Object_t* self, int width, int height);

void Object_AddChild(Object_t* self, Object* child, bool is_template);

void Object_RemoveFromParent(Object_t* self, bool dropModal);

bool Object_SetProperty(Object_t* self, string Property);

nresults Object_GetProperty(Object_t* self, string Property);

Object* Object_FindChild(Object_t* self, string name, bool recursive);

Object* Object_DispatchEvent(Object_t* self, string event);

void Object_Play(Object_t* self, string animation);

void Object_Bind(Object_t* self, string Property, string expression);

void Object_SetFocus(Object_t* self);

void Object_DoTween(Object_t* self);

void Object_AddStyleSheet(Object_t* self, string source);

nresults Object_SetTimer(Object_t* self);

void Object_SetContext(Object_t* self);

string Object_GetName(const Object_t* self);

void Object_SetName(Object_t* self, string name);

string Object_GetClassName(const Object_t* self);

bool Object_CheckName(const Object_t* self, string name);

Object* Object_FindByPath(Object_t* self, string name);

uint Object_GetStyle(const Object_t* self);

void Object_SetStyle(Object_t* self, uint style);

string Object_FindCallbackForID(Object_t* self, uint event);

void Object_ApplyStyles(Object_t* self, bool recursive);

void Object_SetDirty(Object_t* self);

Object* Object_GetParent(const Object_t* self);

Object* Object_GetFirstChild(const Object_t* self);

Object* Object_GetNext(const Object_t* self);

Object* Object_GetRoot(Object_t* self);

Object* Object_FindChildByID(Object_t* self, uint id);

Object* Object_FindChildByAlias(Object_t* self, uint id);

string Object_GetSourceFile(const Object_t* self);

string Object_GetTextContent(const Object_t* self);

long Object_GetTimestamp(const Object_t* self);

uint Object_GetLuaObject(const Object_t* self);

uint Object_GetAlias(const Object_t* self);

uint Object_GetFlags(const Object_t* self);

void Object_SetFlags(Object_t* self, uint flags);

uint Object_GetIdentifier(const Object_t* self);

Object* Object_GetModal(const Object_t* self);

void Object_SetModal(Object_t* self, Object* modal);

bool Object_IsFocused(const Object_t* self);

void Object_SetHover(Object_t* self);

void Object_SetTextContent(Object_t* self, string text);

void Object_SetSourceFile(Object_t* self, string path);

void Object_SetClassName(Object_t* self, string classID);

Object* Object_FindParentOfClass(Object_t* self, uint classID);

Object* Object_FindChildOfClass(Object_t* self, uint classID);

bool Object_IsPrefabView(const Object_t* self);

void Object_AddAlias(Object_t* self, string name, string path);

void Object_AssignAliases(Object_t* self, string pathToObject);

void Object_ParseClassAttribute(Object_t* self, string classString);

void Object_SetAnimation(Object_t* self, string name);

const KeyframeAnim* Object_GetAnimation(const Object_t* self);

void Object_AddAnimation(Object_t* self, KeyframeAnim* animation);

int Object_GetInteger(const Object_t* self, uint ident, int fallback);

Property* Object_GetProperties(const Object_t* self);

Property* Object_FindPropertyByPath(Object_t* self, string path);

// Defines a custom property type that can be attached to engine objects.
struct PropertyType {
    PropertyDesc _desc;
    fixed Category;
    DataType DataType;
    fixed DefaultValue;
    fixed TargetType;
    bool AffectLayout;
    bool AffectRender;
    bool IsReadOnly;
    bool IsHidden;
    bool IsInherited;
    fixed Key;
    fixed Value;
    float Step;
    float UpperBound;
    float LowerBound;
};

// 
struct PropertyEnumValue {
    int Value;
};

#endif
