// Generated by XSLT code generator
#ifndef __SCENEKIT_H__
#define __SCENEKIT_H__

#include <include/orca.h>

#include <source/renderer/api/renderer.h>
#include <include/renderer.h>
#include <source/UIKit/UIKit.h>
typedef struct Node3D Node3D_t;
typedef struct Scene Scene_t;
typedef struct Model3D Model3D_t;
typedef struct PlaneMeshNode PlaneMeshNode_t;
typedef struct Camera Camera_t;
typedef struct TrajectoryList3D TrajectoryList3D_t;
typedef struct Viewport3D Viewport3D_t;
typedef struct PrefabView3D PrefabView3D_t;
typedef struct RenderPass RenderPass_t;
typedef struct CompositionTargetRenderPass CompositionTargetRenderPass_t;
typedef struct BlitRenderPass BlitRenderPass_t;
typedef struct ClearRenderPass ClearRenderPass_t;
typedef struct DrawObjectsRenderPass DrawObjectsRenderPass_t;
typedef struct PipelineStateRenderPass PipelineStateRenderPass_t;
typedef struct TextBlock3D TextBlock3D_t;
typedef struct Light3D Light3D_t;
typedef struct SpriteView SpriteView_t;

// Base class for all 3D scene graph nodes with transform and positioning capabilities
struct Node3D {
    Node_t base;
    float _opacity;
    transform3 LayoutTransform;
    transform3 RenderTransform;
    vec3 RenderTransformOrigin;
    vec3 ContentOffset;
    mat4 Matrix;
    float CalculatedOffset;
};

// Root container for 3D scene content with camera and rendering configuration
struct Scene {
    Node3D_t base;
    fixed Camera;
    fixed PreviewCamera;
    fixed HitTestCamera;
    RenderPass RenderPass;
    fixed BackgroundTimelineSequence;
    RenderPass ComposerOverride;
    Texture EnvironmentTexture;
};

// 3D model renderer that displays mesh geometry with materials
struct Model3D {
    Node3D_t base;
    Mesh Mesh;
    Material Material;
};

// Procedural plane mesh generator for creating rectangular surfaces
struct PlaneMeshNode {
    Model3D_t base;
    float PlaneWidth;
    float PlaneHeight;
    bool PlaneInvertU;
    bool PlaneInvertV;
    bool GenerateTangents;
    bool GenerateNormals;
    Material MeshMaterial;
};

// 3D camera for scene viewing and projection configuration
struct Camera {
    Node3D_t base;
    float Fov;
    FovType FovType;
    ProjectionType ProjectionType;
    float ZNear;
    float ZFar;
    float EyeSeparation;
    float FocalDistance;
    float OrthogonalPlaneHeight;
    bool ZPositive;
};

// Layout container that arranges child nodes along a 3D trajectory path
struct TrajectoryList3D {
    Node3D_t base;
    Trajectory Trajectory;
    vec2 ScrollAxis;
    bool Looping;
    float Spacing;
    float SelectionBehavior;
    float SelectedItemIndex;
};

// 2D viewport component that renders 3D scene content
struct Viewport3D {
    Node2D_t base;
    fixed Camera;
    fixed PreviewCamera;
    fixed HitTestCamera;
    RenderPass RenderPass;
    fixed Scene;
};

// Dynamic loader for 3D prefab assets and scene files
struct PrefabView3D {
    Node3D_t base;
    int _loadedSCA;
    int _loadedPrefab;
    fixed SCA;
    fixed Prefab;
};

// Base class for render pass components in the rendering pipeline
struct RenderPass {
    Node_t base;
};

// Render pass that outputs to the final composition target
struct CompositionTargetRenderPass {
    RenderPass_t base;
};

// Render pass for copying (blitting) between render targets
struct BlitRenderPass {
    RenderPass_t base;
};

// Render pass for clearing framebuffer contents
struct ClearRenderPass {
    RenderPass_t base;
    color ClearColor;
    float ClearDepth;
    int ClearStencil;
};

// Render pass for drawing scene objects with tag-based filtering
struct DrawObjectsRenderPass {
    RenderPass_t base;
    fixed Camera;
    objectTags IncludeTags;
    objectTags ExcludeTags;
};

// Render pass for configuring graphics pipeline state
struct PipelineStateRenderPass {
    RenderPass_t base;
    BlendMode BlendMode;
    ColorWriteMode ColorWriteMode;
    CullMode CullMode;
    CompareFunc DepthTestFunction;
    bool DepthWriteEnabled;
    ViewportMode ViewportMode;
    ViewportMode ScissorMode;
    vec4 Viewport;
    vec4 Scissor;
    CompareFunc StencilTestFunction;
    int StencilReferenceValue;
    int StencilMask;
    StencilOp StencilFailOperation;
    StencilOp StencilPassDepthFailOperation;
    StencilOp StencilPassDepthPassOperation;
    bool StencilWriteEnabled;
};

// 3D text renderer for displaying typography in 3D space
struct TextBlock3D {
    Node3D_t base;
    Node3D* _node3D;
};

// 3D light source for scene illumination and shadow casting
struct Light3D {
    Node3D_t base;
    color Color;
    vec2 SpotAngle;
    float Intensity;
    float Range;
    LightType Type;
};

// Billboard sprite renderer for 2D images in 3D space
struct SpriteView {
    Node3D_t base;
    Texture Image;
    vec4 Bounds;
};

#endif
