// Generated by codegen utility
#include <include/api.h>
#include <source/SpriteKit/SpriteKit.h>
#define DECL(SHORT, LONG, CLASS, NAME, FIELD, TYPE,...) { \
	.id=&(struct ID){.Name=#CLASS"."NAME,.Identifier=SHORT}, \
	.FullIdentifier=LONG, \
	.Offset=offsetof(struct CLASS, FIELD), \
	.DataSize=sizeof(((struct CLASS *)NULL)->FIELD), \
	.DataType=TYPE, ##__VA_ARGS__ }
#define ARRAY_DECL(SHORT, LONG, CLASS, NAME, FIELD, TYPE,...) { \
	.id=&(struct ID){.Name=#CLASS"."NAME,.Identifier=SHORT}, \
	.FullIdentifier=LONG, \
	.Offset=offsetof(struct CLASS, FIELD), \
	.DataSize=sizeof(*((struct CLASS *)NULL)->FIELD), \
	.DataType=TYPE, \
	.IsArray=TRUE, ##__VA_ARGS__ }

void luaX_pushSpriteFrame(lua_State *L, lpcSpriteFrame_t data) {
	lpSpriteFrame_t self = lua_newuserdata(L, sizeof(struct SpriteFrame));
	luaL_setmetatable(L, "SpriteFrame");
	memcpy(self, data, sizeof(struct SpriteFrame));
}
lpSpriteFrame_t luaX_checkSpriteFrame(lua_State *L, int idx) {
	return luaL_checkudata(L, idx, "SpriteFrame");
}
static int f_new_SpriteFrame(lua_State *L) {
	lpSpriteFrame_t self = lua_newuserdata(L, sizeof(struct SpriteFrame));
	luaL_setmetatable(L, "SpriteFrame");
	memset(self, 0, sizeof(struct SpriteFrame));
	return 1;
}
static int f_SpriteFrame___call(lua_State *L) {
	lua_remove(L, 1); // remove SpriteFrame from stack
	return f_new_SpriteFrame(L);
}
int f_SpriteFrame___index(lua_State *L) {
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	case 0x6b109927: // Rect
		luaX_pushrect(L, &luaX_checkSpriteFrame(L, 1)->Rect);
		return 1;
	case 0xae3d25c0: // UvRect
		luaX_pushrect(L, &luaX_checkSpriteFrame(L, 1)->UvRect);
		return 1;
	}
	return luaL_error(L, "Unknown field in SpriteFrame: %s", luaL_checkstring(L, 2));
}
int f_SpriteFrame___newindex(lua_State *L) {
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	case 0x6b109927: // Rect
		luaX_checkSpriteFrame(L, 1)->Rect = *luaX_checkrect(L, 3);
		return 0;
	case 0xae3d25c0: // UvRect
		luaX_checkSpriteFrame(L, 1)->UvRect = *luaX_checkrect(L, 3);
		return 0;
	}
	return luaL_error(L, "Unknown field in SpriteFrame: %s", luaL_checkstring(L, 2));
}
#include <libxml/parser.h>
ORCA_API int xmltoSpriteFrame(xmlNodePtr xml, lpSpriteFrame_t output) {
	if (xml == NULL) return FALSE;
	int xmltorect(xmlNodePtr, struct rect*);
	switch (xml->type) {
	case XML_ELEMENT_NODE:
		xmltorect((xmlNodePtr)xmlHasProp(xml, XMLSTR("Rect")), &output->Rect);
		xmltorect((xmlNodePtr)xmlHasProp(xml, XMLSTR("UvRect")), &output->UvRect);
		return TRUE;
	case XML_ATTRIBUTE_NODE:
		return TRUE;
	default:
		return FALSE;
	}
}

int luaopen_orca_SpriteFrame(lua_State *L) {
	luaL_newmetatable(L, "SpriteFrame");
	luaL_setfuncs(L, ((luaL_Reg[]) {
		{ "new", f_new_SpriteFrame },
		{ "__newindex", f_SpriteFrame___newindex },
		{ "__index", f_SpriteFrame___index },
		{ NULL, NULL },
	}), 0);
	lua_newtable(L);
	lua_pushcfunction(L, f_SpriteFrame___call);
	lua_setfield(L, -2, "__call");
	lua_setmetatable(L, -2);
	lua_pushlightuserdata(L, xmltoSpriteFrame);
	lua_setfield(L, LUA_REGISTRYINDEX, "SpriteFrameParser");
	return 1;
}
static struct PropertyDesc const SpriteAnimationProperties[kSpriteAnimationNumProperties] = {
	/* SpriteAnimation.Image */ DECL(0x590ca79a, 0xb710ed59,
	SpriteAnimation, "Image", Image, kDataTypeObject, .TypeString="Texture"),
	/* SpriteAnimation.Framerate */ DECL(0xbebf2a84, 0xc51f93cb,
	SpriteAnimation, "Framerate", Framerate, kDataTypeFloat),
	/* SpriteAnimation.NumFrames */ DECL(0x32caacb1, 0x37cc69de,
	SpriteAnimation, "NumFrames", NumFrames, kDataTypeInt),
	/* SpriteAnimation.Frames */ ARRAY_DECL(0xf03e266f, 0xcbc4645e,
	SpriteAnimation, "Frames", Frames, kDataTypeStruct, .TypeString="SpriteFrame"),
};
static struct SpriteAnimation SpriteAnimationDefaults = {0};
LRESULT SpriteAnimationProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
}
	return FALSE;
}
void luaX_pushSpriteAnimation(lua_State *L, lpcSpriteAnimation_t SpriteAnimation) {
	luaX_pushObject(L, CMP_GetObject(SpriteAnimation));
}
lpSpriteAnimation_t luaX_checkSpriteAnimation(lua_State *L, int idx) {
	return GetSpriteAnimation(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _SpriteAnimation = {
	.ClassName = "SpriteAnimation",
	.DefaultName = "SpriteAnimation",
	.ContentType = "SpriteAnimation",
	.Xmlns = "None",
	.ParentClasses = {NULL},
	.ClassID = ID_SpriteAnimation,
	.ClassSize = sizeof(struct SpriteAnimation),
	.Properties = SpriteAnimationProperties,
	.ObjProc = SpriteAnimationProc,
	.Defaults = &SpriteAnimationDefaults,
	.NumProperties = kSpriteAnimationNumProperties,
};
#include <libxml/parser.h>
ORCA_API int xmltoSpriteAnimation(xmlNodePtr xml, lpSpriteAnimation_t output) {
	if (xml == NULL) return FALSE;
	int xmltofloat(xmlNodePtr, float*);
	int xmltoint(xmlNodePtr, int32_t*);
	switch (xml->type) {
	case XML_ELEMENT_NODE:
		xmltofloat((xmlNodePtr)xmlHasProp(xml, XMLSTR("Framerate")), &output->Framerate);
		xmltoint((xmlNodePtr)xmlHasProp(xml, XMLSTR("NumFrames")), &output->NumFrames);
		return TRUE;
	case XML_ATTRIBUTE_NODE:
		return TRUE;
	default:
		return FALSE;
	}
}

LRESULT SKNode_UpdateMatrix(lpObject_t, lpSKNode_t, wParam_t, UpdateMatrixEventPtr);
static struct PropertyDesc const SKNodeProperties[kSKNodeNumProperties] = {
	/* SKNode.Position */ DECL(0xe27f342a, 0xa99d4e4c,
	SKNode, "Position", Position, kDataTypeStruct, .TypeString="Vector2D"),
	/* SKNode.Size */ DECL(0xa6478e7c, 0xeaed98c6,
	SKNode, "Size", Size, kDataTypeStruct, .TypeString="Vector2D"),
	/* SKNode.Anchor */ DECL(0xb54055d4, 0xf86abfb6,
	SKNode, "Anchor", Anchor, kDataTypeStruct, .TypeString="Vector2D"),
};
static struct SKNode SKNodeDefaults = {0};
LRESULT SKNodeProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case 0x5dbe404d: // UpdateMatrix
			return SKNode_UpdateMatrix(object, cmp, wparm, lparm);
}
	return FALSE;
}
void luaX_pushSKNode(lua_State *L, lpcSKNode_t SKNode) {
	luaX_pushObject(L, CMP_GetObject(SKNode));
}
lpSKNode_t luaX_checkSKNode(lua_State *L, int idx) {
	return GetSKNode(luaX_checkObject(L, idx));
}
extern struct ClassDesc _Node;
ORCA_API struct ClassDesc _SKNode = {
	.ClassName = "SKNode",
	.DefaultName = "SKNode",
	.ContentType = "Node",
	.Xmlns = "None",
	.ParentClasses = {&_Node, NULL},
	.ClassID = ID_SKNode,
	.ClassSize = sizeof(struct SKNode),
	.Properties = SKNodeProperties,
	.ObjProc = SKNodeProc,
	.Defaults = &SKNodeDefaults,
	.NumProperties = kSKNodeNumProperties,
};
#include <libxml/parser.h>
ORCA_API int xmltoSKNode(xmlNodePtr xml, lpSKNode_t output) {
	if (xml == NULL) return FALSE;
	int xmltovec2(xmlNodePtr, struct vec2*);
	switch (xml->type) {
	case XML_ELEMENT_NODE:
		xmltovec2((xmlNodePtr)xmlHasProp(xml, XMLSTR("Position")), &output->Position);
		xmltovec2((xmlNodePtr)xmlHasProp(xml, XMLSTR("Size")), &output->Size);
		xmltovec2((xmlNodePtr)xmlHasProp(xml, XMLSTR("Anchor")), &output->Anchor);
		return TRUE;
	case XML_ATTRIBUTE_NODE:
		return TRUE;
	default:
		return FALSE;
	}
}

LRESULT SKScene_UpdateMatrix(lpObject_t, lpSKScene_t, wParam_t, UpdateMatrixEventPtr);
static struct PropertyDesc const SKSceneProperties[kSKSceneNumProperties] = {
};
static struct SKScene SKSceneDefaults = {};
LRESULT SKSceneProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case 0x5dbe404d: // UpdateMatrix
			return SKScene_UpdateMatrix(object, cmp, wparm, lparm);
}
	return FALSE;
}
void luaX_pushSKScene(lua_State *L, lpcSKScene_t SKScene) {
	luaX_pushObject(L, CMP_GetObject(SKScene));
}
lpSKScene_t luaX_checkSKScene(lua_State *L, int idx) {
	return GetSKScene(luaX_checkObject(L, idx));
}
extern struct ClassDesc _SKNode;
ORCA_API struct ClassDesc _SKScene = {
	.ClassName = "SKScene",
	.DefaultName = "SKScene",
	.ContentType = "SKNode",
	.Xmlns = "None",
	.ParentClasses = {&_SKNode, NULL},
	.ClassID = ID_SKScene,
	.ClassSize = sizeof(struct SKScene),
	.Properties = SKSceneProperties,
	.ObjProc = SKSceneProc,
	.Defaults = &SKSceneDefaults,
	.NumProperties = kSKSceneNumProperties,
};
#include <libxml/parser.h>
ORCA_API int xmltoSKScene(xmlNodePtr xml, lpSKScene_t output) {
	if (xml == NULL) return FALSE;
	switch (xml->type) {
	case XML_ELEMENT_NODE:
		return TRUE;
	case XML_ATTRIBUTE_NODE:
		return TRUE;
	default:
		return FALSE;
	}
}

LRESULT SKSpriteNode_Render(lpObject_t, lpSKSpriteNode_t, wParam_t, RenderEventPtr);
static struct PropertyDesc const SKSpriteNodeProperties[kSKSpriteNodeNumProperties] = {
	/* SKSpriteNode.Animation */ DECL(0x41e389fd, 0xdfc01dce,
	SKSpriteNode, "Animation", Animation, kDataTypeObject, .TypeString="SpriteAnimation"),
	/* SKSpriteNode.Animation2 */ DECL(0x8831f0dd, 0x376f33b4,
	SKSpriteNode, "Animation2", Animation2, kDataTypeObject, .TypeString="SpriteAnimation"),
	/* SKSpriteNode.Image */ DECL(0x590ca79a, 0x7d43a6bd,
	SKSpriteNode, "Image", Image, kDataTypeObject, .TypeString="Texture"),
	/* SKSpriteNode.FreezeFrame */ DECL(0xa9f98a53, 0x371f13e0,
	SKSpriteNode, "FreezeFrame", FreezeFrame, kDataTypeInt),
	/* SKSpriteNode.BlendMode */ DECL(0x0038792b, 0x240fc724,
	SKSpriteNode, "BlendMode", BlendMode, kDataTypeEnum, .TypeString="AlphaAutomatic,Opaque,Alpha,Additive,PremultipliedAlpha,MixedAlpha"),
	/* SKSpriteNode.UvRect */ DECL(0xae3d25c0, 0xc27a0d8d,
	SKSpriteNode, "UvRect", UvRect, kDataTypeStruct, .TypeString="Rectangle"),
	/* SKSpriteNode.UvRectX */ DECL(0xe2422e48, 0xfb23c64f,
	SKSpriteNode, "UvRectX", UvRect.x, kDataTypeFloat),
	/* SKSpriteNode.UvRectY */ DECL(0xe3422fdb, 0xfa23c4bc,
	SKSpriteNode, "UvRectY", UvRect.y, kDataTypeFloat),
	/* SKSpriteNode.UvRectWidth */ DECL(0xec9d6ecc, 0xfcdbf497,
	SKSpriteNode, "UvRectWidth", UvRect.width, kDataTypeFloat),
	/* SKSpriteNode.UvRectHeight */ DECL(0xdbdb8abb, 0xea8ad8da,
	SKSpriteNode, "UvRectHeight", UvRect.height, kDataTypeFloat),
};
static struct SKSpriteNode SKSpriteNodeDefaults = {
	.FreezeFrame = -1,
	.BlendMode = kBlendModeAlphaAutomatic,
};
LRESULT SKSpriteNodeProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case 0x350cf42d: // Render
			return SKSpriteNode_Render(object, cmp, wparm, lparm);
}
	return FALSE;
}
void luaX_pushSKSpriteNode(lua_State *L, lpcSKSpriteNode_t SKSpriteNode) {
	luaX_pushObject(L, CMP_GetObject(SKSpriteNode));
}
lpSKSpriteNode_t luaX_checkSKSpriteNode(lua_State *L, int idx) {
	return GetSKSpriteNode(luaX_checkObject(L, idx));
}
extern struct ClassDesc _SKNode;
ORCA_API struct ClassDesc _SKSpriteNode = {
	.ClassName = "SKSpriteNode",
	.DefaultName = "SKSpriteNode",
	.ContentType = "SKNode",
	.Xmlns = "None",
	.ParentClasses = {&_SKNode, NULL},
	.ClassID = ID_SKSpriteNode,
	.ClassSize = sizeof(struct SKSpriteNode),
	.Properties = SKSpriteNodeProperties,
	.ObjProc = SKSpriteNodeProc,
	.Defaults = &SKSpriteNodeDefaults,
	.NumProperties = kSKSpriteNodeNumProperties,
};
#include <libxml/parser.h>
ORCA_API int xmltoSKSpriteNode(xmlNodePtr xml, lpSKSpriteNode_t output) {
	if (xml == NULL) return FALSE;
	int xmltoBlendMode(xmlNodePtr, enum BlendMode*);
	int xmltoint(xmlNodePtr, int32_t*);
	int xmltorect(xmlNodePtr, struct rect*);
	switch (xml->type) {
	case XML_ELEMENT_NODE:
		xmltoint((xmlNodePtr)xmlHasProp(xml, XMLSTR("FreezeFrame")), &output->FreezeFrame);
		xmltoBlendMode((xmlNodePtr)xmlHasProp(xml, XMLSTR("BlendMode")), &output->BlendMode);
		xmltorect((xmlNodePtr)xmlHasProp(xml, XMLSTR("UvRect")), &output->UvRect);
		return TRUE;
	case XML_ATTRIBUTE_NODE:
		return TRUE;
	default:
		return FALSE;
	}
}

LRESULT SKLabelNode_Render(lpObject_t, lpSKLabelNode_t, wParam_t, RenderEventPtr);
LRESULT SKLabelNode_Create(lpObject_t, lpSKLabelNode_t, wParam_t, CreateEventPtr);
static struct PropertyDesc const SKLabelNodeProperties[kSKLabelNodeNumProperties] = {
	/* SKLabelNode.Color */ DECL(0xe5b43cf8, 0x84bf37d6,
	SKLabelNode, "Color", Color, kDataTypeStruct, .TypeString="Color"),
};
static struct SKLabelNode SKLabelNodeDefaults = {0};
LRESULT SKLabelNodeProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case 0x350cf42d: // Render
			return SKLabelNode_Render(object, cmp, wparm, lparm);
		case 0x990de47d: // Create
			return SKLabelNode_Create(object, cmp, wparm, lparm);
}
	return FALSE;
}
void luaX_pushSKLabelNode(lua_State *L, lpcSKLabelNode_t SKLabelNode) {
	luaX_pushObject(L, CMP_GetObject(SKLabelNode));
}
lpSKLabelNode_t luaX_checkSKLabelNode(lua_State *L, int idx) {
	return GetSKLabelNode(luaX_checkObject(L, idx));
}
extern struct ClassDesc _SKNode;
extern struct ClassDesc _TextBlockConcept;
ORCA_API struct ClassDesc _SKLabelNode = {
	.ClassName = "SKLabelNode",
	.DefaultName = "SKLabelNode",
	.ContentType = "SKNode",
	.Xmlns = "None",
	.ParentClasses = {&_SKNode, &_TextBlockConcept, NULL},
	.ClassID = ID_SKLabelNode,
	.ClassSize = sizeof(struct SKLabelNode),
	.Properties = SKLabelNodeProperties,
	.ObjProc = SKLabelNodeProc,
	.Defaults = &SKLabelNodeDefaults,
	.NumProperties = kSKLabelNodeNumProperties,
};
#include <libxml/parser.h>
ORCA_API int xmltoSKLabelNode(xmlNodePtr xml, lpSKLabelNode_t output) {
	if (xml == NULL) return FALSE;
	int xmltocolor(xmlNodePtr, struct color*);
	switch (xml->type) {
	case XML_ELEMENT_NODE:
		xmltocolor((xmlNodePtr)xmlHasProp(xml, XMLSTR("Color")), &output->Color);
		return TRUE;
	case XML_ATTRIBUTE_NODE:
		return TRUE;
	default:
		return FALSE;
	}
}

LRESULT SKView_ForegroundContent(lpObject_t, lpSKView_t, wParam_t, ForegroundContentEventPtr);
static struct PropertyDesc const SKViewProperties[kSKViewNumProperties] = {
	/* SKView.ReferenceWidth */ DECL(0x499d2ae6, 0x5c81a8f7,
	SKView, "ReferenceWidth", ReferenceWidth, kDataTypeFloat),
	/* SKView.ReferenceHeight */ DECL(0xf011cff9, 0x4b5832ba,
	SKView, "ReferenceHeight", ReferenceHeight, kDataTypeFloat),
	/* SKView.Scene */ DECL(0xc89b38b3, 0x71075038,
	SKView, "Scene", Scene, kDataTypeFixed),
};
static struct SKView SKViewDefaults = {0};
LRESULT SKViewProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case 0x9a7735e5: // ForegroundContent
			return SKView_ForegroundContent(object, cmp, wparm, lparm);
}
	return FALSE;
}
void luaX_pushSKView(lua_State *L, lpcSKView_t SKView) {
	luaX_pushObject(L, CMP_GetObject(SKView));
}
lpSKView_t luaX_checkSKView(lua_State *L, int idx) {
	return GetSKView(luaX_checkObject(L, idx));
}
extern struct ClassDesc _Node2D;
ORCA_API struct ClassDesc _SKView = {
	.ClassName = "SKView",
	.DefaultName = "SKView",
	.ContentType = "Node2D",
	.Xmlns = "None",
	.ParentClasses = {&_Node2D, NULL},
	.ClassID = ID_SKView,
	.ClassSize = sizeof(struct SKView),
	.Properties = SKViewProperties,
	.ObjProc = SKViewProc,
	.Defaults = &SKViewDefaults,
	.NumProperties = kSKViewNumProperties,
};
#include <libxml/parser.h>
ORCA_API int xmltoSKView(xmlNodePtr xml, lpSKView_t output) {
	if (xml == NULL) return FALSE;
	int xmltofixed(xmlNodePtr, fixedString_t*);
	int xmltofloat(xmlNodePtr, float*);
	switch (xml->type) {
	case XML_ELEMENT_NODE:
		xmltofloat((xmlNodePtr)xmlHasProp(xml, XMLSTR("ReferenceWidth")), &output->ReferenceWidth);
		xmltofloat((xmlNodePtr)xmlHasProp(xml, XMLSTR("ReferenceHeight")), &output->ReferenceHeight);
		xmltofixed((xmlNodePtr)xmlHasProp(xml, XMLSTR("Scene")), &output->Scene);
		return TRUE;
	case XML_ATTRIBUTE_NODE:
		return TRUE;
	default:
		return FALSE;
	}
}

ORCA_API int luaopen_orca_SpriteKit(lua_State *L) {
	luaL_newlib(L, ((luaL_Reg[]) {
		{ NULL, NULL }
	}));
	void on_spritekit_module_registered(lua_State *L);
	on_spritekit_module_registered(L);
	// SpriteFrame
	luaopen_orca_SpriteFrame(L);
	lua_setfield(L, -2, "SpriteFrame");
	// SpriteAnimation
	lua_pushclass(L, &_SpriteAnimation);
	lua_setfield(L, -2, "SpriteAnimation");
	lua_pushlightuserdata(L, xmltoSpriteAnimation);
	lua_setfield(L, LUA_REGISTRYINDEX, "SpriteAnimationParser");
	// SKNode
	lua_pushclass(L, &_SKNode);
	lua_setfield(L, -2, "SKNode");
	lua_pushlightuserdata(L, xmltoSKNode);
	lua_setfield(L, LUA_REGISTRYINDEX, "SKNodeParser");
	// SKScene
	lua_pushclass(L, &_SKScene);
	lua_setfield(L, -2, "SKScene");
	lua_pushlightuserdata(L, xmltoSKScene);
	lua_setfield(L, LUA_REGISTRYINDEX, "SKSceneParser");
	// SKSpriteNode
	lua_pushclass(L, &_SKSpriteNode);
	lua_setfield(L, -2, "SKSpriteNode");
	lua_pushlightuserdata(L, xmltoSKSpriteNode);
	lua_setfield(L, LUA_REGISTRYINDEX, "SKSpriteNodeParser");
	// SKLabelNode
	lua_pushclass(L, &_SKLabelNode);
	lua_setfield(L, -2, "SKLabelNode");
	lua_pushlightuserdata(L, xmltoSKLabelNode);
	lua_setfield(L, LUA_REGISTRYINDEX, "SKLabelNodeParser");
	// SKView
	lua_pushclass(L, &_SKView);
	lua_setfield(L, -2, "SKView");
	lua_pushlightuserdata(L, xmltoSKView);
	lua_setfield(L, LUA_REGISTRYINDEX, "SKViewParser");
	return 1;
}
