// Generated by codegen utility
#include <include/api.h>
#include <source/SpriteKit/SpriteKit.h>
#define DECL(SHORT, CLASS, NAME, FIELD, TYPE,...) { \
	.Name=#CLASS"."#NAME, \
	.Category=#CLASS, \
	.ShortIdentifier=SHORT, \
	.FullIdentifier=ID_##CLASS##_##NAME, \
	.Offset=offsetof(struct CLASS, FIELD), \
	.DataSize=sizeof(((struct CLASS *)NULL)->FIELD), \
	.DataType=TYPE, ##__VA_ARGS__ }
#define ARRAY_DECL(SHORT, CLASS, NAME, FIELD, TYPE,...) { \
	.Name=#CLASS"."#NAME, \
	.Category=#CLASS, \
	.ShortIdentifier=SHORT, \
	.FullIdentifier=ID_##CLASS##_##NAME, \
	.Offset=offsetof(struct CLASS, FIELD), \
	.DataSize=sizeof(*((struct CLASS *)NULL)->FIELD), \
	.DataType=TYPE, \
	.IsArray=TRUE, ##__VA_ARGS__ }

void luaX_pushSpriteFrame(lua_State *L, lpcSpriteFrame_t data) {
	if (data == NULL) { lua_pushnil(L); return; }
	lpSpriteFrame_t self = lua_newuserdata(L, sizeof(struct SpriteFrame));
	luaL_setmetatable(L, "SpriteFrame");
	memcpy(self, data, sizeof(struct SpriteFrame));
}
lpSpriteFrame_t luaX_checkSpriteFrame(lua_State *L, int idx) {
	return luaL_checkudata(L, idx, "SpriteFrame");
}
static int f_new_SpriteFrame(lua_State *L) {
	lpSpriteFrame_t self = lua_newuserdata(L, sizeof(struct SpriteFrame));
	luaL_setmetatable(L, "SpriteFrame");
	memset(self, 0, sizeof(struct SpriteFrame));
	if (lua_gettop(L) == 1) return 1;
	return 1;
}
static int f_SpriteFrame___call(lua_State *L) {
	lua_remove(L, 1); // remove SpriteFrame from stack
	return f_new_SpriteFrame(L);
}
int f_SpriteFrame___index(lua_State *L) {
	lpSpriteFrame_t self = luaX_checkSpriteFrame(L, 1);
	switch(self?fnv1a32(luaL_checkstring(L, 2)):0) { // Check is not needed but to silence unused variable warning
	case 0x6b109927: luaX_pushrect(L, &self->Rect); return 1; // Rect
	case 0xae3d25c0: luaX_pushrect(L, &self->UvRect); return 1; // UvRect
	}
	return luaL_error(L, "Unknown field in SpriteFrame: %s", luaL_checkstring(L, 2));
}
int f_SpriteFrame___newindex(lua_State *L) {
	lpSpriteFrame_t self = luaX_checkSpriteFrame(L, 1);
	switch(self?fnv1a32(luaL_checkstring(L, 2)):0) { // Check is not needed but to silence unused variable warning
	case 0x6b109927: self->Rect = *luaX_checkrect(L, 3); return 0; // Rect
	case 0xae3d25c0: self->UvRect = *luaX_checkrect(L, 3); return 0; // UvRect
	}
	return luaL_error(L, "Unknown field in SpriteFrame: %s", luaL_checkstring(L, 2));
}
int luaopen_orca_SpriteFrame(lua_State *L) {
	luaL_newmetatable(L, "SpriteFrame");
	luaL_setfuncs(L, ((luaL_Reg[]) {
		{ "new", f_new_SpriteFrame },
		{ "__newindex", f_SpriteFrame___newindex },
		{ "__index", f_SpriteFrame___index },
		{ NULL, NULL },
	}), 0);
	lua_newtable(L);
	lua_pushcfunction(L, f_SpriteFrame___call);
	lua_setfield(L, -2, "__call");
	lua_setmetatable(L, -2);
	return 1;
}
static struct PropertyType const SpriteAnimationProperties[kSpriteAnimationNumProperties] = {
	DECL(0x590ca79a, SpriteAnimation, Image, Image, kDataTypeObject, .TypeString="Texture"), // SpriteAnimation.Image
	DECL(0xbebf2a84, SpriteAnimation, Framerate, Framerate, kDataTypeFloat), // SpriteAnimation.Framerate
	ARRAY_DECL(0xf03e266f, SpriteAnimation, Frames, Frames, kDataTypeStruct, .TypeString="SpriteFrame"), // SpriteAnimation.Frames
	DECL(0x32caacb1, SpriteAnimation, NumFrames, NumFrames, kDataTypeInt), // SpriteAnimation.NumFrames
};
static struct SpriteAnimation SpriteAnimationDefaults = {0};
LRESULT SpriteAnimationProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
}
	return FALSE;
}
void luaX_pushSpriteAnimation(lua_State *L, lpcSpriteAnimation_t SpriteAnimation) {
	luaX_pushObject(L, CMP_GetObject(SpriteAnimation));
}
lpSpriteAnimation_t luaX_checkSpriteAnimation(lua_State *L, int idx) {
	return GetSpriteAnimation(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _SpriteAnimation = {
	.ClassName = "SpriteAnimation",
	.DefaultName = "SpriteAnimation",
	.ContentType = "SpriteAnimation",
	.Xmlns = "None",
	.ParentClasses = {NULL},
	.ClassID = ID_SpriteAnimation,
	.ClassSize = sizeof(struct SpriteAnimation),
	.Properties = SpriteAnimationProperties,
	.ObjProc = SpriteAnimationProc,
	.Defaults = &SpriteAnimationDefaults,
	.NumProperties = kSpriteAnimationNumProperties,
};
LRESULT SKNode_UpdateMatrix(lpObject_t, lpSKNode_t, wParam_t, UpdateMatrixEventPtr);
static struct PropertyType const SKNodeProperties[kSKNodeNumProperties] = {
	DECL(0xe27f342a, SKNode, Position, Position, kDataTypeStruct, .TypeString="Vector2D"), // SKNode.Position
	DECL(0xa6478e7c, SKNode, Size, Size, kDataTypeStruct, .TypeString="Vector2D"), // SKNode.Size
	DECL(0xb54055d4, SKNode, Anchor, Anchor, kDataTypeStruct, .TypeString="Vector2D"), // SKNode.Anchor
};
static struct SKNode SKNodeDefaults = {0};
LRESULT SKNodeProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventUpdateMatrix: return SKNode_UpdateMatrix(object, cmp, wparm, lparm); // UpdateMatrix
}
	return FALSE;
}
void luaX_pushSKNode(lua_State *L, lpcSKNode_t SKNode) {
	luaX_pushObject(L, CMP_GetObject(SKNode));
}
lpSKNode_t luaX_checkSKNode(lua_State *L, int idx) {
	return GetSKNode(luaX_checkObject(L, idx));
}
extern struct ClassDesc _Node;
ORCA_API struct ClassDesc _SKNode = {
	.ClassName = "SKNode",
	.DefaultName = "SKNode",
	.ContentType = "Node",
	.Xmlns = "None",
	.ParentClasses = {&_Node, NULL},
	.ClassID = ID_SKNode,
	.ClassSize = sizeof(struct SKNode),
	.Properties = SKNodeProperties,
	.ObjProc = SKNodeProc,
	.Defaults = &SKNodeDefaults,
	.NumProperties = kSKNodeNumProperties,
};
LRESULT SKScene_UpdateMatrix(lpObject_t, lpSKScene_t, wParam_t, UpdateMatrixEventPtr);
static struct PropertyType const SKSceneProperties[kSKSceneNumProperties] = {
};
static struct SKScene SKSceneDefaults = {};
LRESULT SKSceneProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventUpdateMatrix: return SKScene_UpdateMatrix(object, cmp, wparm, lparm); // UpdateMatrix
}
	return FALSE;
}
void luaX_pushSKScene(lua_State *L, lpcSKScene_t SKScene) {
	luaX_pushObject(L, CMP_GetObject(SKScene));
}
lpSKScene_t luaX_checkSKScene(lua_State *L, int idx) {
	return GetSKScene(luaX_checkObject(L, idx));
}
extern struct ClassDesc _SKNode;
ORCA_API struct ClassDesc _SKScene = {
	.ClassName = "SKScene",
	.DefaultName = "SKScene",
	.ContentType = "SKNode",
	.Xmlns = "None",
	.ParentClasses = {&_SKNode, NULL},
	.ClassID = ID_SKScene,
	.ClassSize = sizeof(struct SKScene),
	.Properties = SKSceneProperties,
	.ObjProc = SKSceneProc,
	.Defaults = &SKSceneDefaults,
	.NumProperties = kSKSceneNumProperties,
};
LRESULT SKSpriteNode_Render(lpObject_t, lpSKSpriteNode_t, wParam_t, RenderEventPtr);
static struct PropertyType const SKSpriteNodeProperties[kSKSpriteNodeNumProperties] = {
	DECL(0x41e389fd, SKSpriteNode, Animation, Animation, kDataTypeObject, .TypeString="SpriteAnimation"), // SKSpriteNode.Animation
	DECL(0x8831f0dd, SKSpriteNode, Animation2, Animation2, kDataTypeObject, .TypeString="SpriteAnimation"), // SKSpriteNode.Animation2
	DECL(0x590ca79a, SKSpriteNode, Image, Image, kDataTypeObject, .TypeString="Texture"), // SKSpriteNode.Image
	DECL(0xa9f98a53, SKSpriteNode, FreezeFrame, FreezeFrame, kDataTypeInt), // SKSpriteNode.FreezeFrame
	DECL(0x0038792b, SKSpriteNode, BlendMode, BlendMode, kDataTypeEnum, .TypeString="AlphaAutomatic,Opaque,Alpha,Additive,PremultipliedAlpha,MixedAlpha"), // SKSpriteNode.BlendMode
	DECL(0xae3d25c0, SKSpriteNode, UvRect, UvRect, kDataTypeStruct, .TypeString="Rectangle"), // SKSpriteNode.UvRect
	DECL(0xe2422e48, SKSpriteNode, UvRectX, UvRect.x, kDataTypeFloat), // SKSpriteNode.UvRectX
	DECL(0xe3422fdb, SKSpriteNode, UvRectY, UvRect.y, kDataTypeFloat), // SKSpriteNode.UvRectY
	DECL(0xec9d6ecc, SKSpriteNode, UvRectWidth, UvRect.width, kDataTypeFloat), // SKSpriteNode.UvRectWidth
	DECL(0xdbdb8abb, SKSpriteNode, UvRectHeight, UvRect.height, kDataTypeFloat), // SKSpriteNode.UvRectHeight
};
static struct SKSpriteNode SKSpriteNodeDefaults = {
	.FreezeFrame = -1,
	.BlendMode = kBlendModeAlphaAutomatic,
};
LRESULT SKSpriteNodeProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventRender: return SKSpriteNode_Render(object, cmp, wparm, lparm); // Render
}
	return FALSE;
}
void luaX_pushSKSpriteNode(lua_State *L, lpcSKSpriteNode_t SKSpriteNode) {
	luaX_pushObject(L, CMP_GetObject(SKSpriteNode));
}
lpSKSpriteNode_t luaX_checkSKSpriteNode(lua_State *L, int idx) {
	return GetSKSpriteNode(luaX_checkObject(L, idx));
}
extern struct ClassDesc _SKNode;
ORCA_API struct ClassDesc _SKSpriteNode = {
	.ClassName = "SKSpriteNode",
	.DefaultName = "SKSpriteNode",
	.ContentType = "SKNode",
	.Xmlns = "None",
	.ParentClasses = {&_SKNode, NULL},
	.ClassID = ID_SKSpriteNode,
	.ClassSize = sizeof(struct SKSpriteNode),
	.Properties = SKSpriteNodeProperties,
	.ObjProc = SKSpriteNodeProc,
	.Defaults = &SKSpriteNodeDefaults,
	.NumProperties = kSKSpriteNodeNumProperties,
};
LRESULT SKLabelNode_Render(lpObject_t, lpSKLabelNode_t, wParam_t, RenderEventPtr);
LRESULT SKLabelNode_Create(lpObject_t, lpSKLabelNode_t, wParam_t, CreateEventPtr);
static struct PropertyType const SKLabelNodeProperties[kSKLabelNodeNumProperties] = {
	DECL(0xe5b43cf8, SKLabelNode, Color, Color, kDataTypeStruct, .TypeString="Color"), // SKLabelNode.Color
};
static struct SKLabelNode SKLabelNodeDefaults = {0};
LRESULT SKLabelNodeProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventRender: return SKLabelNode_Render(object, cmp, wparm, lparm); // Render
		case kEventCreate: return SKLabelNode_Create(object, cmp, wparm, lparm); // Create
}
	return FALSE;
}
void luaX_pushSKLabelNode(lua_State *L, lpcSKLabelNode_t SKLabelNode) {
	luaX_pushObject(L, CMP_GetObject(SKLabelNode));
}
lpSKLabelNode_t luaX_checkSKLabelNode(lua_State *L, int idx) {
	return GetSKLabelNode(luaX_checkObject(L, idx));
}
extern struct ClassDesc _SKNode;
extern struct ClassDesc _TextBlockConcept;
ORCA_API struct ClassDesc _SKLabelNode = {
	.ClassName = "SKLabelNode",
	.DefaultName = "SKLabelNode",
	.ContentType = "SKNode",
	.Xmlns = "None",
	.ParentClasses = {&_SKNode, &_TextBlockConcept, NULL},
	.ClassID = ID_SKLabelNode,
	.ClassSize = sizeof(struct SKLabelNode),
	.Properties = SKLabelNodeProperties,
	.ObjProc = SKLabelNodeProc,
	.Defaults = &SKLabelNodeDefaults,
	.NumProperties = kSKLabelNodeNumProperties,
};
LRESULT SKView_ForegroundContent(lpObject_t, lpSKView_t, wParam_t, ForegroundContentEventPtr);
static struct PropertyType const SKViewProperties[kSKViewNumProperties] = {
	DECL(0x499d2ae6, SKView, ReferenceWidth, ReferenceWidth, kDataTypeFloat), // SKView.ReferenceWidth
	DECL(0xf011cff9, SKView, ReferenceHeight, ReferenceHeight, kDataTypeFloat), // SKView.ReferenceHeight
	DECL(0xc89b38b3, SKView, Scene, Scene, kDataTypeFixed), // SKView.Scene
};
static struct SKView SKViewDefaults = {0};
LRESULT SKViewProc(lpObject_t object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventForegroundContent: return SKView_ForegroundContent(object, cmp, wparm, lparm); // ForegroundContent
}
	return FALSE;
}
void luaX_pushSKView(lua_State *L, lpcSKView_t SKView) {
	luaX_pushObject(L, CMP_GetObject(SKView));
}
lpSKView_t luaX_checkSKView(lua_State *L, int idx) {
	return GetSKView(luaX_checkObject(L, idx));
}
extern struct ClassDesc _Node2D;
ORCA_API struct ClassDesc _SKView = {
	.ClassName = "SKView",
	.DefaultName = "SKView",
	.ContentType = "Node2D",
	.Xmlns = "None",
	.ParentClasses = {&_Node2D, NULL},
	.ClassID = ID_SKView,
	.ClassSize = sizeof(struct SKView),
	.Properties = SKViewProperties,
	.ObjProc = SKViewProc,
	.Defaults = &SKViewDefaults,
	.NumProperties = kSKViewNumProperties,
};
ORCA_API int luaopen_orca_SpriteKit(lua_State *L) {
	luaL_newlib(L, ((luaL_Reg[]) {
		{ NULL, NULL }
	}));
	void on_spritekit_module_registered(lua_State *L);
	on_spritekit_module_registered(L);
	// SpriteFrame
	luaopen_orca_SpriteFrame(L);
	lua_setfield(L, -2, "SpriteFrame");
	// SpriteAnimation
	lua_pushclass(L, &_SpriteAnimation);
	lua_setfield(L, -2, "SpriteAnimation");
	// SKNode
	lua_pushclass(L, &_SKNode);
	lua_setfield(L, -2, "SKNode");
	// SKScene
	lua_pushclass(L, &_SKScene);
	lua_setfield(L, -2, "SKScene");
	// SKSpriteNode
	lua_pushclass(L, &_SKSpriteNode);
	lua_setfield(L, -2, "SKSpriteNode");
	// SKLabelNode
	lua_pushclass(L, &_SKLabelNode);
	lua_setfield(L, -2, "SKLabelNode");
	// SKView
	lua_pushclass(L, &_SKView);
	lua_setfield(L, -2, "SKView");
	return 1;
}
