<?php

class config {
	// Each type entry must be a single-line array (pyphp limitation with nested multi-line dicts)
	public static $TypeInfos = [
		"float" => [
			'decl' => 'float', 
			'check' => 'luaL_checknumber(L, {arg})', 
			'pop' => '{addr} = luaL_optnumber(L, {arg}, 0)', 
			'push' => 'lua_pushnumber(L, {arg})',  
			'convert' => '{addr} = {arg}', 
			'format' => "%f",
			'default' => "%s",
		],
		"int" => [
			'decl' => 'int32_t', 
			'check' => '(int32_t)luaL_checkinteger(L, {arg})', 
			'pop' => '{addr} = (int32_t)luaL_optinteger(L, {arg}, 0)', 
			'push' => 'lua_pushinteger(L, {arg})',  
			'convert' => '{addr} = {arg}', 
			'format' => "%d",
			'default' => "%s",
		],
		"uint" => [
			'decl' => 'uint32_t', 
			'check' => '(uint32_t)luaL_checkinteger(L, {arg})', 
			'pop' => '{addr} = (uint32_t)luaL_optinteger(L, {arg}, 0)', 
			'push' => 'lua_pushinteger(L, {arg})',  
			'convert' => '{addr} = {arg}', 
			'format' => "%u",
			'default' => "%s",
		],
		"long" => [
			'decl' => 'long', 
			'check' => 'luaL_checkinteger(L, {arg})',
			'pop' => '{addr} = luaL_optinteger(L, {arg}, 0)',
			'push' => 'lua_pushinteger(L, {arg})', 
			'convert' => '{addr} = {arg}', 
			'format' => "%ld",
			'default' => "%s",
		],
		"bool" => [
			'decl' => 'bool_t', 
			'check' => 'lua_toboolean(L, {arg})', 
			'pop' => '{addr} = lua_toboolean(L, {arg})', 
			'push' => 'lua_pushboolean(L, {arg})', 
			'convert' => '{addr} = !strcmp({arg}, "true")', 
			'format' => "%s",
			'default' => "%s",
		],
		"string" => [
			'decl' => 'const char*', 
			'check' => 'luaL_checkstring(L, {arg})', 
			'pop' => '{addr} = lua_type(L, {arg}) == LUA_TSTRING ? strdup(luaL_checkstring(L, {arg})) : NULL', 
			'push' => 'lua_pushstring(L, {arg})',  
			'convert' => '{addr} = {arg}', 
			'format' => "%s",
			'default' => "\"%s\"",
		],
		"enum" => [
			'decl' => 'enum %s', 
			'check' => 'luaX_check{type}(L, {arg})', 
			'pop' => '{addr} = lua_type(L, {arg}) == LUA_TSTRING ? luaX_check{type}(L, {arg}) : 0', 
			'push' => 'luaX_push{type}(L, {arg})', 
			'convert' => 'lua_pop(L, (lua_pushstring(L, {arg}), {addr} = luaL_checkoption(L, -1, NULL, _{type}), 1));', 
			'format' => "%s",
			'default' => "k{type}%s",
		],
		"struct" => [
			'decl' => 'struct %s', 
			'check' => 'luaX_check{type}(L, {arg})', 
			'pop' => '{addr} = lua_type(L, {arg}) == LUA_TUSERDATA ? *luaX_check{type}(L, {arg}) : (struct {type}){0}',
			'push' => 'luaX_push{type}(L, &{arg})',
			'convert' => '{addr} = {arg}', 
			'format' => "%s",
			'default' => "{%s}",
		],
		"interface" => [
			'decl' => 'struct %s', 
			'check' => 'luaX_check{type}(L, {arg})', 
			'pop' => '{addr} = luaX_check{type}(L, {arg})',
			'push' => 'luaX_push{type}(L, {arg})',
			'convert' => '{addr} = {arg}', 
			'format' => "%s",
			'default' => "{%s}",
		],
		"component" => [
			'decl' => 'struct %s', 
			'check' => 'luaX_check{type}(L, {arg})', 
			'pop' => '{addr} = luaX_check{type}(L, {arg})',
			'push' => 'luaX_push{type}(L, {arg})', 
			'convert' => 'lua_pop(L, (f_convert_string(L, &(struct PropertyType) { .DataType = kDataTypeObject, .TypeString = "{type}" }, {arg}, TRUE), {addr} = luaX_check{type}(L, -1), 1));', 
			'format' => "%s",
			'default' => "{%s}",
		],
		"external_struct" => [
			'decl' => 'struct %s', 
			'check' => 'NULL', 
			'pop' => '{addr} = NULL',
			'push' => 'luaX_push{type}(L, {arg})',
			'convert' => '', 
			'format' => "%s",
			'default' => "{%s}"
		],
		"strarray" => [
			'decl' => 'lpcString_t const*',
			'format' => "%s",
		],
		"nresults" => [
			'decl' => 'int',
			'push' => 'lua_pushnil(L)', 
			'return' => 'return {arg};' 
		],
		"void" => [
			'decl' => '%s', 
			'return' => '{arg};\n\treturn 0;' 
		],
		"lua_State" => [],
		"ptr" => [
			'decl' => 'void*',
			'check' => 'lua_touserdata(L, {arg})',
			'pop' => '{addr} = lua_touserdata(L, {arg})',
			'push' => 'lua_pushlightuserdata(L, {arg})',
			'convert' => '{addr} = {arg}',
			'format' => "%p",
			'default' => "NULL",
		],
	];

	public static $Axis = [
		["(.+)\\.Axis\\[0\\]\\.Left(.*)",         "\\1Left\\2"],
		["(.+)\\.Axis\\[0\\]\\.Right(.*)",        "\\1Right\\2"],
		["(.+)\\.Axis\\[1\\]\\.Left(.*)",         "\\1Top\\2"],
		["(.+)\\.Axis\\[1\\]\\.Right(.*)",        "\\1Bottom\\2"],
		["(.+)\\.Axis\\[2\\]\\.Left(.*)",         "\\1Front\\2"],
		["(.+)\\.Axis\\[2\\]\\.Right(.*)",        "\\1Back\\2"],
		["Size.Axis\\[0\\]\\.(?:Requested)?(.*)", "\\1Width"],
		["Size.Axis\\[1\\]\\.(?:Requested)?(.*)", "\\1Height"],
		["Size.Axis\\[2\\]\\.(?:Requested)?(.*)", "\\1Depth"],
		["(.+)\\.Axis\\[0\\]",                    "Horizontal\\1"],
		["(.+)\\.Axis\\[1\\]",                    "Vertical\\1"],
		["(.+)\\.Axis\\[2\\]",                    "Depth\\1"],
		["Border\\.Radius\\.(.+)Radius",          "Border\\1Radius"],
		// for structs that have an "Axis[3]" property but no "Size.Axis[3]", to avoid accidentally matching the latter
		["Axis\\[0\\]\\.Left(.*)",         				"Left\\1"],
		["Axis\\[0\\]\\.Right(.*)",        				"Right\\1"],
		["Axis\\[1\\]\\.Left(.*)",         				"Top\\1"],
		["Axis\\[1\\]\\.Right(.*)",        				"Bottom\\1"],
		["Axis\\[2\\]\\.Left(.*)",         				"Front\\1"],
		["Axis\\[2\\]\\.Right(.*)",        				"Back\\1"],
		["Axis\\[0\\]",                    				"Horizontal"],
		["Axis\\[1\\]",                    				"Vertical"],
		["Axis\\[2\\]",                    				"Depth"],
	];
}
