// Generated by XSLT code generator
#include <include/api.h>
#include <geometry.h>


ORCA_API int luaopen_orca_geometry(lua_State *L) {
    luaL_newlib(L, ((luaL_Reg[]) {
        { NULL, NULL }
    }));
    // vec2
    luaopen_orca_vec2(L);
    lua_setfield(L, -2, "Vector2D");
    // vec3
    luaopen_orca_vec3(L);
    lua_setfield(L, -2, "Vector3D");
    // vec4
    luaopen_orca_vec4(L);
    lua_setfield(L, -2, "Vector4D");
    // box2
    luaopen_orca_box2(L);
    lua_setfield(L, -2, "Box2D");
    // box3
    luaopen_orca_box3(L);
    lua_setfield(L, -2, "Box3D");
    // rect
    luaopen_orca_rect(L);
    lua_setfield(L, -2, "Rect");
    // quat
    luaopen_orca_quat(L);
    lua_setfield(L, -2, "Quaternion");
    // mat3
    luaopen_orca_mat3(L);
    lua_setfield(L, -2, "Matrix2D");
    // mat4
    luaopen_orca_mat4(L);
    lua_setfield(L, -2, "Matrix3D");
    // bounds
    luaopen_orca_bounds(L);
    lua_setfield(L, -2, "Bounds");
    // plane3
    luaopen_orca_plane3(L);
    lua_setfield(L, -2, "Plane");
    // sphere3
    luaopen_orca_sphere3(L);
    lua_setfield(L, -2, "Sphere");
    // frustum3
    luaopen_orca_frustum3(L);
    lua_setfield(L, -2, "Frustum");
    // transform2
    luaopen_orca_transform2(L);
    lua_setfield(L, -2, "Transform2D");
    // transform3
    luaopen_orca_transform3(L);
    lua_setfield(L, -2, "Transform3D");
    // triangle3
    luaopen_orca_triangle3(L);
    lua_setfield(L, -2, "Triangle3D");
    // line3
    luaopen_orca_line3(L);
    lua_setfield(L, -2, "Line3D");
    // edges
    luaopen_orca_edges(L);
    lua_setfield(L, -2, "Edges");
    // color
    luaopen_orca_color(L);
    lua_setfield(L, -2, "Color");
    return 1;
}
