-- Generated by tools/blender-export.py. One entry per exported animation clip.
-- Scrub a clip by setting CurrentTime on its player node: time = Duration * (value - Min) / (Max - Min).
return {
	Energy_Flow = { Player = "Animations/Energy_Flow", Duration = 1, Signal = "energy_phase", Min = 0, Max = 6.28319 },
	Gauge_Boost = { Player = "Animations/Gauge_Boost", Duration = 1, Signal = "boost_bar", Min = 0, Max = 2.5 },
	Gauge_Range = { Player = "Animations/Gauge_Range", Duration = 1, Signal = "fuel_level", Min = 0, Max = 1 },
	Gauge_Rev = { Player = "Animations/Gauge_Rev", Duration = 1, Signal = "rpm", Min = 0, Max = 8000 },
	Gauge_Speed = { Player = "Animations/Gauge_Speed", Duration = 1, Signal = "speed_kmh", Min = 0, Max = 320 },
	Gauge_Water = { Player = "Animations/Gauge_Water", Duration = 1, Signal = "water_temp_c", Min = 50, Max = 130 },
}
