Name = "ClusterDemo"
StartupScreen = "ClusterDemo/Screens/Cluster"
WindowWidth = 1920
WindowHeight = 720
ScreenLibrary = { IsExternal = true }
SystemMessages = {
	{ Message="KeyDown", Key="q", Command="return" },
	{ Message="WindowClosed", Command="return" },
	{ Message="RequestReload", Command="window:refresh()" },
}
EnginePlugins = {
	{ Name="orca.UIKit" },
	{ Name="orca.SceneKit" },
}
-- Shader uniforms. tools/blender-export.py reports any that are missing here.
PropertyTypes = {
	{ Name = "ReadoutMin", Category = "Uniform", DataType = "Float" },
	{ Name = "GlyphPitch", Category = "Uniform", DataType = "Float" },
	{ Name = "ReadoutDigits", Category = "Uniform", DataType = "Float" },
	{ Name = "ReadoutMax", Category = "Uniform", DataType = "Float" },
	{ Name = "Heat", Category = "Uniform", DataType = "Float" },
	{ Name = "Spread", Category = "Uniform", DataType = "Float" },
	{ Name = "Roughness", Category = "Uniform", DataType = "Float" },
	{ Name = "Metallic", Category = "Uniform", DataType = "Float" },
	{ Name = "Reflectance", Category = "Uniform", DataType = "Float" },
	{ Name = "HotTint", Category = "Uniform", DataType = "Color" },
	{ Name = "Accent", Category = "Uniform", DataType = "Color" },
	{ Name = "Color0", Category = "Uniform", DataType = "Color" },
	{ Name = "Color1", Category = "Uniform", DataType = "Color" },
	{ Name = "Color2", Category = "Uniform", DataType = "Color" },
	{ Name = "ColorDark", Category = "Uniform", DataType = "Color" },
	{ Name = "ColorLight", Category = "Uniform", DataType = "Color" },
	{ Name = "ColorOff", Category = "Uniform", DataType = "Color" },
	{ Name = "ColorOn", Category = "Uniform", DataType = "Color" },
	{ Name = "EdgeDark", Category = "Uniform", DataType = "Float" },
	{ Name = "FadeIn", Category = "Uniform", DataType = "Float" },
	{ Name = "FadeOut", Category = "Uniform", DataType = "Float" },
	{ Name = "InnerFade", Category = "Uniform", DataType = "Float" },
	{ Name = "Intensity", Category = "Uniform", DataType = "Float" },
	{ Name = "Level", Category = "Uniform", DataType = "Float" },
	{ Name = "Lobes", Category = "Uniform", DataType = "Float" },
	{ Name = "Phase", Category = "Uniform", DataType = "Float" },
	{ Name = "Pos0", Category = "Uniform", DataType = "Float" },
	{ Name = "Pos1", Category = "Uniform", DataType = "Float" },
	{ Name = "Pos2", Category = "Uniform", DataType = "Float" },
	{ Name = "Power", Category = "Uniform", DataType = "Float" },
	{ Name = "RingContrast", Category = "Uniform", DataType = "Float" },
	{ Name = "Rings", Category = "Uniform", DataType = "Float" },
	{ Name = "Sharpness", Category = "Uniform", DataType = "Float" },
	{ Name = "Soft", Category = "Uniform", DataType = "Float" },
	{ Name = "Tail", Category = "Uniform", DataType = "Float" },
	{ Name = "Tint", Category = "Uniform", DataType = "Color" },
	{ Name = "Aspect", Category = "Uniform", DataType = "Float" },
	{ Name = "Bloom", Category = "Uniform", DataType = "Float" },
	{ Name = "Core", Category = "Uniform", DataType = "Float" },
	{ Name = "Count", Category = "Uniform", DataType = "Float" },
	{ Name = "CountU", Category = "Uniform", DataType = "Float" },
	{ Name = "CountV", Category = "Uniform", DataType = "Float" },
	{ Name = "Dashes", Category = "Uniform", DataType = "Float" },
	{ Name = "Density", Category = "Uniform", DataType = "Float" },
	{ Name = "Dim", Category = "Uniform", DataType = "Float" },
	{ Name = "DotSize", Category = "Uniform", DataType = "Float" },
	{ Name = "EnvironmentMap", Category = "Uniform", DataType = "Object", TypeString = "CubeMapTexture" },
	{ Name = "Glow", Category = "Uniform", DataType = "Float" },
	{ Name = "GlowWidth", Category = "Uniform", DataType = "Float" },
	{ Name = "Grooves", Category = "Uniform", DataType = "Float" },
	{ Name = "Sheen", Category = "Uniform", DataType = "Float" },
	{ Name = "SheenPos", Category = "Uniform", DataType = "Float" },
	{ Name = "SheenWidth", Category = "Uniform", DataType = "Float" },
	{ Name = "Spill", Category = "Uniform", DataType = "Float" },
	{ Name = "TopTint", Category = "Uniform", DataType = "Color" },
	{ Name = "Fade", Category = "Uniform", DataType = "Float" },
	{ Name = "Backlight", Category = "Uniform", DataType = "Color" },
	{ Name = "Rim", Category = "Uniform", DataType = "Color" },
	{ Name = "RimWidth", Category = "Uniform", DataType = "Float" },
	{ Name = "Studio", Category = "Uniform", DataType = "Float" },
	{ Name = "Falloff", Category = "Uniform", DataType = "Float" },
}
