<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="text" encoding="UTF-8"/>
    
    <!-- Main template for export C file generation -->
    <xsl:template match="/module">
        <xsl:variable name="moduleName" select="@name"/>
        <xsl:variable name="namespace" select="@namespace"/>
        
        <xsl:text>// Generated by XSLT code generator&#10;</xsl:text>
        <xsl:text>#include &lt;include/api.h&gt;&#10;</xsl:text>
        <xsl:text>#include &lt;</xsl:text>
        <xsl:value-of select="$moduleName"/>
        <xsl:text>.h&gt;&#10;&#10;</xsl:text>
        
        <!-- Generate Lua binding functions for each method -->
        <xsl:apply-templates select="struct/method|interface/method" mode="lua-binding"/>
        
        <!-- Generate luaopen function -->
        <xsl:text>&#10;ORCA_API int luaopen_</xsl:text>
        <xsl:value-of select="$namespace"/>
        <xsl:text>_</xsl:text>
        <xsl:value-of select="$moduleName"/>
        <xsl:text>(lua_State *L) {&#10;</xsl:text>
        
        <xsl:text>    luaL_newlib(L, ((luaL_Reg[]) {&#10;</xsl:text>
        
        <!-- Register global functions -->
        <xsl:apply-templates select="function" mode="register"/>
        
        <xsl:text>        { NULL, NULL }&#10;</xsl:text>
        <xsl:text>    }));&#10;</xsl:text>
        
        <!-- Call on-luaopen hook if specified -->
        <xsl:if test="@on-luaopen">
            <xsl:text>    void </xsl:text>
            <xsl:value-of select="@on-luaopen"/>
            <xsl:text>(lua_State *L);&#10;</xsl:text>
            <xsl:text>    </xsl:text>
            <xsl:value-of select="@on-luaopen"/>
            <xsl:text>(L);&#10;</xsl:text>
        </xsl:if>
        
        <!-- Register structs and interfaces -->
        <xsl:apply-templates select="struct|interface" mode="register-type"/>
        
        <xsl:text>    return 1;&#10;</xsl:text>
        <xsl:text>}&#10;</xsl:text>
    </xsl:template>
    
    <!-- Generate Lua binding for a method -->
    <xsl:template match="method" mode="lua-binding">
        <xsl:if test="@lua = 'true'">
            <xsl:text>static int lua_</xsl:text>
            <xsl:value-of select="../@name"/>
            <xsl:text>_</xsl:text>
            <xsl:value-of select="@name"/>
            <xsl:text>(lua_State *L) {&#10;</xsl:text>
            
            <!-- Get self pointer -->
            <xsl:text>    </xsl:text>
            <xsl:value-of select="../@name"/>
            <xsl:text>_t* self = lua_to</xsl:text>
            <xsl:value-of select="../@name"/>
            <xsl:text>(L, 1);&#10;</xsl:text>
            
            <!-- Call the actual function -->
            <xsl:text>    </xsl:text>
            <xsl:if test="returns">
                <xsl:value-of select="returns/@type"/>
                <xsl:text> result = </xsl:text>
            </xsl:if>
            <xsl:value-of select="../@name"/>
            <xsl:text>_</xsl:text>
            <xsl:value-of select="@name"/>
            <xsl:text>(self);&#10;</xsl:text>
            
            <!-- Return value if applicable -->
            <xsl:if test="returns">
                <xsl:text>    lua_push</xsl:text>
                <xsl:value-of select="returns/@type"/>
                <xsl:text>(L, result);&#10;</xsl:text>
                <xsl:text>    return 1;&#10;</xsl:text>
            </xsl:if>
            <xsl:if test="not(returns)">
                <xsl:text>    return 0;&#10;</xsl:text>
            </xsl:if>
            
            <xsl:text>}&#10;&#10;</xsl:text>
        </xsl:if>
    </xsl:template>
    
    <!-- Register a function in the Lua library -->
    <xsl:template match="function" mode="register">
        <xsl:text>        { "</xsl:text>
        <xsl:choose>
            <xsl:when test="@export">
                <xsl:value-of select="@export"/>
            </xsl:when>
            <xsl:otherwise>
                <xsl:value-of select="@name"/>
            </xsl:otherwise>
        </xsl:choose>
        <xsl:text>", lua_</xsl:text>
        <xsl:value-of select="@name"/>
        <xsl:text> },&#10;</xsl:text>
    </xsl:template>
    
    <!-- Register a struct/interface type -->
    <xsl:template match="struct|interface" mode="register-type">
        <xsl:variable name="typeName" select="@name"/>
        <xsl:variable name="exportName">
            <xsl:choose>
                <xsl:when test="@export">
                    <xsl:value-of select="@export"/>
                </xsl:when>
                <xsl:otherwise>
                    <xsl:value-of select="@name"/>
                </xsl:otherwise>
            </xsl:choose>
        </xsl:variable>
        
        <xsl:text>    // </xsl:text>
        <xsl:value-of select="$typeName"/>
        <xsl:text>&#10;</xsl:text>
        <xsl:text>    luaopen_</xsl:text>
        <xsl:value-of select="/module/@namespace"/>
        <xsl:text>_</xsl:text>
        <xsl:value-of select="$typeName"/>
        <xsl:text>(L);&#10;</xsl:text>
        <xsl:text>    lua_setfield(L, -2, "</xsl:text>
        <xsl:value-of select="$exportName"/>
        <xsl:text>");&#10;</xsl:text>
    </xsl:template>
    
</xsl:stylesheet>
