-- Generated by Tools/export_workshop_camera.lua; regenerate, do not edit.
return {
    source_path = "Book/Rooms/workshop.blks",
    source_width = 1536,
    source_height = 1024,
    native_scene_path = "Book/Scenes/WorkshopCamera.xml",
    default_camera = "workshop-floor",
    cameras = {
        ["workshop-floor"] = {
            name = "workshop-floor", fov = 70, near = 0.1, far = 100,
            pos = {-5.4, 0.8, 4.2}, look = {0.85, 7.35, 1.05}, rotation = {43.1022631367, -63.2518958371, 0},
        },
    },
    anchors = {
        ["CLOCK-FACE"] = {-5.76, 4.8, 3.6},
        ["KEY-HOOK"] = {-5.76, 1.8, 3.2},
        ["LOFT-LADDER"] = {-5.76, 8, 2.4},
        ["OIL-CAN"] = {-4.7, 3.8, 0.2},
        ["PET-DOOR"] = {1, 9.88, 0},
        ["WORKBENCH"] = {-4.7, 3.8, 0.8},
    },
}
