-- Generated by Tools/export_workshop_camera.lua; regenerate, do not edit.
return {
    source_path = "Book/Images/prototype/workshop.blks",
    source_width = 1536,
    source_height = 1024,
    native_scene_path = "Book/Scenes/WorkshopCamera.xml",
    camera = {
        name = "WorkshopEstablishing",
        pos = {-0.8, 1.45, -3.2},
        look = {-0.4, 1.2, -7.35},
        fov = 60,
    },
    native = {
        rotation = {-3.43152224968, -5.50547785798, 0},
        fov = 60,
        fov_type = "Yfov", projection_type = "Perspective",
        z_positive = false, z_near = 0.1, z_far = 100,
    },
    anchors = {
        ["hook"] = {0, 1.7, -8.84},
        ["oil"] = {1.9, 0.14, -7.4},
        ["door"] = {-3.9, 0.3, -8.83},
        ["clock"] = {1.62, 2.25, -8.83},
    },
}
