// Generated by codegen utility
#include <include/api.h>

#include "renderer.h"

// fontface
extern void luaX_pushfontface(lua_State *L, struct fontface const* value);
extern struct fontface* luaX_checkfontface(lua_State *L, int index);
// timeline
extern void luaX_pushtimeline(lua_State *L, struct timeline const* value);
extern struct timeline* luaX_checktimeline(lua_State *L, int index);
// shader
extern void luaX_pushshader(lua_State *L, struct shader const* value);
extern struct shader* luaX_checkshader(lua_State *L, int index);
// model
extern void luaX_pushmodel(lua_State *L, struct model const* value);
extern struct model* luaX_checkmodel(lua_State *L, int index);
// shape
extern void luaX_pushshape(lua_State *L, struct shape const* value);
extern struct shape* luaX_checkshape(lua_State *L, int index);
// ViewDef
extern void luaX_pushViewDef(lua_State *L, struct ViewDef const* value);
extern struct ViewDef* luaX_checkViewDef(lua_State *L, int index);
// lua_State
extern void luaX_pushlua_State(lua_State *L, struct lua_State const* value);
extern struct lua_State* luaX_checklua_State(lua_State *L, int index);

static const char *_BlendMode[] = {"AlphaAutomatic","Opaque","Alpha","Additive","PremultipliedAlpha","MixedAlpha",NULL};
const char *BlendModeToString(enum BlendMode value) {
	assert(value >= 0 && value < 6);
	return _BlendMode[value];
}
enum BlendMode luaX_checkBlendMode(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _BlendMode);
}
void luaX_pushBlendMode(lua_State *L, enum BlendMode value) {
	assert(value >= 0 && value < 6);
	lua_pushstring(L, _BlendMode[value]);
}
static const char *_CompareFunc[] = {"Never","Always","Less","LessOrEqual","Greater","GreaterOrEqual","Equal","NotEqual","Disabled",NULL};
const char *CompareFuncToString(enum CompareFunc value) {
	assert(value >= 0 && value < 9);
	return _CompareFunc[value];
}
enum CompareFunc luaX_checkCompareFunc(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _CompareFunc);
}
void luaX_pushCompareFunc(lua_State *L, enum CompareFunc value) {
	assert(value >= 0 && value < 9);
	lua_pushstring(L, _CompareFunc[value]);
}
static const char *_TextureFilter[] = {"Nearest","Linear","Trilinear",NULL};
const char *TextureFilterToString(enum TextureFilter value) {
	assert(value >= 0 && value < 3);
	return _TextureFilter[value];
}
enum TextureFilter luaX_checkTextureFilter(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _TextureFilter);
}
void luaX_pushTextureFilter(lua_State *L, enum TextureFilter value) {
	assert(value >= 0 && value < 3);
	lua_pushstring(L, _TextureFilter[value]);
}
static const char *_TextureWrap[] = {"Clamp","Repeat","Base",NULL};
const char *TextureWrapToString(enum TextureWrap value) {
	assert(value >= 0 && value < 3);
	return _TextureWrap[value];
}
enum TextureWrap luaX_checkTextureWrap(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _TextureWrap);
}
void luaX_pushTextureWrap(lua_State *L, enum TextureWrap value) {
	assert(value >= 0 && value < 3);
	lua_pushstring(L, _TextureWrap[value]);
}
static const char *_TextureFormat[] = {"Automatic","Rgba8","Rgb8","Alpha8","DepthComponent","DepthStencil",NULL};
const char *TextureFormatToString(enum TextureFormat value) {
	assert(value >= 0 && value < 6);
	return _TextureFormat[value];
}
enum TextureFormat luaX_checkTextureFormat(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _TextureFormat);
}
void luaX_pushTextureFormat(lua_State *L, enum TextureFormat value) {
	assert(value >= 0 && value < 6);
	lua_pushstring(L, _TextureFormat[value]);
}
static const char *_MipmapMode[] = {"Base","Nearest","Linear","Trilinear",NULL};
const char *MipmapModeToString(enum MipmapMode value) {
	assert(value >= 0 && value < 4);
	return _MipmapMode[value];
}
enum MipmapMode luaX_checkMipmapMode(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _MipmapMode);
}
void luaX_pushMipmapMode(lua_State *L, enum MipmapMode value) {
	assert(value >= 0 && value < 4);
	lua_pushstring(L, _MipmapMode[value]);
}
static const char *_AnisotropyType[] = {"None","X2","X4","X8","X16",NULL};
const char *AnisotropyTypeToString(enum AnisotropyType value) {
	assert(value >= 0 && value < 5);
	return _AnisotropyType[value];
}
enum AnisotropyType luaX_checkAnisotropyType(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _AnisotropyType);
}
void luaX_pushAnisotropyType(lua_State *L, enum AnisotropyType value) {
	assert(value >= 0 && value < 5);
	lua_pushstring(L, _AnisotropyType[value]);
}
static const char *_ImageFormat[] = {"Png","Jpeg","Svg","Astc","Pvrtc",NULL};
const char *ImageFormatToString(enum ImageFormat value) {
	assert(value >= 0 && value < 5);
	return _ImageFormat[value];
}
enum ImageFormat luaX_checkImageFormat(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _ImageFormat);
}
void luaX_pushImageFormat(lua_State *L, enum ImageFormat value) {
	assert(value >= 0 && value < 5);
	lua_pushstring(L, _ImageFormat[value]);
}
static const char *_AstcFormat[] = {"UnormBlock4x4","UnormBlock5x4","UnormBlock5x5","UnormBlock6x5","UnormBlock6x6","UnormBlock8x5","UnormBlock8x6","UnormBlock8x8","UnormBlock10x5","UnormBlock10x6","UnormBlock10x8","UnormBlock10x10","UnormBlock12x10","UnormBlock12x12","SrgbBlock4x4","SrgbBlock5x4","SrgbBlock5x5","SrgbBlock6x5","SrgbBlock6x6","SrgbBlock8x5","SrgbBlock8x6","SrgbBlock8x8","SrgbBlock10x5","SrgbBlock10x6","SrgbBlock10x8","SrgbBlock10x10","SrgbBlock12x10","SrgbBlock12x12",NULL};
const char *AstcFormatToString(enum AstcFormat value) {
	assert(value >= 0 && value < 28);
	return _AstcFormat[value];
}
enum AstcFormat luaX_checkAstcFormat(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _AstcFormat);
}
void luaX_pushAstcFormat(lua_State *L, enum AstcFormat value) {
	assert(value >= 0 && value < 28);
	lua_pushstring(L, _AstcFormat[value]);
}
static const char *_AtcCompressionScheme[] = {"ExplicitAlpha","InterpolatedAlpha","Rgb",NULL};
const char *AtcCompressionSchemeToString(enum AtcCompressionScheme value) {
	assert(value >= 0 && value < 3);
	return _AtcCompressionScheme[value];
}
enum AtcCompressionScheme luaX_checkAtcCompressionScheme(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _AtcCompressionScheme);
}
void luaX_pushAtcCompressionScheme(lua_State *L, enum AtcCompressionScheme value) {
	assert(value >= 0 && value < 3);
	lua_pushstring(L, _AtcCompressionScheme[value]);
}
static const char *_AstcCompressionSpeed[] = {"VeryFast","Fast","Medium","Thorough","Exhaustive",NULL};
const char *AstcCompressionSpeedToString(enum AstcCompressionSpeed value) {
	assert(value >= 0 && value < 5);
	return _AstcCompressionSpeed[value];
}
enum AstcCompressionSpeed luaX_checkAstcCompressionSpeed(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _AstcCompressionSpeed);
}
void luaX_pushAstcCompressionSpeed(lua_State *L, enum AstcCompressionSpeed value) {
	assert(value >= 0 && value < 5);
	lua_pushstring(L, _AstcCompressionSpeed[value]);
}
static const char *_RawColorByteFormat[] = {"Rgba8","Rgb8","Bgra8","Rgba16f","Rgb10a2","R11g11b10f","Rgba32f",NULL};
const char *RawColorByteFormatToString(enum RawColorByteFormat value) {
	assert(value >= 0 && value < 7);
	return _RawColorByteFormat[value];
}
enum RawColorByteFormat luaX_checkRawColorByteFormat(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _RawColorByteFormat);
}
void luaX_pushRawColorByteFormat(lua_State *L, enum RawColorByteFormat value) {
	assert(value >= 0 && value < 7);
	lua_pushstring(L, _RawColorByteFormat[value]);
}
static const char *_FilePngCompressionLevel[] = {"None","Fast","Normal","Maximum","ProjectDefault",NULL};
const char *FilePngCompressionLevelToString(enum FilePngCompressionLevel value) {
	assert(value >= 0 && value < 5);
	return _FilePngCompressionLevel[value];
}
enum FilePngCompressionLevel luaX_checkFilePngCompressionLevel(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _FilePngCompressionLevel);
}
void luaX_pushFilePngCompressionLevel(lua_State *L, enum FilePngCompressionLevel value) {
	assert(value >= 0 && value < 5);
	lua_pushstring(L, _FilePngCompressionLevel[value]);
}
static const char *_SpansionCompressionScheme[] = {"None","Standard","Enhanced",NULL};
const char *SpansionCompressionSchemeToString(enum SpansionCompressionScheme value) {
	assert(value >= 0 && value < 3);
	return _SpansionCompressionScheme[value];
}
enum SpansionCompressionScheme luaX_checkSpansionCompressionScheme(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _SpansionCompressionScheme);
}
void luaX_pushSpansionCompressionScheme(lua_State *L, enum SpansionCompressionScheme value) {
	assert(value >= 0 && value < 3);
	lua_pushstring(L, _SpansionCompressionScheme[value]);
}
static const char *_ImageType[] = {"Normal","Mask",NULL};
const char *ImageTypeToString(enum ImageType value) {
	assert(value >= 0 && value < 2);
	return _ImageType[value];
}
enum ImageType luaX_checkImageType(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _ImageType);
}
void luaX_pushImageType(lua_State *L, enum ImageType value) {
	assert(value >= 0 && value < 2);
	lua_pushstring(L, _ImageType[value]);
}
static const char *_RenderTargetType[] = {"Color","Depth","Stencil","DepthStencil","Normal","Specular","Emission",NULL};
const char *RenderTargetTypeToString(enum RenderTargetType value) {
	assert(value >= 0 && value < 7);
	return _RenderTargetType[value];
}
enum RenderTargetType luaX_checkRenderTargetType(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _RenderTargetType);
}
void luaX_pushRenderTargetType(lua_State *L, enum RenderTargetType value) {
	assert(value >= 0 && value < 7);
	lua_pushstring(L, _RenderTargetType[value]);
}
static const char *_RenderTargetTextureAttachment[] = {"None","Color0","Color1","Color2","Color3","Depth","Stencil","DepthStencil",NULL};
const char *RenderTargetTextureAttachmentToString(enum RenderTargetTextureAttachment value) {
	assert(value >= 0 && value < 8);
	return _RenderTargetTextureAttachment[value];
}
enum RenderTargetTextureAttachment luaX_checkRenderTargetTextureAttachment(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _RenderTargetTextureAttachment);
}
void luaX_pushRenderTargetTextureAttachment(lua_State *L, enum RenderTargetTextureAttachment value) {
	assert(value >= 0 && value < 8);
	lua_pushstring(L, _RenderTargetTextureAttachment[value]);
}
static const char *_FloatPrecision[] = {"Unset","Low","Medium","High",NULL};
const char *FloatPrecisionToString(enum FloatPrecision value) {
	assert(value >= 0 && value < 4);
	return _FloatPrecision[value];
}
enum FloatPrecision luaX_checkFloatPrecision(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _FloatPrecision);
}
void luaX_pushFloatPrecision(lua_State *L, enum FloatPrecision value) {
	assert(value >= 0 && value < 4);
	lua_pushstring(L, _FloatPrecision[value]);
}
static const char *_Shading[] = {"Unlit","Phong","Standard",NULL};
const char *ShadingToString(enum Shading value) {
	assert(value >= 0 && value < 3);
	return _Shading[value];
}
enum Shading luaX_checkShading(lua_State *L, int idx) {
	return luaL_checkoption(L, idx, NULL, _Shading);
}
void luaX_pushShading(lua_State *L, enum Shading value) {
	assert(value >= 0 && value < 3);
	lua_pushstring(L, _Shading[value]);
}
void luaX_pushwindow(lua_State *L, struct window const* data);
struct window* luaX_checkwindow(lua_State *L, int idx);
int f_window___index(lua_State *L) {
	struct window* self = luaX_checkwindow(L, 1);
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	}
	return luaL_error(L, "Unknown field in window(%p): %s", self, luaL_checkstring(L, 2));
}
int luaopen_orca_window(lua_State *L) {
	luaL_newmetatable(L, "Window");
	luaL_setfuncs(L, ((luaL_Reg[]) {
		{ "__index", f_window___index },
		{ NULL, NULL },
	}), 0);
	return 1;
}
void luaX_pushRenderScreenEventArgs(lua_State *L, struct RenderScreenEventArgs const* data) {
	if (data == NULL) { lua_pushnil(L); return; }
	struct RenderScreenEventArgs* self = lua_newuserdata(L, sizeof(struct RenderScreenEventArgs));
	luaL_setmetatable(L, "RenderScreenEventArgs");
	memcpy(self, data, sizeof(struct RenderScreenEventArgs));
}
struct RenderScreenEventArgs* luaX_checkRenderScreenEventArgs(lua_State *L, int idx) {
	return luaL_checkudata(L, idx, "RenderScreenEventArgs");
}
static int f_new_RenderScreenEventArgs(lua_State *L) {
	struct RenderScreenEventArgs* self = lua_newuserdata(L, sizeof(struct RenderScreenEventArgs));
	luaL_setmetatable(L, "RenderScreenEventArgs");
	memset(self, 0, sizeof(struct RenderScreenEventArgs));
	if (lua_gettop(L) == 1) return 1;
	if (lua_istable(L, 1)) {
		lua_pop(L, (lua_getfield(L, 1, "width"), self->width = luaL_checknumber(L, -1), 1));
		lua_pop(L, (lua_getfield(L, 1, "height"), self->height = luaL_checknumber(L, -1), 1));
		lua_pop(L, (lua_getfield(L, 1, "stereo"), self->stereo = luaL_checknumber(L, -1), 1));
		lua_pop(L, (lua_getfield(L, 1, "angle"), self->angle = luaL_checknumber(L, -1), 1));
		lua_pop(L, (lua_getfield(L, 1, "target"), self->target = luaX_checkTexture(L, -1), 1));
		lua_pop(L, (lua_getfield(L, 1, "only_paint"), self->only_paint = lua_toboolean(L, -1), 1));
	} else {
		self->width = luaL_checknumber(L, 1);
		self->height = luaL_checknumber(L, 2);
		self->stereo = luaL_checknumber(L, 3);
		self->angle = luaL_checknumber(L, 4);
		self->target = luaX_checkTexture(L, 5);
		self->only_paint = lua_toboolean(L, 6);
	}
	return 1;
}
int f_RenderScreenEventArgs___index(lua_State *L) {
	struct RenderScreenEventArgs* self = luaX_checkRenderScreenEventArgs(L, 1);
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	case 0x95876e1f: lua_pushnumber(L, self->width); return 1; // width
	case 0xd5bdbb42: lua_pushnumber(L, self->height); return 1; // height
	case 0xcc87a64d: lua_pushnumber(L, self->stereo); return 1; // stereo
	case 0xad544418: lua_pushnumber(L, self->angle); return 1; // angle
	case 0x32608848: luaX_pushTexture(L, self->target); return 1; // target
	case 0xc577ec54: lua_pushboolean(L, self->only_paint); return 1; // only_paint
	}
	return luaL_error(L, "Unknown field in RenderScreenEventArgs(%p): %s", self, luaL_checkstring(L, 2));
}
int f_RenderScreenEventArgs___newindex(lua_State *L) {
	struct RenderScreenEventArgs* self = luaX_checkRenderScreenEventArgs(L, 1);
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	case 0x95876e1f: self->width = luaL_checknumber(L, 3); return 0; // width
	case 0xd5bdbb42: self->height = luaL_checknumber(L, 3); return 0; // height
	case 0xcc87a64d: self->stereo = luaL_checknumber(L, 3); return 0; // stereo
	case 0xad544418: self->angle = luaL_checknumber(L, 3); return 0; // angle
	case 0x32608848: self->target = luaX_checkTexture(L, 3); return 0; // target
	case 0xc577ec54: self->only_paint = lua_toboolean(L, 3); return 0; // only_paint
	}
	return luaL_error(L, "Unknown field in RenderScreenEventArgs(%p): %s", self, luaL_checkstring(L, 2));
}
extern bool_t f_convert_string(lua_State*, struct PropertyType const*, char const*, bool_t);
static int f_RenderScreenEventArgs___fromstring(lua_State *L) {
	unsigned width;
	unsigned height;
	float stereo;
	float angle;
	fixedString_t target;
	fixedString_t only_paint;
	struct RenderScreenEventArgs self = {0};
	switch (sscanf(luaL_checkstring(L, 1), "%u %u %f %f %s %s", &width, &height, &stereo, &angle, target, only_paint)) {
	case 6: 
		self.width = width;
		self.height = height;
		self.stereo = stereo;
		self.angle = angle;
		lua_pop(L, (f_convert_string(L, &(struct PropertyType) { .DataType = kDataTypeObject, .TypeString = "Texture" }, target, TRUE), self.target = luaX_checkTexture(L, -1), 1));;
		self.only_paint = !strcmp(only_paint, "true");
		return (luaX_pushRenderScreenEventArgs(L, &self), 1);
	default:
		return luaL_error(L, "Invalid format for RenderScreenEventArgs: %s", luaL_checkstring(L, 1));
	}
}
static int f_RenderScreenEventArgs___call(lua_State *L) {
	return ((void)lua_remove(L, 1), f_new_RenderScreenEventArgs(L));  // remove RenderScreenEventArgs from stack and call constructor
}
int luaopen_orca_RenderScreenEventArgs(lua_State *L) {
	luaL_newmetatable(L, "RenderScreenEventArgs");
	luaL_setfuncs(L, ((luaL_Reg[]) {
		{ "new", f_new_RenderScreenEventArgs },
		{ "fromstring", f_RenderScreenEventArgs___fromstring },
		{ "__newindex", f_RenderScreenEventArgs___newindex },
		{ "__index", f_RenderScreenEventArgs___index },
		{ NULL, NULL },
	}), 0);
	// Make RenderScreenEventArgs creatable via constructor-like syntax
	lua_newtable(L);
	lua_pushcfunction(L, f_RenderScreenEventArgs___call);
	lua_setfield(L, -2, "__call");
	lua_setmetatable(L, -2);
	return 1;
}
void luaX_pushRenderEventArgs(lua_State *L, struct RenderEventArgs const* data) {
	if (data == NULL) { lua_pushnil(L); return; }
	struct RenderEventArgs* self = lua_newuserdata(L, sizeof(struct RenderEventArgs));
	luaL_setmetatable(L, "RenderEventArgs");
	memcpy(self, data, sizeof(struct RenderEventArgs));
}
struct RenderEventArgs* luaX_checkRenderEventArgs(lua_State *L, int idx) {
	return luaL_checkudata(L, idx, "RenderEventArgs");
}
static int f_new_RenderEventArgs(lua_State *L) {
	struct RenderEventArgs* self = lua_newuserdata(L, sizeof(struct RenderEventArgs));
	luaL_setmetatable(L, "RenderEventArgs");
	memset(self, 0, sizeof(struct RenderEventArgs));
	if (lua_gettop(L) == 1) return 1;
	if (lua_istable(L, 1)) {
		lua_pop(L, (lua_getfield(L, 1, "ViewDef"), self->ViewDef = NULL, 1));
	} else {
		self->ViewDef = NULL;
	}
	return 1;
}
int f_RenderEventArgs___index(lua_State *L) {
	struct RenderEventArgs* self = luaX_checkRenderEventArgs(L, 1);
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	case 0xce9ab61f: luaX_pushViewDef(L, self->ViewDef); return 1; // ViewDef
	}
	return luaL_error(L, "Unknown field in RenderEventArgs(%p): %s", self, luaL_checkstring(L, 2));
}
int f_RenderEventArgs___newindex(lua_State *L) {
	struct RenderEventArgs* self = luaX_checkRenderEventArgs(L, 1);
	switch(fnv1a32(luaL_checkstring(L, 2))) {
	case 0xce9ab61f: self->ViewDef = NULL; return 0; // ViewDef
	}
	return luaL_error(L, "Unknown field in RenderEventArgs(%p): %s", self, luaL_checkstring(L, 2));
}
extern bool_t f_convert_string(lua_State*, struct PropertyType const*, char const*, bool_t);
static int f_RenderEventArgs___fromstring(lua_State *L) {
	fixedString_t ViewDef;
	struct RenderEventArgs self = {0};
	switch (sscanf(luaL_checkstring(L, 1), "%s", ViewDef)) {
	case 1: 
		;
		return (luaX_pushRenderEventArgs(L, &self), 1);
	default:
		return luaL_error(L, "Invalid format for RenderEventArgs: %s", luaL_checkstring(L, 1));
	}
}
static int f_RenderEventArgs___call(lua_State *L) {
	return ((void)lua_remove(L, 1), f_new_RenderEventArgs(L));  // remove RenderEventArgs from stack and call constructor
}
int luaopen_orca_RenderEventArgs(lua_State *L) {
	luaL_newmetatable(L, "RenderEventArgs");
	luaL_setfuncs(L, ((luaL_Reg[]) {
		{ "new", f_new_RenderEventArgs },
		{ "fromstring", f_RenderEventArgs___fromstring },
		{ "__newindex", f_RenderEventArgs___newindex },
		{ "__index", f_RenderEventArgs___index },
		{ NULL, NULL },
	}), 0);
	// Make RenderEventArgs creatable via constructor-like syntax
	lua_newtable(L);
	lua_pushcfunction(L, f_RenderEventArgs___call);
	lua_setfield(L, -2, "__call");
	lua_setmetatable(L, -2);
	return 1;
}
#define DECL(SHORT, CLASS, NAME, FIELD, TYPE,...) { .Name=#CLASS"."#NAME, .Category=#CLASS, .ShortIdentifier=SHORT, .FullIdentifier=ID_##CLASS##_##NAME, .Offset=offsetof(struct CLASS, FIELD), .DataSize=sizeof(((struct CLASS *)NULL)->FIELD), .DataType=TYPE, ##__VA_ARGS__ }
#define ARRAY_DECL(SHORT, CLASS, NAME, FIELD, TYPE,...) { .Name=#CLASS"."#NAME, .Category=#CLASS, .ShortIdentifier=SHORT, .FullIdentifier=ID_##CLASS##_##NAME, .Offset=offsetof(struct CLASS, FIELD), .DataSize=sizeof(*((struct CLASS *)NULL)->FIELD), .DataType=TYPE, .IsArray=TRUE, ##__VA_ARGS__ }

typedef struct RenderScreenEventArgs* RenderScreenEventPtr;
typedef struct RenderEventArgs* RenderEventPtr;

static struct PropertyType const TextureProperties[kTextureNumProperties] = {
	DECL(0x47bdcfab, Texture, MinificationFilter, MinificationFilter, kDataTypeEnum, .TypeString = "Nearest,Linear,Trilinear"), // Texture.MinificationFilter
	DECL(0xf5ff802c, Texture, MagnificationFilter, MagnificationFilter, kDataTypeEnum, .TypeString = "Nearest,Linear,Trilinear"), // Texture.MagnificationFilter
	DECL(0xc2114a32, Texture, WrapMode, WrapMode, kDataTypeEnum, .TypeString = "Clamp,Repeat,Base"), // Texture.WrapMode
	DECL(0xffb0ff72, Texture, Format, Format, kDataTypeEnum, .TypeString = "Automatic,Rgba8,Rgb8,Alpha8,DepthComponent,DepthStencil"), // Texture.Format
	DECL(0x28528e11, Texture, Scale, Scale, kDataTypeInt), // Texture.Scale
	DECL(0xb3ad7612, Texture, MipmapMode, MipmapMode, kDataTypeEnum, .TypeString = "Base,Nearest,Linear,Trilinear"), // Texture.MipmapMode
	DECL(0x78736795, Texture, AnisotropyType, AnisotropyType, kDataTypeEnum, .TypeString = "None,X2,X4,X8,X16"), // Texture.AnisotropyType
	DECL(0x3b42dfbf, Texture, Width, Width, kDataTypeInt), // Texture.Width
	DECL(0x1bd13562, Texture, Height, Height, kDataTypeInt), // Texture.Height
};
static struct Texture TextureDefaults = {
};
LRESULT TextureProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
	}
	return FALSE;
}
void luaX_pushTexture(lua_State *L, struct Texture const* Texture) {
	luaX_pushObject(L, CMP_GetObject(Texture));
}
struct Texture* luaX_checkTexture(lua_State *L, int idx) {
	return GetTexture(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _Texture = {
	.ClassName = "Texture",
	.DefaultName = "Texture",
	.ContentType = "Texture",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_Texture,
	.ClassSize = sizeof(struct Texture),
	.Properties = TextureProperties,
	.ObjProc = TextureProc,
	.Defaults = &TextureDefaults,
	.NumProperties = kTextureNumProperties,
};

LRESULT Image_Start(struct Object*, struct Image*, wParam_t, StartEventPtr);

static struct PropertyType const ImageProperties[kImageNumProperties] = {
	DECL(0x61e2a3f8, Image, Source, Source, kDataTypeFixed), // Image.Source
	DECL(0xa3c8af46, Image, PremultiplyAlpha, PremultiplyAlpha, kDataTypeBool), // Image.PremultiplyAlpha
	DECL(0xd155d06d, Image, Type, Type, kDataTypeEnum, .TypeString = "Normal,Mask"), // Image.Type
	DECL(0xdb9ccf58, Image, HasMipmaps, HasMipmaps, kDataTypeBool), // Image.HasMipmaps
	DECL(0xa6478e7c, Image, Size, Size, kDataTypeFixed), // Image.Size
	DECL(0x7588b4d5, Image, BitDepth, BitDepth, kDataTypeInt), // Image.BitDepth
	DECL(0x94ab250b, Image, FileHasTransparency, FileHasTransparency, kDataTypeBool), // Image.FileHasTransparency
	DECL(0xb5f815c3, Image, FileHasICCProfile, FileHasICCProfile, kDataTypeBool), // Image.FileHasICCProfile
	DECL(0x86ff7dab, Image, TargetFormat, TargetFormat, kDataTypeEnum, .TypeString = "Png,Jpeg,Svg,Astc,Pvrtc"), // Image.TargetFormat
	DECL(0x79fe08b6, Image, AtcCompressionScheme, AtcCompressionScheme, kDataTypeEnum, .TypeString = "ExplicitAlpha,InterpolatedAlpha,Rgb"), // Image.AtcCompressionScheme
	DECL(0x18e754ba, Image, PvrtcBitDepth, PvrtcBitDepth, kDataTypeInt), // Image.PvrtcBitDepth
	DECL(0x022a53d7, Image, PvrtcQuality, PvrtcQuality, kDataTypeInt), // Image.PvrtcQuality
	DECL(0x55e09913, Image, PvrtcCompressionScheme, PvrtcCompressionScheme, kDataTypeInt), // Image.PvrtcCompressionScheme
	DECL(0x8bceff48, Image, AstcBlockSize, AstcBlockSize, kDataTypeEnum, .TypeString = "UnormBlock4x4,UnormBlock5x4,UnormBlock5x5,UnormBlock6x5,UnormBlock6x6,UnormBlock8x5,UnormBlock8x6,UnormBlock8x8,UnormBlock10x5,UnormBlock10x6,UnormBlock10x8,UnormBlock10x10,UnormBlock12x10,UnormBlock12x12,SrgbBlock4x4,SrgbBlock5x4,SrgbBlock5x5,SrgbBlock6x5,SrgbBlock6x6,SrgbBlock8x5,SrgbBlock8x6,SrgbBlock8x8,SrgbBlock10x5,SrgbBlock10x6,SrgbBlock10x8,SrgbBlock10x10,SrgbBlock12x10,SrgbBlock12x12"), // Image.AstcBlockSize
	DECL(0x52120f05, Image, AstcCompressionSpeed, AstcCompressionSpeed, kDataTypeEnum, .TypeString = "VeryFast,Fast,Medium,Thorough,Exhaustive"), // Image.AstcCompressionSpeed
	DECL(0x0ccdd5f0, Image, AstcIsSRGB, AstcIsSRGB, kDataTypeBool), // Image.AstcIsSRGB
	DECL(0xfe76304d, Image, RawColorByteFormat, RawColorByteFormat, kDataTypeEnum, .TypeString = "Rgba8,Rgb8,Bgra8,Rgba16f,Rgb10a2,R11g11b10f,Rgba32f"), // Image.RawColorByteFormat
	DECL(0x66001361, Image, SpansionCompressionScheme, SpansionCompressionScheme, kDataTypeEnum, .TypeString = "None,Standard,Enhanced"), // Image.SpansionCompressionScheme
	DECL(0x28b08476, Image, FilePngCompressionLevel, FilePngCompressionLevel, kDataTypeEnum, .TypeString = "None,Fast,Normal,Maximum,ProjectDefault"), // Image.FilePngCompressionLevel
	DECL(0xd96ef887, Image, Etc2Effort, Etc2Effort, kDataTypeInt), // Image.Etc2Effort
	DECL(0x84841aff, Image, FileExportSourceTexture, FileExportSourceTexture, kDataTypeBool), // Image.FileExportSourceTexture
	DECL(0xc1e7dbf8, Image, FileExportAlways, FileExportAlways, kDataTypeBool), // Image.FileExportAlways
	DECL(0x1c849134, Image, FileExportEmptyWhenFileIsMissing, FileExportEmptyWhenFileIsMissing, kDataTypeBool), // Image.FileExportEmptyWhenFileIsMissing
	DECL(0x85202b31, Image, FileExportSourceImage, FileExportSourceImage, kDataTypeFixed), // Image.FileExportSourceImage
};
static struct Image ImageDefaults = {
};
LRESULT ImageProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventStart: return Image_Start(object, cmp, wparm, lparm); // Start
	}
	return FALSE;
}
void luaX_pushImage(lua_State *L, struct Image const* Image) {
	luaX_pushObject(L, CMP_GetObject(Image));
}
struct Image* luaX_checkImage(lua_State *L, int idx) {
	return GetImage(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _Image = {
	.ClassName = "Image",
	.DefaultName = "Image",
	.ContentType = "Image",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_Image,
	.ClassSize = sizeof(struct Image),
	.Properties = ImageProperties,
	.ObjProc = ImageProc,
	.Defaults = &ImageDefaults,
	.NumProperties = kImageNumProperties,
};

LRESULT RenderTargetTexture_Start(struct Object*, struct RenderTargetTexture*, wParam_t, StartEventPtr);

static struct PropertyType const RenderTargetTextureProperties[kRenderTargetTextureNumProperties] = {
	DECL(0x3b42dfbf, RenderTargetTexture, Width, Width, kDataTypeInt), // RenderTargetTexture.Width
	DECL(0x1bd13562, RenderTargetTexture, Height, Height, kDataTypeInt), // RenderTargetTexture.Height
	DECL(0x77ada720, RenderTargetTexture, TargetType, TargetType, kDataTypeEnum, .TypeString = "Color,Depth,Stencil,DepthStencil,Normal,Specular,Emission"), // RenderTargetTexture.TargetType
	DECL(0xdb3b9d57, RenderTargetTexture, SupportSimpleRenderTarget, SupportSimpleRenderTarget, kDataTypeBool), // RenderTargetTexture.SupportSimpleRenderTarget
	DECL(0x9048e288, RenderTargetTexture, Attachment, Attachment, kDataTypeEnum, .TypeString = "None,Color0,Color1,Color2,Color3,Depth,Stencil,DepthStencil"), // RenderTargetTexture.Attachment
	DECL(0x337c9af1, RenderTargetTexture, AllowDepthFallback, AllowDepthFallback, kDataTypeBool), // RenderTargetTexture.AllowDepthFallback
	DECL(0x76f1691e, RenderTargetTexture, SampleCount, SampleCount, kDataTypeInt), // RenderTargetTexture.SampleCount
};
static struct RenderTargetTexture RenderTargetTextureDefaults = {
};
LRESULT RenderTargetTextureProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventStart: return RenderTargetTexture_Start(object, cmp, wparm, lparm); // Start
	}
	return FALSE;
}
void luaX_pushRenderTargetTexture(lua_State *L, struct RenderTargetTexture const* RenderTargetTexture) {
	luaX_pushObject(L, CMP_GetObject(RenderTargetTexture));
}
struct RenderTargetTexture* luaX_checkRenderTargetTexture(lua_State *L, int idx) {
	return GetRenderTargetTexture(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _RenderTargetTexture = {
	.ClassName = "RenderTargetTexture",
	.DefaultName = "RenderTargetTexture",
	.ContentType = "RenderTargetTexture",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_RenderTargetTexture,
	.ClassSize = sizeof(struct RenderTargetTexture),
	.Properties = RenderTargetTextureProperties,
	.ObjProc = RenderTargetTextureProc,
	.Defaults = &RenderTargetTextureDefaults,
	.NumProperties = kRenderTargetTextureNumProperties,
};

LRESULT CubeMapTexture_Start(struct Object*, struct CubeMapTexture*, wParam_t, StartEventPtr);

static struct PropertyType const CubeMapTextureProperties[kCubeMapTextureNumProperties] = {
	DECL(0x59f82b67, CubeMapTexture, BackImage, BackImage, kDataTypeFixed), // CubeMapTexture.BackImage
	DECL(0xe5328805, CubeMapTexture, FrontImage, FrontImage, kDataTypeFixed), // CubeMapTexture.FrontImage
	DECL(0xd2e8522d, CubeMapTexture, LeftImage, LeftImage, kDataTypeFixed), // CubeMapTexture.LeftImage
	DECL(0x7d77ff5a, CubeMapTexture, RightImage, RightImage, kDataTypeFixed), // CubeMapTexture.RightImage
	DECL(0xea5c127f, CubeMapTexture, BottomImage, BottomImage, kDataTypeFixed), // CubeMapTexture.BottomImage
	DECL(0x5d1df0f9, CubeMapTexture, TopImage, TopImage, kDataTypeFixed), // CubeMapTexture.TopImage
};
static struct CubeMapTexture CubeMapTextureDefaults = {
};
LRESULT CubeMapTextureProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventStart: return CubeMapTexture_Start(object, cmp, wparm, lparm); // Start
	}
	return FALSE;
}
void luaX_pushCubeMapTexture(lua_State *L, struct CubeMapTexture const* CubeMapTexture) {
	luaX_pushObject(L, CMP_GetObject(CubeMapTexture));
}
struct CubeMapTexture* luaX_checkCubeMapTexture(lua_State *L, int idx) {
	return GetCubeMapTexture(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _CubeMapTexture = {
	.ClassName = "CubeMapTexture",
	.DefaultName = "CubeMapTexture",
	.ContentType = "CubeMapTexture",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_CubeMapTexture,
	.ClassSize = sizeof(struct CubeMapTexture),
	.Properties = CubeMapTextureProperties,
	.ObjProc = CubeMapTextureProc,
	.Defaults = &CubeMapTextureDefaults,
	.NumProperties = kCubeMapTextureNumProperties,
};

LRESULT IOSurfaceTexture_Start(struct Object*, struct IOSurfaceTexture*, wParam_t, StartEventPtr);

static struct PropertyType const IOSurfaceTextureProperties[kIOSurfaceTextureNumProperties] = {
	DECL(0xb5fc4968, IOSurfaceTexture, IOSurface, IOSurface, kDataTypeInt), // IOSurfaceTexture.IOSurface
};
static struct IOSurfaceTexture IOSurfaceTextureDefaults = {
};
LRESULT IOSurfaceTextureProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventStart: return IOSurfaceTexture_Start(object, cmp, wparm, lparm); // Start
	}
	return FALSE;
}
void luaX_pushIOSurfaceTexture(lua_State *L, struct IOSurfaceTexture const* IOSurfaceTexture) {
	luaX_pushObject(L, CMP_GetObject(IOSurfaceTexture));
}
struct IOSurfaceTexture* luaX_checkIOSurfaceTexture(lua_State *L, int idx) {
	return GetIOSurfaceTexture(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _IOSurfaceTexture = {
	.ClassName = "IOSurfaceTexture",
	.DefaultName = "IOSurfaceTexture",
	.ContentType = "IOSurfaceTexture",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_IOSurfaceTexture,
	.ClassSize = sizeof(struct IOSurfaceTexture),
	.Properties = IOSurfaceTextureProperties,
	.ObjProc = IOSurfaceTextureProc,
	.Defaults = &IOSurfaceTextureDefaults,
	.NumProperties = kIOSurfaceTextureNumProperties,
};


static struct PropertyType const VertexShaderProperties[kVertexShaderNumProperties] = {
	DECL(0x5dcdd537, VertexShader, Version, Version, kDataTypeInt), // VertexShader.Version
	DECL(0x1ecae757, VertexShader, FloatPrecision, FloatPrecision, kDataTypeEnum, .TypeString = "Unset,Low,Medium,High"), // VertexShader.FloatPrecision
	DECL(0x2cbcb34d, VertexShader, Shading, Shading, kDataTypeEnum, .TypeString = "Unlit,Phong,Standard"), // VertexShader.Shading
};
static struct VertexShader VertexShaderDefaults = {
};
LRESULT VertexShaderProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
	}
	return FALSE;
}
void luaX_pushVertexShader(lua_State *L, struct VertexShader const* VertexShader) {
	luaX_pushObject(L, CMP_GetObject(VertexShader));
}
struct VertexShader* luaX_checkVertexShader(lua_State *L, int idx) {
	return GetVertexShader(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _VertexShader = {
	.ClassName = "VertexShader",
	.DefaultName = "VertexShader",
	.ContentType = "VertexShader",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_VertexShader,
	.ClassSize = sizeof(struct VertexShader),
	.Properties = VertexShaderProperties,
	.ObjProc = VertexShaderProc,
	.Defaults = &VertexShaderDefaults,
	.NumProperties = kVertexShaderNumProperties,
};


static struct PropertyType const FragmentShaderProperties[kFragmentShaderNumProperties] = {
	DECL(0x5dcdd537, FragmentShader, Version, Version, kDataTypeInt), // FragmentShader.Version
	DECL(0x1ecae757, FragmentShader, FloatPrecision, FloatPrecision, kDataTypeEnum, .TypeString = "Unset,Low,Medium,High"), // FragmentShader.FloatPrecision
	DECL(0x0da660ff, FragmentShader, Out, Out, kDataTypeFixed), // FragmentShader.Out
};
static struct FragmentShader FragmentShaderDefaults = {
};
LRESULT FragmentShaderProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
	}
	return FALSE;
}
void luaX_pushFragmentShader(lua_State *L, struct FragmentShader const* FragmentShader) {
	luaX_pushObject(L, CMP_GetObject(FragmentShader));
}
struct FragmentShader* luaX_checkFragmentShader(lua_State *L, int idx) {
	return GetFragmentShader(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _FragmentShader = {
	.ClassName = "FragmentShader",
	.DefaultName = "FragmentShader",
	.ContentType = "FragmentShader",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_FragmentShader,
	.ClassSize = sizeof(struct FragmentShader),
	.Properties = FragmentShaderProperties,
	.ObjProc = FragmentShaderProc,
	.Defaults = &FragmentShaderDefaults,
	.NumProperties = kFragmentShaderNumProperties,
};

LRESULT Shader_Start(struct Object*, struct Shader*, wParam_t, StartEventPtr);
LRESULT Shader_Destroy(struct Object*, struct Shader*, wParam_t, DestroyEventPtr);

static struct PropertyType const ShaderProperties[kShaderNumProperties] = {
	DECL(0x0038792b, Shader, BlendMode, BlendMode, kDataTypeEnum, .TypeString = "AlphaAutomatic,Opaque,Alpha,Additive,PremultipliedAlpha,MixedAlpha"), // Shader.BlendMode
	DECL(0xb7e582be, Shader, DepthTestFunction, DepthTestFunction, kDataTypeEnum, .TypeString = "Never,Always,Less,LessOrEqual,Greater,GreaterOrEqual,Equal,NotEqual,Disabled"), // Shader.DepthTestFunction
	DECL(0x8ec3072e, Shader, DepthWriteEnabled, DepthWriteEnabled, kDataTypeBool), // Shader.DepthWriteEnabled
};
static struct Shader ShaderDefaults = {
  .BlendMode = kBlendModeMixedAlpha,
};
LRESULT ShaderProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventStart: return Shader_Start(object, cmp, wparm, lparm); // Start
		case kEventDestroy: return Shader_Destroy(object, cmp, wparm, lparm); // Destroy
	}
	return FALSE;
}
void luaX_pushShader(lua_State *L, struct Shader const* Shader) {
	luaX_pushObject(L, CMP_GetObject(Shader));
}
struct Shader* luaX_checkShader(lua_State *L, int idx) {
	return GetShader(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _Shader = {
	.ClassName = "Shader",
	.DefaultName = "Shader",
	.ContentType = "Shader",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_Shader,
	.ClassSize = sizeof(struct Shader),
	.Properties = ShaderProperties,
	.ObjProc = ShaderProc,
	.Defaults = &ShaderDefaults,
	.NumProperties = kShaderNumProperties,
};


static struct PropertyType const MaterialProperties[kMaterialNumProperties] = {
	DECL(0x7deb3888, Material, Shader, Shader, kDataTypeObject, .TypeString = "Shader"), // Material.Shader
	DECL(0x63792322, Material, GlobalAmbient, GlobalAmbient, kDataTypeStruct, .TypeString = "Color"), // Material.GlobalAmbient
	DECL(0x33f2678b, Material, Ambient, Ambient, kDataTypeStruct, .TypeString = "Color"), // Material.Ambient
	DECL(0x84d12add, Material, Diffuse, Diffuse, kDataTypeStruct, .TypeString = "Color"), // Material.Diffuse
	DECL(0x555cbaee, Material, Emissive, Emissive, kDataTypeStruct, .TypeString = "Color"), // Material.Emissive
	DECL(0xd5e66b37, Material, SpecularColor, SpecularColor, kDataTypeStruct, .TypeString = "Color"), // Material.SpecularColor
	DECL(0x841db767, Material, SpecularExponent, SpecularExponent, kDataTypeFloat), // Material.SpecularExponent
	DECL(0x994c5594, Material, Texture, Texture, kDataTypeObject, .TypeString = "Texture"), // Material.Texture
	DECL(0xf92ad452, Material, Texture2, Texture2, kDataTypeObject, .TypeString = "Texture"), // Material.Texture2
	DECL(0xe83ca8af, Material, TextureOffset, TextureOffset, kDataTypeStruct, .TypeString = "Vector2D"), // Material.TextureOffset
	DECL(0x861dbc5b, Material, TextureTiling, TextureTiling, kDataTypeStruct, .TypeString = "Vector2D"), // Material.TextureTiling
	DECL(0x5df90df9, Material, BlendIntensity, BlendIntensity, kDataTypeFloat), // Material.BlendIntensity
	DECL(0x0038792b, Material, BlendMode, BlendMode, kDataTypeEnum, .TypeString = "AlphaAutomatic,Opaque,Alpha,Additive,PremultipliedAlpha,MixedAlpha"), // Material.BlendMode
};
static struct Material MaterialDefaults = {
  .BlendMode = kBlendModeAlphaAutomatic,
};
LRESULT MaterialProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
	}
	return FALSE;
}
void luaX_pushMaterial(lua_State *L, struct Material const* Material) {
	luaX_pushObject(L, CMP_GetObject(Material));
}
struct Material* luaX_checkMaterial(lua_State *L, int idx) {
	return GetMaterial(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _Material = {
	.ClassName = "Material",
	.DefaultName = "Material",
	.ContentType = "Material",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_Material,
	.ClassSize = sizeof(struct Material),
	.Properties = MaterialProperties,
	.ObjProc = MaterialProc,
	.Defaults = &MaterialDefaults,
	.NumProperties = kMaterialNumProperties,
};

LRESULT Mesh_Start(struct Object*, struct Mesh*, wParam_t, StartEventPtr);
LRESULT Mesh_Destroy(struct Object*, struct Mesh*, wParam_t, DestroyEventPtr);

static struct PropertyType const MeshProperties[kMeshNumProperties] = {
	DECL(0x61e2a3f8, Mesh, Source, Source, kDataTypeFixed), // Mesh.Source
	DECL(0xcbd54f80, Mesh, Material, Material, kDataTypeObject, .TypeString = "Material"), // Mesh.Material
	DECL(0x553fd778, Mesh, MeshMorphTargets, MeshMorphTargets, kDataTypeFixed), // Mesh.MeshMorphTargets
};
static struct Mesh MeshDefaults = {
};
LRESULT MeshProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventStart: return Mesh_Start(object, cmp, wparm, lparm); // Start
		case kEventDestroy: return Mesh_Destroy(object, cmp, wparm, lparm); // Destroy
	}
	return FALSE;
}
void luaX_pushMesh(lua_State *L, struct Mesh const* Mesh) {
	luaX_pushObject(L, CMP_GetObject(Mesh));
}
struct Mesh* luaX_checkMesh(lua_State *L, int idx) {
	return GetMesh(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _Mesh = {
	.ClassName = "Mesh",
	.DefaultName = "Mesh",
	.ContentType = "Mesh",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_Mesh,
	.ClassSize = sizeof(struct Mesh),
	.Properties = MeshProperties,
	.ObjProc = MeshProc,
	.Defaults = &MeshDefaults,
	.NumProperties = kMeshNumProperties,
};

LRESULT FontFamily_Start(struct Object*, struct FontFamily*, wParam_t, StartEventPtr);
LRESULT FontFamily_Destroy(struct Object*, struct FontFamily*, wParam_t, DestroyEventPtr);

static struct PropertyType const FontFamilyProperties[kFontFamilyNumProperties] = {
	DECL(0xe750f2b7, FontFamily, Regular, Regular, kDataTypeFixed), // FontFamily.Regular
	DECL(0x45768d96, FontFamily, Bold, Bold, kDataTypeFixed), // FontFamily.Bold
	DECL(0x8db0c08d, FontFamily, Italic, Italic, kDataTypeFixed), // FontFamily.Italic
	DECL(0x6e1d4e1a, FontFamily, BoldItalic, BoldItalic, kDataTypeFixed), // FontFamily.BoldItalic
};
static struct FontFamily FontFamilyDefaults = {
};
LRESULT FontFamilyProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
		case kEventStart: return FontFamily_Start(object, cmp, wparm, lparm); // Start
		case kEventDestroy: return FontFamily_Destroy(object, cmp, wparm, lparm); // Destroy
	}
	return FALSE;
}
void luaX_pushFontFamily(lua_State *L, struct FontFamily const* FontFamily) {
	luaX_pushObject(L, CMP_GetObject(FontFamily));
}
struct FontFamily* luaX_checkFontFamily(lua_State *L, int idx) {
	return GetFontFamily(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _FontFamily = {
	.ClassName = "FontFamily",
	.DefaultName = "FontFamily",
	.ContentType = "FontFamily",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_FontFamily,
	.ClassSize = sizeof(struct FontFamily),
	.Properties = FontFamilyProperties,
	.ObjProc = FontFamilyProc,
	.Defaults = &FontFamilyDefaults,
	.NumProperties = kFontFamilyNumProperties,
};


static struct PropertyType const TrajectoryProperties[kTrajectoryNumProperties] = {
};
static struct Trajectory TrajectoryDefaults = {
};
LRESULT TrajectoryProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
	}
	return FALSE;
}
void luaX_pushTrajectory(lua_State *L, struct Trajectory const* Trajectory) {
	luaX_pushObject(L, CMP_GetObject(Trajectory));
}
struct Trajectory* luaX_checkTrajectory(lua_State *L, int idx) {
	return GetTrajectory(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _Trajectory = {
	.ClassName = "Trajectory",
	.DefaultName = "Trajectory",
	.ContentType = "Trajectory",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_Trajectory,
	.ClassSize = sizeof(struct Trajectory),
	.Properties = TrajectoryProperties,
	.ObjProc = TrajectoryProc,
	.Defaults = &TrajectoryDefaults,
	.NumProperties = kTrajectoryNumProperties,
};


static struct PropertyType const TimelineProperties[kTimelineNumProperties] = {
};
static struct Timeline TimelineDefaults = {
};
LRESULT TimelineProc(struct Object* object, void* cmp, uint32_t message, wParam_t wparm, lParam_t lparm) {
	switch (message) {
	}
	return FALSE;
}
void luaX_pushTimeline(lua_State *L, struct Timeline const* Timeline) {
	luaX_pushObject(L, CMP_GetObject(Timeline));
}
struct Timeline* luaX_checkTimeline(lua_State *L, int idx) {
	return GetTimeline(luaX_checkObject(L, idx));
}
ORCA_API struct ClassDesc _Timeline = {
	.ClassName = "Timeline",
	.DefaultName = "Timeline",
	.ContentType = "Timeline",
	.Xmlns = "http://schemas.corepunch.com/orca/2006/xml/presentation",
	.ParentClasses = {NULL},
	.ClassID = ID_Timeline,
	.ClassSize = sizeof(struct Timeline),
	.Properties = TimelineProperties,
	.ObjProc = TimelineProc,
	.Defaults = &TimelineDefaults,
	.NumProperties = kTimelineNumProperties,
};


int f_renderer_Init(lua_State *L) {
	uint32_t Width = luaL_checknumber(L, 1);
	uint32_t Height = luaL_checknumber(L, 2);
	bool_t Offscreen = lua_toboolean(L, 3);
	int32_t result_ = renderer_Init(Width, Height, Offscreen);
	lua_pushnumber(L, result_);
	return 1;
}
int f_renderer_Shutdown(lua_State *L) {
	renderer_Shutdown( );
	return 0;
}
int f_renderer_CreateShader(lua_State *L) {
	const char* vertex = luaL_checkstring(L, 1);
	const char* fragment = luaL_checkstring(L, 2);
	struct Shader* result_ = renderer_CreateShader(L, vertex, fragment);
	luaX_pushShader(L, result_);
	return 1;
}
int f_renderer_GetSize(lua_State *L) {
	return renderer_GetSize(L);
}
int f_renderer_DrawImage(lua_State *L) {
	renderer_DrawImage(L );
	return 0;
}

ORCA_API int luaopen_orca_renderer(lua_State *L) {
	luaL_newlib(L, ((luaL_Reg[]) { 
		{ "init", f_renderer_Init },
		{ "shutdown", f_renderer_Shutdown },
		{ "createShader", f_renderer_CreateShader },
		{ "getSize", f_renderer_GetSize },
		{ "drawImage", f_renderer_DrawImage },
		{ NULL, NULL } 
	}));
	void on_renderer_module_registered(lua_State *L);
	on_renderer_module_registered(L);
	// Structs
	lua_setfield(L, ((void)luaopen_orca_RenderScreenEventArgs(L), -2), "RenderScreenEventArgs");
	lua_setfield(L, ((void)luaopen_orca_RenderEventArgs(L), -2), "RenderEventArgs");
	// Components
	lua_setfield(L, ((void)lua_pushclass(L, &_Texture), -2), "Texture");
	lua_setfield(L, ((void)lua_pushclass(L, &_Image), -2), "Image");
	lua_setfield(L, ((void)lua_pushclass(L, &_RenderTargetTexture), -2), "RenderTargetTexture");
	lua_setfield(L, ((void)lua_pushclass(L, &_CubeMapTexture), -2), "CubeMapTexture");
	lua_setfield(L, ((void)lua_pushclass(L, &_IOSurfaceTexture), -2), "IOSurfaceTexture");
	lua_setfield(L, ((void)lua_pushclass(L, &_VertexShader), -2), "VertexShader");
	lua_setfield(L, ((void)lua_pushclass(L, &_FragmentShader), -2), "FragmentShader");
	lua_setfield(L, ((void)lua_pushclass(L, &_Shader), -2), "Shader");
	lua_setfield(L, ((void)lua_pushclass(L, &_Material), -2), "Material");
	lua_setfield(L, ((void)lua_pushclass(L, &_Mesh), -2), "Mesh");
	lua_setfield(L, ((void)lua_pushclass(L, &_FontFamily), -2), "FontFamily");
	lua_setfield(L, ((void)lua_pushclass(L, &_Trajectory), -2), "Trajectory");
	lua_setfield(L, ((void)lua_pushclass(L, &_Timeline), -2), "Timeline");
	return 1;
}
