// Generated by codegen utility
#include <include/api.h>

#include "<?= $moduleName ?>.h"

<?php foreach ($externalStructs as $name => $module): ?>
// <?= $name ?>
extern void luaX_push<?= $name ?>(lua_State *L, struct <?= $name ?> const* value);
extern struct <?= $name ?>* luaX_check<?= $name ?>(lua_State *L, int index);
<?php endforeach ?>

<?php include_template('export_enums'); ?>
<?php include_template('export_interfaces'); ?>
<?php include_template('export_structs'); ?>
<?php include_template('export_components'); ?>
<?php include_template('export_functions'); ?>

ORCA_API int luaopen_orca_<?= $moduleName ?>(lua_State *L) {
	luaL_newlib(L, ((luaL_Reg[]) { 
<?php foreach ($functions as $name => $func):?>
		{ "<?= lcfirst($name) ?>", f_<?= $prefix.$name ?> },
<?php endforeach ?>
		{ NULL, NULL } 
	}));
<?php if ($on_luaopen): ?>
	void <?= $on_luaopen ?>(lua_State *L);
	<?= $on_luaopen ?>(L);
<?php endif ?>
<?php foreach ($structs as $name => $struct):?>
	lua_setfield(L, ((void)luaopen_orca_<?= $name ?>(L), -2), "<?= $name ?>");
<?php endforeach ?>
<?php foreach ($interfaces as $name => $interface):?>
	lua_setfield(L, ((void)luaopen_orca_<?= $name ?>(L), -2), "<?= $name ?>");
<?php endforeach ?>
<?php foreach ($components as $name => $component):?>
	lua_setfield(L, ((void)lua_pushclass(L, &_<?= $name ?>), -2), "<?= $name ?>");
<?php endforeach ?>
	return 1;
}
