<?php require "model/module.php"; ?>
<?php $model = new Model($argv[1]); ?>
// Generated by codegen utility
#include <include/api.h>

#include "<?= $model->getModuleName() ?>.h"

<?php foreach ($model->getExternalStructs() as $name => $module): ?>
// <?= $name ?>
extern void luaX_push<?= $name ?>(lua_State *L, struct <?= $name ?> const* value);
extern struct <?= $name ?>* luaX_check<?= $name ?>(lua_State *L, int index);
<?php endforeach ?>

<?php // require "templates/export_enums.php"; ?>
<?php // require "templates/export_interfaces.php"; ?>
<?php // require "templates/export_structs.php"; ?>
<?php // require "templates/export_components.php"; ?>
<?php require "templates/export_functions2.php"; ?>

ORCA_API int luaopen_orca_<?= $model->getModuleName() ?>(lua_State *L) {
	luaL_newlib(L, ((luaL_Reg[]) { 
<?php foreach ($model->getFunctions() as $name => $func):?>
		{ "<?= lcfirst($name) ?>", f_<?= $model->prefix.$name ?> },
<?php endforeach ?>
		{ NULL, NULL } 
	}));
<?php if ($model->on_luaopen): ?>
	void <?= $model->on_luaopen ?>(lua_State *L);
	<?= $model->on_luaopen ?>(L);
<?php endif ?>
<?php foreach ($model->getStructs() as $name => $struct):?>
	lua_setfield(L, ((void)luaopen_orca_<?= $name ?>(L), -2), "<?= $name ?>");
<?php endforeach ?>
<?php foreach ($model->getInterfaces() as $name => $interface):?>
	lua_setfield(L, ((void)luaopen_orca_<?= $name ?>(L), -2), "<?= $name ?>");
<?php endforeach ?>
<?php foreach ($model->getComponents() as $name => $component):?>
	lua_setfield(L, ((void)lua_pushclass(L, &_<?= $name ?>), -2), "<?= $name ?>");
<?php endforeach ?>
	return 1;
}
