<?php require "model.py"; ?>
<?php $model = new Model($argv[1]); ?>
// Generated by codegen utility
#include <include/api.h>
#include "<?= substr($model->source, 0, -4) ?>.h"

#define DECL(SHORT, CLASS, NAME, FIELD, TYPE,...) { .Name=#CLASS"."#NAME, .Category=#CLASS, .ShortIdentifier=SHORT, .FullIdentifier=ID_##CLASS##_##NAME, .Offset=offsetof(struct CLASS, FIELD), .DataSize=sizeof(((struct CLASS *)NULL)->FIELD), .DataType=TYPE, ##__VA_ARGS__ }
#define ARRAY_DECL(SHORT, CLASS, NAME, FIELD, TYPE,...) { .Name=#CLASS"."#NAME, .Category=#CLASS, .ShortIdentifier=SHORT, .FullIdentifier=ID_##CLASS##_##NAME, .Offset=offsetof(struct CLASS, FIELD), .DataSize=sizeof(*((struct CLASS *)NULL)->FIELD), .DataType=TYPE, .IsArray=TRUE, ##__VA_ARGS__ }

<?php require "templates/export_enums.php"; ?>
<?php require "templates/export_structs.php"; ?>

#ifndef __<?= strtoupper($model->getModuleName()) ?>_PROPERTIES_H__
#define __<?= strtoupper($model->getModuleName()) ?>_PROPERTIES_H__
<?php foreach ($model->getComponents() as $classname => $class):?>
// <?= $classname ?>
#define ID_<?= $classname ?> 0x<?= hash('fnv1a32', $classname) ?>
#define Get<?= $classname ?>(_P) ((struct <?= $classname ?>*)((_P)?OBJ_GetComponent(_P,ID_<?= $classname ?>):NULL))
#define <?= $classname ?>_GetProperty(_P,_N) OBJ_GetPropertyAtIndex(_P,ID_<?= $classname ?>,sizeof(struct <?= $classname ?>),_N)
<?php foreach ($class->getProperties() as $name => $type) {
	$hashed_property = hash('fnv1a32', "$classname.$name");
	echo("#define ID_{$classname}_{$name} 0x$hashed_property // {$classname}.{$name}\n");
}?>
enum <?= $classname ?>Properties {
	<?php foreach ($class->getProperties() as $name => $type) {
		echo("\tk{$classname}{$name},\n")
	}
	echo("\tk{$classname}NumProperties")?>	
};
<?php endforeach ?>
#endif