// Generated by codegen utility
#ifndef __FILESYSTEM_H__
#define __FILESYSTEM_H__

#include <include/orca.h>

#include <source/filesystem/filesystem_properties.h>

typedef struct Workspace Workspace_t, *lpWorkspace_t;
typedef struct Workspace const cWorkspace_t, *lpcWorkspace_t;
/// @brief Push Workspace onto Lua stack.
ORCA_API void
luaX_pushWorkspace(lua_State *L, lpcWorkspace_t Workspace);
/// @brief Check Workspace form Lua stack at index.
ORCA_API lpWorkspace_t
luaX_checkWorkspace(lua_State *L, int idx);

typedef struct Project Project_t, *lpProject_t;
typedef struct Project const cProject_t, *lpcProject_t;
/// @brief Push Project onto Lua stack.
ORCA_API void
luaX_pushProject(lua_State *L, lpcProject_t Project);
/// @brief Check Project form Lua stack at index.
ORCA_API lpProject_t
luaX_checkProject(lua_State *L, int idx);

typedef struct Library Library_t, *lpLibrary_t;
typedef struct Library const cLibrary_t, *lpcLibrary_t;
/// @brief Push Library onto Lua stack.
ORCA_API void
luaX_pushLibrary(lua_State *L, lpcLibrary_t Library);
/// @brief Check Library form Lua stack at index.
ORCA_API lpLibrary_t
luaX_checkLibrary(lua_State *L, int idx);

typedef struct AnimationClipLibrary AnimationClipLibrary_t, *lpAnimationClipLibrary_t;
typedef struct AnimationClipLibrary const cAnimationClipLibrary_t, *lpcAnimationClipLibrary_t;
/// @brief Push AnimationClipLibrary onto Lua stack.
ORCA_API void
luaX_pushAnimationClipLibrary(lua_State *L, lpcAnimationClipLibrary_t AnimationClipLibrary);
/// @brief Check AnimationClipLibrary form Lua stack at index.
ORCA_API lpAnimationClipLibrary_t
luaX_checkAnimationClipLibrary(lua_State *L, int idx);

typedef struct ScreenLibrary ScreenLibrary_t, *lpScreenLibrary_t;
typedef struct ScreenLibrary const cScreenLibrary_t, *lpcScreenLibrary_t;
/// @brief Push ScreenLibrary onto Lua stack.
ORCA_API void
luaX_pushScreenLibrary(lua_State *L, lpcScreenLibrary_t ScreenLibrary);
/// @brief Check ScreenLibrary form Lua stack at index.
ORCA_API lpScreenLibrary_t
luaX_checkScreenLibrary(lua_State *L, int idx);

typedef struct MaterialTypeLibrary MaterialTypeLibrary_t, *lpMaterialTypeLibrary_t;
typedef struct MaterialTypeLibrary const cMaterialTypeLibrary_t, *lpcMaterialTypeLibrary_t;
/// @brief Push MaterialTypeLibrary onto Lua stack.
ORCA_API void
luaX_pushMaterialTypeLibrary(lua_State *L, lpcMaterialTypeLibrary_t MaterialTypeLibrary);
/// @brief Check MaterialTypeLibrary form Lua stack at index.
ORCA_API lpMaterialTypeLibrary_t
luaX_checkMaterialTypeLibrary(lua_State *L, int idx);

typedef struct MaterialLibrary MaterialLibrary_t, *lpMaterialLibrary_t;
typedef struct MaterialLibrary const cMaterialLibrary_t, *lpcMaterialLibrary_t;
/// @brief Push MaterialLibrary onto Lua stack.
ORCA_API void
luaX_pushMaterialLibrary(lua_State *L, lpcMaterialLibrary_t MaterialLibrary);
/// @brief Check MaterialLibrary form Lua stack at index.
ORCA_API lpMaterialLibrary_t
luaX_checkMaterialLibrary(lua_State *L, int idx);

typedef struct BrushLibrary BrushLibrary_t, *lpBrushLibrary_t;
typedef struct BrushLibrary const cBrushLibrary_t, *lpcBrushLibrary_t;
/// @brief Push BrushLibrary onto Lua stack.
ORCA_API void
luaX_pushBrushLibrary(lua_State *L, lpcBrushLibrary_t BrushLibrary);
/// @brief Check BrushLibrary form Lua stack at index.
ORCA_API lpBrushLibrary_t
luaX_checkBrushLibrary(lua_State *L, int idx);

typedef struct MeshLibrary MeshLibrary_t, *lpMeshLibrary_t;
typedef struct MeshLibrary const cMeshLibrary_t, *lpcMeshLibrary_t;
/// @brief Push MeshLibrary onto Lua stack.
ORCA_API void
luaX_pushMeshLibrary(lua_State *L, lpcMeshLibrary_t MeshLibrary);
/// @brief Check MeshLibrary form Lua stack at index.
ORCA_API lpMeshLibrary_t
luaX_checkMeshLibrary(lua_State *L, int idx);

typedef struct TimelineSequenceLibrary TimelineSequenceLibrary_t, *lpTimelineSequenceLibrary_t;
typedef struct TimelineSequenceLibrary const cTimelineSequenceLibrary_t, *lpcTimelineSequenceLibrary_t;
/// @brief Push TimelineSequenceLibrary onto Lua stack.
ORCA_API void
luaX_pushTimelineSequenceLibrary(lua_State *L, lpcTimelineSequenceLibrary_t TimelineSequenceLibrary);
/// @brief Check TimelineSequenceLibrary form Lua stack at index.
ORCA_API lpTimelineSequenceLibrary_t
luaX_checkTimelineSequenceLibrary(lua_State *L, int idx);

typedef struct SceneObjectLibrary SceneObjectLibrary_t, *lpSceneObjectLibrary_t;
typedef struct SceneObjectLibrary const cSceneObjectLibrary_t, *lpcSceneObjectLibrary_t;
/// @brief Push SceneObjectLibrary onto Lua stack.
ORCA_API void
luaX_pushSceneObjectLibrary(lua_State *L, lpcSceneObjectLibrary_t SceneObjectLibrary);
/// @brief Check SceneObjectLibrary form Lua stack at index.
ORCA_API lpSceneObjectLibrary_t
luaX_checkSceneObjectLibrary(lua_State *L, int idx);

typedef struct ComposerLibrary ComposerLibrary_t, *lpComposerLibrary_t;
typedef struct ComposerLibrary const cComposerLibrary_t, *lpcComposerLibrary_t;
/// @brief Push ComposerLibrary onto Lua stack.
ORCA_API void
luaX_pushComposerLibrary(lua_State *L, lpcComposerLibrary_t ComposerLibrary);
/// @brief Check ComposerLibrary form Lua stack at index.
ORCA_API lpComposerLibrary_t
luaX_checkComposerLibrary(lua_State *L, int idx);

typedef struct PipelineItemLibrary PipelineItemLibrary_t, *lpPipelineItemLibrary_t;
typedef struct PipelineItemLibrary const cPipelineItemLibrary_t, *lpcPipelineItemLibrary_t;
/// @brief Push PipelineItemLibrary onto Lua stack.
ORCA_API void
luaX_pushPipelineItemLibrary(lua_State *L, lpcPipelineItemLibrary_t PipelineItemLibrary);
/// @brief Check PipelineItemLibrary form Lua stack at index.
ORCA_API lpPipelineItemLibrary_t
luaX_checkPipelineItemLibrary(lua_State *L, int idx);

typedef struct SceneLibrary SceneLibrary_t, *lpSceneLibrary_t;
typedef struct SceneLibrary const cSceneLibrary_t, *lpcSceneLibrary_t;
/// @brief Push SceneLibrary onto Lua stack.
ORCA_API void
luaX_pushSceneLibrary(lua_State *L, lpcSceneLibrary_t SceneLibrary);
/// @brief Check SceneLibrary form Lua stack at index.
ORCA_API lpSceneLibrary_t
luaX_checkSceneLibrary(lua_State *L, int idx);

typedef struct TrajectoryLibrary TrajectoryLibrary_t, *lpTrajectoryLibrary_t;
typedef struct TrajectoryLibrary const cTrajectoryLibrary_t, *lpcTrajectoryLibrary_t;
/// @brief Push TrajectoryLibrary onto Lua stack.
ORCA_API void
luaX_pushTrajectoryLibrary(lua_State *L, lpcTrajectoryLibrary_t TrajectoryLibrary);
/// @brief Check TrajectoryLibrary form Lua stack at index.
ORCA_API lpTrajectoryLibrary_t
luaX_checkTrajectoryLibrary(lua_State *L, int idx);

typedef struct TransitionLibrary TransitionLibrary_t, *lpTransitionLibrary_t;
typedef struct TransitionLibrary const cTransitionLibrary_t, *lpcTransitionLibrary_t;
/// @brief Push TransitionLibrary onto Lua stack.
ORCA_API void
luaX_pushTransitionLibrary(lua_State *L, lpcTransitionLibrary_t TransitionLibrary);
/// @brief Check TransitionLibrary form Lua stack at index.
ORCA_API lpTransitionLibrary_t
luaX_checkTransitionLibrary(lua_State *L, int idx);

typedef struct SplineLibrary SplineLibrary_t, *lpSplineLibrary_t;
typedef struct SplineLibrary const cSplineLibrary_t, *lpcSplineLibrary_t;
/// @brief Push SplineLibrary onto Lua stack.
ORCA_API void
luaX_pushSplineLibrary(lua_State *L, lpcSplineLibrary_t SplineLibrary);
/// @brief Check SplineLibrary form Lua stack at index.
ORCA_API lpSplineLibrary_t
luaX_checkSplineLibrary(lua_State *L, int idx);

typedef struct PrefabLibrary PrefabLibrary_t, *lpPrefabLibrary_t;
typedef struct PrefabLibrary const cPrefabLibrary_t, *lpcPrefabLibrary_t;
/// @brief Push PrefabLibrary onto Lua stack.
ORCA_API void
luaX_pushPrefabLibrary(lua_State *L, lpcPrefabLibrary_t PrefabLibrary);
/// @brief Check PrefabLibrary form Lua stack at index.
ORCA_API lpPrefabLibrary_t
luaX_checkPrefabLibrary(lua_State *L, int idx);

typedef struct ProjectReferenceLibrary ProjectReferenceLibrary_t, *lpProjectReferenceLibrary_t;
typedef struct ProjectReferenceLibrary const cProjectReferenceLibrary_t, *lpcProjectReferenceLibrary_t;
/// @brief Push ProjectReferenceLibrary onto Lua stack.
ORCA_API void
luaX_pushProjectReferenceLibrary(lua_State *L, lpcProjectReferenceLibrary_t ProjectReferenceLibrary);
/// @brief Check ProjectReferenceLibrary form Lua stack at index.
ORCA_API lpProjectReferenceLibrary_t
luaX_checkProjectReferenceLibrary(lua_State *L, int idx);

typedef struct ProfileLibrary ProfileLibrary_t, *lpProfileLibrary_t;
typedef struct ProfileLibrary const cProfileLibrary_t, *lpcProfileLibrary_t;
/// @brief Push ProfileLibrary onto Lua stack.
ORCA_API void
luaX_pushProfileLibrary(lua_State *L, lpcProfileLibrary_t ProfileLibrary);
/// @brief Check ProfileLibrary form Lua stack at index.
ORCA_API lpProfileLibrary_t
luaX_checkProfileLibrary(lua_State *L, int idx);

typedef struct EnginePluginLibrary EnginePluginLibrary_t, *lpEnginePluginLibrary_t;
typedef struct EnginePluginLibrary const cEnginePluginLibrary_t, *lpcEnginePluginLibrary_t;
/// @brief Push EnginePluginLibrary onto Lua stack.
ORCA_API void
luaX_pushEnginePluginLibrary(lua_State *L, lpcEnginePluginLibrary_t EnginePluginLibrary);
/// @brief Check EnginePluginLibrary form Lua stack at index.
ORCA_API lpEnginePluginLibrary_t
luaX_checkEnginePluginLibrary(lua_State *L, int idx);

typedef struct ShortcutLibrary ShortcutLibrary_t, *lpShortcutLibrary_t;
typedef struct ShortcutLibrary const cShortcutLibrary_t, *lpcShortcutLibrary_t;
/// @brief Push ShortcutLibrary onto Lua stack.
ORCA_API void
luaX_pushShortcutLibrary(lua_State *L, lpcShortcutLibrary_t ShortcutLibrary);
/// @brief Check ShortcutLibrary form Lua stack at index.
ORCA_API lpShortcutLibrary_t
luaX_checkShortcutLibrary(lua_State *L, int idx);

typedef struct LayerLibrary LayerLibrary_t, *lpLayerLibrary_t;
typedef struct LayerLibrary const cLayerLibrary_t, *lpcLayerLibrary_t;
/// @brief Push LayerLibrary onto Lua stack.
ORCA_API void
luaX_pushLayerLibrary(lua_State *L, lpcLayerLibrary_t LayerLibrary);
/// @brief Check LayerLibrary form Lua stack at index.
ORCA_API lpLayerLibrary_t
luaX_checkLayerLibrary(lua_State *L, int idx);

typedef struct AnimationLibrary AnimationLibrary_t, *lpAnimationLibrary_t;
typedef struct AnimationLibrary const cAnimationLibrary_t, *lpcAnimationLibrary_t;
/// @brief Push AnimationLibrary onto Lua stack.
ORCA_API void
luaX_pushAnimationLibrary(lua_State *L, lpcAnimationLibrary_t AnimationLibrary);
/// @brief Check AnimationLibrary form Lua stack at index.
ORCA_API lpAnimationLibrary_t
luaX_checkAnimationLibrary(lua_State *L, int idx);

typedef struct TagLibrary TagLibrary_t, *lpTagLibrary_t;
typedef struct TagLibrary const cTagLibrary_t, *lpcTagLibrary_t;
/// @brief Push TagLibrary onto Lua stack.
ORCA_API void
luaX_pushTagLibrary(lua_State *L, lpcTagLibrary_t TagLibrary);
/// @brief Check TagLibrary form Lua stack at index.
ORCA_API lpTagLibrary_t
luaX_checkTagLibrary(lua_State *L, int idx);

typedef struct ThemeLibrary ThemeLibrary_t, *lpThemeLibrary_t;
typedef struct ThemeLibrary const cThemeLibrary_t, *lpcThemeLibrary_t;
/// @brief Push ThemeLibrary onto Lua stack.
ORCA_API void
luaX_pushThemeLibrary(lua_State *L, lpcThemeLibrary_t ThemeLibrary);
/// @brief Check ThemeLibrary form Lua stack at index.
ORCA_API lpThemeLibrary_t
luaX_checkThemeLibrary(lua_State *L, int idx);

typedef struct ResourceExportTagLibrary ResourceExportTagLibrary_t, *lpResourceExportTagLibrary_t;
typedef struct ResourceExportTagLibrary const cResourceExportTagLibrary_t, *lpcResourceExportTagLibrary_t;
/// @brief Push ResourceExportTagLibrary onto Lua stack.
ORCA_API void
luaX_pushResourceExportTagLibrary(lua_State *L, lpcResourceExportTagLibrary_t ResourceExportTagLibrary);
/// @brief Check ResourceExportTagLibrary form Lua stack at index.
ORCA_API lpResourceExportTagLibrary_t
luaX_checkResourceExportTagLibrary(lua_State *L, int idx);

typedef struct LocaleLibrary LocaleLibrary_t, *lpLocaleLibrary_t;
typedef struct LocaleLibrary const cLocaleLibrary_t, *lpcLocaleLibrary_t;
/// @brief Push LocaleLibrary onto Lua stack.
ORCA_API void
luaX_pushLocaleLibrary(lua_State *L, lpcLocaleLibrary_t LocaleLibrary);
/// @brief Check LocaleLibrary form Lua stack at index.
ORCA_API lpLocaleLibrary_t
luaX_checkLocaleLibrary(lua_State *L, int idx);

typedef struct DataSourceLibrary DataSourceLibrary_t, *lpDataSourceLibrary_t;
typedef struct DataSourceLibrary const cDataSourceLibrary_t, *lpcDataSourceLibrary_t;
/// @brief Push DataSourceLibrary onto Lua stack.
ORCA_API void
luaX_pushDataSourceLibrary(lua_State *L, lpcDataSourceLibrary_t DataSourceLibrary);
/// @brief Check DataSourceLibrary form Lua stack at index.
ORCA_API lpDataSourceLibrary_t
luaX_checkDataSourceLibrary(lua_State *L, int idx);

typedef struct PageTransitionCollectionLibrary PageTransitionCollectionLibrary_t, *lpPageTransitionCollectionLibrary_t;
typedef struct PageTransitionCollectionLibrary const cPageTransitionCollectionLibrary_t, *lpcPageTransitionCollectionLibrary_t;
/// @brief Push PageTransitionCollectionLibrary onto Lua stack.
ORCA_API void
luaX_pushPageTransitionCollectionLibrary(lua_State *L, lpcPageTransitionCollectionLibrary_t PageTransitionCollectionLibrary);
/// @brief Check PageTransitionCollectionLibrary form Lua stack at index.
ORCA_API lpPageTransitionCollectionLibrary_t
luaX_checkPageTransitionCollectionLibrary(lua_State *L, int idx);

typedef struct TextureLibrary TextureLibrary_t, *lpTextureLibrary_t;
typedef struct TextureLibrary const cTextureLibrary_t, *lpcTextureLibrary_t;
/// @brief Push TextureLibrary onto Lua stack.
ORCA_API void
luaX_pushTextureLibrary(lua_State *L, lpcTextureLibrary_t TextureLibrary);
/// @brief Check TextureLibrary form Lua stack at index.
ORCA_API lpTextureLibrary_t
luaX_checkTextureLibrary(lua_State *L, int idx);

typedef struct StyleLibrary StyleLibrary_t, *lpStyleLibrary_t;
typedef struct StyleLibrary const cStyleLibrary_t, *lpcStyleLibrary_t;
/// @brief Push StyleLibrary onto Lua stack.
ORCA_API void
luaX_pushStyleLibrary(lua_State *L, lpcStyleLibrary_t StyleLibrary);
/// @brief Check StyleLibrary form Lua stack at index.
ORCA_API lpStyleLibrary_t
luaX_checkStyleLibrary(lua_State *L, int idx);

typedef struct StateManagerLibrary StateManagerLibrary_t, *lpStateManagerLibrary_t;
typedef struct StateManagerLibrary const cStateManagerLibrary_t, *lpcStateManagerLibrary_t;
/// @brief Push StateManagerLibrary onto Lua stack.
ORCA_API void
luaX_pushStateManagerLibrary(lua_State *L, lpcStateManagerLibrary_t StateManagerLibrary);
/// @brief Check StateManagerLibrary form Lua stack at index.
ORCA_API lpStateManagerLibrary_t
luaX_checkStateManagerLibrary(lua_State *L, int idx);

typedef struct ConnectServiceLibrary ConnectServiceLibrary_t, *lpConnectServiceLibrary_t;
typedef struct ConnectServiceLibrary const cConnectServiceLibrary_t, *lpcConnectServiceLibrary_t;
/// @brief Push ConnectServiceLibrary onto Lua stack.
ORCA_API void
luaX_pushConnectServiceLibrary(lua_State *L, lpcConnectServiceLibrary_t ConnectServiceLibrary);
/// @brief Check ConnectServiceLibrary form Lua stack at index.
ORCA_API lpConnectServiceLibrary_t
luaX_checkConnectServiceLibrary(lua_State *L, int idx);

typedef struct ConnectUserServiceLibrary ConnectUserServiceLibrary_t, *lpConnectUserServiceLibrary_t;
typedef struct ConnectUserServiceLibrary const cConnectUserServiceLibrary_t, *lpcConnectUserServiceLibrary_t;
/// @brief Push ConnectUserServiceLibrary onto Lua stack.
ORCA_API void
luaX_pushConnectUserServiceLibrary(lua_State *L, lpcConnectUserServiceLibrary_t ConnectUserServiceLibrary);
/// @brief Check ConnectUserServiceLibrary form Lua stack at index.
ORCA_API lpConnectUserServiceLibrary_t
luaX_checkConnectUserServiceLibrary(lua_State *L, int idx);

typedef struct PropertyTypeLibrary PropertyTypeLibrary_t, *lpPropertyTypeLibrary_t;
typedef struct PropertyTypeLibrary const cPropertyTypeLibrary_t, *lpcPropertyTypeLibrary_t;
/// @brief Push PropertyTypeLibrary onto Lua stack.
ORCA_API void
luaX_pushPropertyTypeLibrary(lua_State *L, lpcPropertyTypeLibrary_t PropertyTypeLibrary);
/// @brief Check PropertyTypeLibrary form Lua stack at index.
ORCA_API lpPropertyTypeLibrary_t
luaX_checkPropertyTypeLibrary(lua_State *L, int idx);

typedef struct WI_MessageLibrary MessageLibrary_t, *lpMessageLibrary_t;
typedef struct WI_MessageLibrary const cMessageLibrary_t, *lpcMessageLibrary_t;
/// @brief Push MessageLibrary onto Lua stack.
ORCA_API void
luaX_pushMessageLibrary(lua_State *L, lpcMessageLibrary_t MessageLibrary);
/// @brief Check MessageLibrary form Lua stack at index.
ORCA_API lpMessageLibrary_t
luaX_checkMessageLibrary(lua_State *L, int idx);

typedef struct SystemMessage SystemMessage_t, *lpSystemMessage_t;
typedef struct SystemMessage const cSystemMessage_t, *lpcSystemMessage_t;
/// @brief Push SystemMessage onto Lua stack.
ORCA_API void
luaX_pushSystemMessage(lua_State *L, lpcSystemMessage_t SystemMessage);
/// @brief Check SystemMessage form Lua stack at index.
ORCA_API lpSystemMessage_t
luaX_checkSystemMessage(lua_State *L, int idx);

typedef struct ImageLibrary ImageLibrary_t, *lpImageLibrary_t;
typedef struct ImageLibrary const cImageLibrary_t, *lpcImageLibrary_t;
/// @brief Push ImageLibrary onto Lua stack.
ORCA_API void
luaX_pushImageLibrary(lua_State *L, lpcImageLibrary_t ImageLibrary);
/// @brief Check ImageLibrary form Lua stack at index.
ORCA_API lpImageLibrary_t
luaX_checkImageLibrary(lua_State *L, int idx);

typedef struct FontLibrary FontLibrary_t, *lpFontLibrary_t;
typedef struct FontLibrary const cFontLibrary_t, *lpcFontLibrary_t;
/// @brief Push FontLibrary onto Lua stack.
ORCA_API void
luaX_pushFontLibrary(lua_State *L, lpcFontLibrary_t FontLibrary);
/// @brief Check FontLibrary form Lua stack at index.
ORCA_API lpFontLibrary_t
luaX_checkFontLibrary(lua_State *L, int idx);

typedef struct ProjectReferenceItem ProjectReferenceItem_t, *lpProjectReferenceItem_t;
typedef struct ProjectReferenceItem const cProjectReferenceItem_t, *lpcProjectReferenceItem_t;
/// @brief Push ProjectReferenceItem onto Lua stack.
ORCA_API void
luaX_pushProjectReferenceItem(lua_State *L, lpcProjectReferenceItem_t ProjectReferenceItem);
/// @brief Check ProjectReferenceItem form Lua stack at index.
ORCA_API lpProjectReferenceItem_t
luaX_checkProjectReferenceItem(lua_State *L, int idx);

typedef struct LocaleReferenceItem LocaleReferenceItem_t, *lpLocaleReferenceItem_t;
typedef struct LocaleReferenceItem const cLocaleReferenceItem_t, *lpcLocaleReferenceItem_t;
/// @brief Push LocaleReferenceItem onto Lua stack.
ORCA_API void
luaX_pushLocaleReferenceItem(lua_State *L, lpcLocaleReferenceItem_t LocaleReferenceItem);
/// @brief Check LocaleReferenceItem form Lua stack at index.
ORCA_API lpLocaleReferenceItem_t
luaX_checkLocaleReferenceItem(lua_State *L, int idx);

typedef struct Tag Tag_t, *lpTag_t;
typedef struct Tag const cTag_t, *lpcTag_t;
/// @brief Push Tag onto Lua stack.
ORCA_API void
luaX_pushTag(lua_State *L, lpcTag_t Tag);
/// @brief Check Tag form Lua stack at index.
ORCA_API lpTag_t
luaX_checkTag(lua_State *L, int idx);

typedef struct EnginePlugin EnginePlugin_t, *lpEnginePlugin_t;
typedef struct EnginePlugin const cEnginePlugin_t, *lpcEnginePlugin_t;
/// @brief Push EnginePlugin onto Lua stack.
ORCA_API void
luaX_pushEnginePlugin(lua_State *L, lpcEnginePlugin_t EnginePlugin);
/// @brief Check EnginePlugin form Lua stack at index.
ORCA_API lpEnginePlugin_t
luaX_checkEnginePlugin(lua_State *L, int idx);

typedef struct EngineMetaclass EngineMetaclass_t, *lpEngineMetaclass_t;
typedef struct EngineMetaclass const cEngineMetaclass_t, *lpcEngineMetaclass_t;
/// @brief Push EngineMetaclass onto Lua stack.
ORCA_API void
luaX_pushEngineMetaclass(lua_State *L, lpcEngineMetaclass_t EngineMetaclass);
/// @brief Check EngineMetaclass form Lua stack at index.
ORCA_API lpEngineMetaclass_t
luaX_checkEngineMetaclass(lua_State *L, int idx);

typedef struct ThemeGroup ThemeGroup_t, *lpThemeGroup_t;
typedef struct ThemeGroup const cThemeGroup_t, *lpcThemeGroup_t;
/// @brief Push ThemeGroup onto Lua stack.
ORCA_API void
luaX_pushThemeGroup(lua_State *L, lpcThemeGroup_t ThemeGroup);
/// @brief Check ThemeGroup form Lua stack at index.
ORCA_API lpThemeGroup_t
luaX_checkThemeGroup(lua_State *L, int idx);

typedef struct Theme Theme_t, *lpTheme_t;
typedef struct Theme const cTheme_t, *lpcTheme_t;
/// @brief Push Theme onto Lua stack.
ORCA_API void
luaX_pushTheme(lua_State *L, lpcTheme_t Theme);
/// @brief Check Theme form Lua stack at index.
ORCA_API lpTheme_t
luaX_checkTheme(lua_State *L, int idx);

typedef struct Entry Entry_t, *lpEntry_t;
typedef struct Entry const cEntry_t, *lpcEntry_t;
/// @brief Push Entry onto Lua stack.
ORCA_API void
luaX_pushEntry(lua_State *L, lpcEntry_t Entry);
/// @brief Check Entry form Lua stack at index.
ORCA_API lpEntry_t
luaX_checkEntry(lua_State *L, int idx);

typedef struct ThemeDefaultValuesDictionary ThemeDefaultValuesDictionary_t, *lpThemeDefaultValuesDictionary_t;
typedef struct ThemeDefaultValuesDictionary const cThemeDefaultValuesDictionary_t, *lpcThemeDefaultValuesDictionary_t;
/// @brief Push ThemeDefaultValuesDictionary onto Lua stack.
ORCA_API void
luaX_pushThemeDefaultValuesDictionary(lua_State *L, lpcThemeDefaultValuesDictionary_t ThemeDefaultValuesDictionary);
/// @brief Check ThemeDefaultValuesDictionary form Lua stack at index.
ORCA_API lpThemeDefaultValuesDictionary_t
luaX_checkThemeDefaultValuesDictionary(lua_State *L, int idx);

#define kEventReadCommands 0x23d83fd3
typedef void* ReadCommandsEventPtr;

typedef struct Package Package_t, *lpPackage_t;
typedef struct Package const cPackage_t, *lpcPackage_t;
/// @brief Push Package onto Lua stack.
ORCA_API void
luaX_pushPackage(lua_State *L, lpcPackage_t Package);
/// @brief Check Package form Lua stack at index.
ORCA_API lpPackage_t
luaX_checkPackage(lua_State *L, int idx);

typedef struct Workspace Workspace, *WorkspacePtr;
typedef struct Workspace const *WorkspaceCPtr;
struct Workspace {
};

typedef struct Project Project, *ProjectPtr;
typedef struct Project const *ProjectCPtr;
struct Project {
	bool_t HalfFloatTextureFormat;
	bool_t HalfFloatTextureFormatLinear;
	bool_t HalfFloatColorAttachment;
	bool_t RenderToMipmapLevels;
	bool_t ExternalTexture;
	fixedString_t StartupScreen;
	color_t PreviewWindowBackgroundColor;
	int32_t MessageLimitPerFrame;
	int32_t GlobalTimelineStartTime;
	int32_t GlobalTimelineEndTime;
	fixedString_t BinaryExportDirectory;
	fixedString_t ApplicationExportDirectory;
	bool_t IsMasterProject;
	bool_t OptimizeMeshes;
	int32_t TargetPlatformVertexCacheSize;
	bool_t PlotAnimations;
	bool_t RoundImagesToNearestPowerOf2;
	bool_t ProjectExportShaderSourceCode;
	bool_t ProjectExportMainKzbWithBakedThemes;
	bool_t ProjectGroupByThemeNameInBakedThemeExport;
	bool_t IsLocalizationEnabled;
	bool_t FullScreenPreviewLayer;
	bool_t ShowChildrenInLayerThumbnails;
	vec2_t CompositionDesignSize;
	bool_t ProjectUsePremultipliedAlpha;
	bool_t ProjectRemoveICCProfilesOfPngs;
	fixedString_t BinaryFileName;
	bool_t IsAssetPackage;
	bool_t KanziConnectEnabled;
	fixedString_t DefaultMaterial;
	bool_t isPackage;
	lpPackage_t package;
};

typedef struct Library Library, *LibraryPtr;
typedef struct Library const *LibraryCPtr;
struct Library {
	bool_t IsExternal;
};

typedef struct AnimationClipLibrary AnimationClipLibrary, *AnimationClipLibraryPtr;
typedef struct AnimationClipLibrary const *AnimationClipLibraryCPtr;
struct AnimationClipLibrary {
};

typedef struct ScreenLibrary ScreenLibrary, *ScreenLibraryPtr;
typedef struct ScreenLibrary const *ScreenLibraryCPtr;
struct ScreenLibrary {
};

typedef struct MaterialTypeLibrary MaterialTypeLibrary, *MaterialTypeLibraryPtr;
typedef struct MaterialTypeLibrary const *MaterialTypeLibraryCPtr;
struct MaterialTypeLibrary {
};

typedef struct MaterialLibrary MaterialLibrary, *MaterialLibraryPtr;
typedef struct MaterialLibrary const *MaterialLibraryCPtr;
struct MaterialLibrary {
};

typedef struct BrushLibrary BrushLibrary, *BrushLibraryPtr;
typedef struct BrushLibrary const *BrushLibraryCPtr;
struct BrushLibrary {
};

typedef struct MeshLibrary MeshLibrary, *MeshLibraryPtr;
typedef struct MeshLibrary const *MeshLibraryCPtr;
struct MeshLibrary {
};

typedef struct TimelineSequenceLibrary TimelineSequenceLibrary, *TimelineSequenceLibraryPtr;
typedef struct TimelineSequenceLibrary const *TimelineSequenceLibraryCPtr;
struct TimelineSequenceLibrary {
};

typedef struct SceneObjectLibrary SceneObjectLibrary, *SceneObjectLibraryPtr;
typedef struct SceneObjectLibrary const *SceneObjectLibraryCPtr;
struct SceneObjectLibrary {
};

typedef struct ComposerLibrary ComposerLibrary, *ComposerLibraryPtr;
typedef struct ComposerLibrary const *ComposerLibraryCPtr;
struct ComposerLibrary {
};

typedef struct PipelineItemLibrary PipelineItemLibrary, *PipelineItemLibraryPtr;
typedef struct PipelineItemLibrary const *PipelineItemLibraryCPtr;
struct PipelineItemLibrary {
};

typedef struct SceneLibrary SceneLibrary, *SceneLibraryPtr;
typedef struct SceneLibrary const *SceneLibraryCPtr;
struct SceneLibrary {
};

typedef struct TrajectoryLibrary TrajectoryLibrary, *TrajectoryLibraryPtr;
typedef struct TrajectoryLibrary const *TrajectoryLibraryCPtr;
struct TrajectoryLibrary {
};

typedef struct TransitionLibrary TransitionLibrary, *TransitionLibraryPtr;
typedef struct TransitionLibrary const *TransitionLibraryCPtr;
struct TransitionLibrary {
};

typedef struct SplineLibrary SplineLibrary, *SplineLibraryPtr;
typedef struct SplineLibrary const *SplineLibraryCPtr;
struct SplineLibrary {
};

typedef struct PrefabLibrary PrefabLibrary, *PrefabLibraryPtr;
typedef struct PrefabLibrary const *PrefabLibraryCPtr;
struct PrefabLibrary {
};

typedef struct ProjectReferenceLibrary ProjectReferenceLibrary, *ProjectReferenceLibraryPtr;
typedef struct ProjectReferenceLibrary const *ProjectReferenceLibraryCPtr;
struct ProjectReferenceLibrary {
};

typedef struct ProfileLibrary ProfileLibrary, *ProfileLibraryPtr;
typedef struct ProfileLibrary const *ProfileLibraryCPtr;
struct ProfileLibrary {
};

typedef struct EnginePluginLibrary EnginePluginLibrary, *EnginePluginLibraryPtr;
typedef struct EnginePluginLibrary const *EnginePluginLibraryCPtr;
struct EnginePluginLibrary {
};

typedef struct ShortcutLibrary ShortcutLibrary, *ShortcutLibraryPtr;
typedef struct ShortcutLibrary const *ShortcutLibraryCPtr;
struct ShortcutLibrary {
};

typedef struct LayerLibrary LayerLibrary, *LayerLibraryPtr;
typedef struct LayerLibrary const *LayerLibraryCPtr;
struct LayerLibrary {
};

typedef struct AnimationLibrary AnimationLibrary, *AnimationLibraryPtr;
typedef struct AnimationLibrary const *AnimationLibraryCPtr;
struct AnimationLibrary {
};

typedef struct TagLibrary TagLibrary, *TagLibraryPtr;
typedef struct TagLibrary const *TagLibraryCPtr;
struct TagLibrary {
};

typedef struct ThemeLibrary ThemeLibrary, *ThemeLibraryPtr;
typedef struct ThemeLibrary const *ThemeLibraryCPtr;
struct ThemeLibrary {
};

typedef struct ResourceExportTagLibrary ResourceExportTagLibrary, *ResourceExportTagLibraryPtr;
typedef struct ResourceExportTagLibrary const *ResourceExportTagLibraryCPtr;
struct ResourceExportTagLibrary {
};

typedef struct LocaleLibrary LocaleLibrary, *LocaleLibraryPtr;
typedef struct LocaleLibrary const *LocaleLibraryCPtr;
struct LocaleLibrary {
};

typedef struct DataSourceLibrary DataSourceLibrary, *DataSourceLibraryPtr;
typedef struct DataSourceLibrary const *DataSourceLibraryCPtr;
struct DataSourceLibrary {
};

typedef struct PageTransitionCollectionLibrary PageTransitionCollectionLibrary, *PageTransitionCollectionLibraryPtr;
typedef struct PageTransitionCollectionLibrary const *PageTransitionCollectionLibraryCPtr;
struct PageTransitionCollectionLibrary {
};

typedef struct TextureLibrary TextureLibrary, *TextureLibraryPtr;
typedef struct TextureLibrary const *TextureLibraryCPtr;
struct TextureLibrary {
};

typedef struct StyleLibrary StyleLibrary, *StyleLibraryPtr;
typedef struct StyleLibrary const *StyleLibraryCPtr;
struct StyleLibrary {
};

typedef struct StateManagerLibrary StateManagerLibrary, *StateManagerLibraryPtr;
typedef struct StateManagerLibrary const *StateManagerLibraryCPtr;
struct StateManagerLibrary {
};

typedef struct ConnectServiceLibrary ConnectServiceLibrary, *ConnectServiceLibraryPtr;
typedef struct ConnectServiceLibrary const *ConnectServiceLibraryCPtr;
struct ConnectServiceLibrary {
};

typedef struct ConnectUserServiceLibrary ConnectUserServiceLibrary, *ConnectUserServiceLibraryPtr;
typedef struct ConnectUserServiceLibrary const *ConnectUserServiceLibraryCPtr;
struct ConnectUserServiceLibrary {
};

typedef struct PropertyTypeLibrary PropertyTypeLibrary, *PropertyTypeLibraryPtr;
typedef struct PropertyTypeLibrary const *PropertyTypeLibraryCPtr;
struct PropertyTypeLibrary {
};

typedef struct WI_MessageLibrary MessageLibrary, *MessageLibraryPtr;
typedef struct WI_MessageLibrary const *MessageLibraryCPtr;
struct WI_MessageLibrary {
};

typedef struct SystemMessage SystemMessage, *SystemMessagePtr;
typedef struct SystemMessage const *SystemMessageCPtr;
struct SystemMessage {
	fixedString_t Message;
	fixedString_t Key;
};

typedef struct ImageLibrary ImageLibrary, *ImageLibraryPtr;
typedef struct ImageLibrary const *ImageLibraryCPtr;
struct ImageLibrary {
};

typedef struct FontLibrary FontLibrary, *FontLibraryPtr;
typedef struct FontLibrary const *FontLibraryCPtr;
struct FontLibrary {
};

typedef struct ProjectReferenceItem ProjectReferenceItem, *ProjectReferenceItemPtr;
typedef struct ProjectReferenceItem const *ProjectReferenceItemCPtr;
struct ProjectReferenceItem {
};

typedef struct LocaleReferenceItem LocaleReferenceItem, *LocaleReferenceItemPtr;
typedef struct LocaleReferenceItem const *LocaleReferenceItemCPtr;
struct LocaleReferenceItem {
};

typedef struct Tag Tag, *TagPtr;
typedef struct Tag const *TagCPtr;
struct Tag {
	bool_t TagIsInherited;
};

typedef struct EnginePlugin EnginePlugin, *EnginePluginPtr;
typedef struct EnginePlugin const *EnginePluginCPtr;
struct EnginePlugin {
};

typedef struct EngineMetaclass EngineMetaclass, *EngineMetaclassPtr;
typedef struct EngineMetaclass const *EngineMetaclassCPtr;
struct EngineMetaclass {
	fixedString_t BaseClassName;
};

typedef struct ThemeGroup ThemeGroup, *ThemeGroupPtr;
typedef struct ThemeGroup const *ThemeGroupCPtr;
struct ThemeGroup {
	fixedString_t SelectedDictionary;
};

typedef struct Theme Theme, *ThemePtr;
typedef struct Theme const *ThemeCPtr;
struct Theme {
	bool_t IsThemeVisible;
};

typedef struct Entry Entry, *EntryPtr;
typedef struct Entry const *EntryCPtr;
struct Entry {
};

typedef struct ThemeDefaultValuesDictionary ThemeDefaultValuesDictionary, *ThemeDefaultValuesDictionaryPtr;
typedef struct ThemeDefaultValuesDictionary const *ThemeDefaultValuesDictionaryCPtr;
struct ThemeDefaultValuesDictionary {
};

/// @brief Retrieves main workspace object.
ORCA_API lpObject_t
FS_GetWorkspace(void);

/// @brief Gets the base filename from a path
ORCA_API const char*
FS_GetBaseName(const char* path);

/// @brief Extracts the path without query parameters
ORCA_API const char*
FS_GetPathName(const char* path, const char* out, int32_t maxlen);

/// @brief Extracts the directory path from a full file path
ORCA_API const char*
FS_GetDirName(const char* path, const char* out, int32_t maxlen);

/// @brief Joins two path segments into a complete path
ORCA_API const char*
FS_JoinPaths(const char* path1, const char* path2);

/// @brief Converts a module name to a file path
ORCA_API const char*
FS_PathFromModule(const char* module);

/// @brief Checks if any tracked files have been modified
ORCA_API bool_t
FS_HasChangedFiles(void);

/// @brief Creates a directory at the specified path
ORCA_API bool_t
FS_MakeDirectory(const char* path);

/// @brief Checks if a file exists at the specified path
ORCA_API bool_t
FS_FileExists(const char* path);

/// @brief Adds a package to the resource search path
ORCA_API lpPackage_t
FS_AddSearchPath(lua_State *L, const char* path);

#endif
