// Generated by XSLT code generator
// Component properties for filesystem

// Properties for Project
#define PROP_PROJECT_HALFFLOATTEXTUREFORMAT "HalfFloatTextureFormat"
#define PROP_PROJECT_HALFFLOATTEXTUREFORMATLINEAR "HalfFloatTextureFormatLinear"
#define PROP_PROJECT_HALFFLOATCOLORATTACHMENT "HalfFloatColorAttachment"
#define PROP_PROJECT_RENDERTOMIPMAPLEVELS "RenderToMipmapLevels"
#define PROP_PROJECT_EXTERNALTEXTURE "ExternalTexture"
#define PROP_PROJECT_STARTUPSCREEN "StartupScreen"
#define PROP_PROJECT_PREVIEWWINDOWBACKGROUNDCOLOR "PreviewWindowBackgroundColor"
#define PROP_PROJECT_MESSAGELIMITPERFRAME "MessageLimitPerFrame"
#define PROP_PROJECT_GLOBALTIMELINESTARTTIME "GlobalTimelineStartTime"
#define PROP_PROJECT_GLOBALTIMELINEENDTIME "GlobalTimelineEndTime"
#define PROP_PROJECT_BINARYEXPORTDIRECTORY "BinaryExportDirectory"
#define PROP_PROJECT_APPLICATIONEXPORTDIRECTORY "ApplicationExportDirectory"
#define PROP_PROJECT_ISMASTERPROJECT "IsMasterProject"
#define PROP_PROJECT_OPTIMIZEMESHES "OptimizeMeshes"
#define PROP_PROJECT_TARGETPLATFORMVERTEXCACHESIZE "TargetPlatformVertexCacheSize"
#define PROP_PROJECT_PLOTANIMATIONS "PlotAnimations"
#define PROP_PROJECT_ROUNDIMAGESTONEARESTPOWEROF2 "RoundImagesToNearestPowerOf2"
#define PROP_PROJECT_PROJECTEXPORTSHADERSOURCECODE "ProjectExportShaderSourceCode"
#define PROP_PROJECT_PROJECTEXPORTMAINKZBWITHBAKEDTHEMES "ProjectExportMainKzbWithBakedThemes"
#define PROP_PROJECT_PROJECTGROUPBYTHEMENAMEINBAKEDTHEMEEXPORT "ProjectGroupByThemeNameInBakedThemeExport"
#define PROP_PROJECT_ISLOCALIZATIONENABLED "IsLocalizationEnabled"
#define PROP_PROJECT_FULLSCREENPREVIEWLAYER "FullScreenPreviewLayer"
#define PROP_PROJECT_SHOWCHILDRENINLAYERTHUMBNAILS "ShowChildrenInLayerThumbnails"
#define PROP_PROJECT_COMPOSITIONDESIGNSIZE "CompositionDesignSize"
#define PROP_PROJECT_PROJECTUSEPREMULTIPLIEDALPHA "ProjectUsePremultipliedAlpha"
#define PROP_PROJECT_PROJECTREMOVEICCPROFILESOFPNGS "ProjectRemoveICCProfilesOfPngs"
#define PROP_PROJECT_BINARYFILENAME "BinaryFileName"
#define PROP_PROJECT_ISASSETPACKAGE "IsAssetPackage"
#define PROP_PROJECT_KANZICONNECTENABLED "KanziConnectEnabled"
#define PROP_PROJECT_DEFAULTMATERIAL "DefaultMaterial"
#define PROP_PROJECT_WIDTH "Width"
#define PROP_PROJECT_HEIGHT "Height"

// Properties for Library
#define PROP_LIBRARY_ISEXTERNAL "IsExternal"

// Properties for SystemMessage
#define PROP_SYSTEMMESSAGE_MESSAGE "Message"
#define PROP_SYSTEMMESSAGE_KEY "Key"

// Properties for Tag
#define PROP_TAG_TAGISINHERITED "TagIsInherited"

// Properties for EngineMetaclass
#define PROP_ENGINEMETACLASS_BASECLASSNAME "BaseClassName"

// Properties for ThemeGroup
#define PROP_THEMEGROUP_SELECTEDDICTIONARY "SelectedDictionary"

// Properties for Theme
#define PROP_THEME_ISTHEMEVISIBLE "IsThemeVisible"

