php:
	python3 -m pyphp.pyphp templates/header.php ../source/core/core.xml > ../source/core/core.h
	python3 -m pyphp.pyphp templates/properties.php ../source/core/core.xml > ../source/core/core_properties.h
	python3 -m pyphp.pyphp templates/export.php ../source/core/core.xml > ../source/core/core_export.c

	python3 -m pyphp.pyphp templates/header.php ../source/renderer/api/renderer.xml > ../source/renderer/api/renderer.h
	python3 -m pyphp.pyphp templates/properties.php ../source/renderer/api/renderer.xml > ../source/renderer/api/renderer_properties.h
	python3 -m pyphp.pyphp templates/export.php ../source/renderer/api/renderer.xml > ../source/renderer/api/renderer_export.c

	python3 -m pyphp.pyphp templates/header.php ../source/geometry/geometry.xml > ../source/geometry/geometry.h
	python3 -m pyphp.pyphp templates/properties.php ../source/geometry/geometry.xml > ../source/geometry/geometry_properties.h
	python3 -m pyphp.pyphp templates/export.php ../source/geometry/geometry.xml > ../source/geometry/geometry_export.c

	python3 -m pyphp.pyphp templates/header.php ../source/UIKit/UIKit.xml > ../source/UIKit/UIKit.h
	python3 -m pyphp.pyphp templates/properties.php ../source/UIKit/UIKit.xml > ../source/UIKit/UIKit_properties.h
	python3 -m pyphp.pyphp templates/export.php ../source/UIKit/UIKit.xml > ../source/UIKit/UIKit_export.c

