php:
	python3 -m pyphp.pyphp templates/export.php ../source/UIKit/UIKit.xml > ../source/UIKit/UIKit_export.c
# 	python3 -m pyphp.pyphp templates/export.php ../source/geometry/geometry.xml > ../source/geometry/geometry_export.c